### ISSUE TITLE
Empty message language changed

### ISSUE THREAD

**Issue by renato-mmex** [moneymanagerex/moneymanagerex#4296] opened 2022-04-17 09:27 UTC
MMEX version:
 - [x] **Version: 1.5.15-Beta.1 64-bit**
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows 11
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
appears when MMEX is started:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/76920138/163708405-a199eb60-9801-43ae-8f17-8cf01849bb0f.png">

but the previously valid language is used.
in the settings you can find the language: Aymara (instead of english) or Bosnian (instead of german)
If you redefine the language everything works again without message.

**Comment by renato-mmex** [comment] 2022-04-17 10:07
Perhaps this can be related to the call:
"C:\Program Files\Money Manager EX\bin\mmex.exe" -i C:\Users\bruec\AppData\Roaming\MoneyManagerEx\mmexini-d.db3
"C:\Program Files\Money Manager EX\bin\mmex.exe" -i C:\Users\bruec\AppData\Roaming\MoneyManagerEx\mmexini.db3
(I have two accounts in different languages).

MMEX is installed but above it says (Portabler Modus) on mmexini-d.db3  (german)

**Comment by vomikan** [comment] 2022-05-05 13:43
I can't reproduce this issue.

**Comment by vomikan** [comment] 2022-05-07 14:17
I just unpacked the archive with the program and launched it. A non-standard mmexini.db3 file issued such a warning. In the future, this does not manifest itself.

![image](https://user-images.githubusercontent.com/6836805/167258122-6a35c931-e844-4870-ad4d-41ba5391275f.png)

**Comment by vomikan** [comment] 2022-05-07 14:50
I found that for version 1.5.10, for example, the Russian language is stored as code 160 in the mmexini.db3 file.
But code 160 in the current version of wxWidgets is Ukrainian.

![image](https://user-images.githubusercontent.com/6836805/167259446-85eff501-00cd-4319-bb9c-45b6ae08eae7.png)

If you correct the code to 159, the message does not occur.
Solution: you just need to reassign the language when you first launch a new version of the application.

**Comment by vomikan** [comment] 2022-05-07 15:30
bool mmGUIApp::setGUILanguage(wxLanguage lang)

The function is quite confusing and requires correction.

**Comment by PMaff** [comment] 2022-05-07 17:34
Initially mmex should take the language that you set with the previous version (in the case of renato this might be a bit trickier).
If I select "system default" this emtpy dialog does not appear in Linux. 
See https://github.com/moneymanagerex/moneymanagerex/issues/4331

**Comment by vomikan** [comment] 2022-05-07 18:56
mmex stores the code (a certain number), not the name of the language. This is a conceptual mistake.

**Comment by PMaff** [comment] 2022-05-07 20:01
> mmex stores the code (a certain number), not the name of the language. This is a conceptual mistake.

Maybe it is possible to solve the language problem and the i18n problem in one go?
Like e.g.:
https://github.com/cospired/i18n-iso-languages
https://github.com/cospired/i18n-iso-languages/blob/main/README.md

**Closed** 2022-05-08 12:19 UTC
Labels: bug, fixed

**Comment by vomikan** [comment] 2022-06-07 11:20
You can use the brute force method to determine the language code.
```
    int lang_code = wxLANGUAGE_ENGLISH;
    wxString lang = "ru_RU"; //Option::instance().getLanguageID()
    for (lang_code; lang_code < wxLANGUAGE_USER_DEFINED; lang_code++)
    {
        const auto l = wxLocale::GetLanguageCanonicalName(lang_code);
        const auto n = wxLocale::GetLanguageName(lang_code);
        wxLogDebug("Language: %i  %s  %s", lang_code, l, n);
        if (lang == l)
            break;
    }
    wxLogDebug("Language found: %i", lang_code);
```

```
Language: 641  rof  Rombo
Language: 642  rof_TZ  Rombo (Tanzania)
Language: 643  ru  Russian
Language: 644  ru_BY  Russian (Belarus)
Language: 645  ru_KZ  Russian (Kazakhstan)
Language: 646  ru_KG  Russian (Kyrgyzstan)
Language: 647  ru_MD  Russian (Moldova)
Language: 648  ru_RU  Russian (Russia)
Language found: 648
```
