### ISSUE TITLE
Reference number format

### ISSUE THREAD

**Issue by RTMWEST** [moneymanagerex/moneymanagerex#4951] opened 2022-08-20 08:53 UTC
MMEX version:
 - [ ] 1.5.17
 - [ ] 1.5.18
 - [x ] 1.5.19
 - [ ] 1.5.20 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Item reference numbers seem to be formatted as numbers instead of plain text

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Enter for example #1234 in the reference number field

Expected result:

#1234

Actual result:

1,234.00

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment] 2022-08-20 09:14
Bug confirmed.

If you enter ABC, the Number field shows ABC in the transaction list

However, if you enter ABC1234, the Number field shows 1234.00 in the transaction list

**Comment by hrleno** [comment] 2022-08-20 15:24
I, too, have this issue with the latest update to mmex. What's the fix, if any?

**Comment by tactilis** [comment] 2022-08-20 15:48
> What's the fix, if any?

Just re-install the previous version of MMEX until you see the report of fix made in this Issue, then install the Beta build - or wait until the 1.5.20 release.

Yes, it's a bug and ideally it shouldn't be there. But it's trivial to go back to 1.5.18 and then wait a few weeks for a fix.

**Comment by hrleno** [comment] 2022-08-20 15:54
Thanks for the reply. That was going to be my next step.

Henry R. Leno, Jr.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by RTMWEST** [comment] 2022-08-20 16:50
Cheers Martin,

 

Will go back to 1.5.18 and wait for the fix in the next release.

**Comment by whalley** [comment] 2022-08-20 23:03
Not quite sure why this field is using mmtexctrl rather than wxtextctrl.

**Comment by tactilis** [comment] 2022-08-21 09:47
See also this forum post reporting a crash on MacOS - but I could not reproduce it on Windows.

[https://forum.moneymanagerex.org/viewtopic.php?p=23241](https://forum.moneymanagerex.org/viewtopic.php?p=23241)

**Comment by tactilis** [comment] 2022-08-21 10:19
@whalley
> Not quite sure why this field is using mmtexctrl rather than wxtextctrl.

I've just checked 1.5.18, 1.5.17 and 1.5.16. This is **not** a recent (i.e. 1.5.19) change.

The Number field is not a pure text field; it allows you to do maths - but things go wrong if you mix numeric and non-numeric characters.

```
Enter         Result after validation
abc               abc
123               123.00
abc123         123.00
100+23        123.00
abc 100+23 123.00
&(                   (    _and_ the error message 1: unexpected symbol near ';'
```

IMO, Number should be a free text field

**Comment by RTMWEST** [comment] 2022-08-21 15:24
Don’t know if it helps, but in Ver 1.5.18

 

Enter ABC123

 

Press return you get 123.00

 

Click directly on any other field, without pressing return, you get ABC123

**Comment by tactilis** [comment] 2022-08-21 15:40
Thank you @RTMWEST.

This difference is behaviour between 1.5.18 and 1.5.19 is known and, importantly, the cause is understood.

It will be fixed in 1.5.20.

**Comment by whalley** [comment] 2022-08-21 15:50
Fixed as part of https://github.com/moneymanagerex/moneymanagerex/issues/4946

**Comment by hrleno** [comment] 2022-08-21 19:17
I reverted back to ver. 1.5.18 and have no issues. That ABC123 thing doesn't work in ver. 18.

Henry R. Leno, Jr.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Closed** 2022-08-25 22:22 UTC
Labels: bug, fixed
