### ISSUE TITLE
Stocks/Shares - Application Crashes on Trying to Enter a Stock Transaction

### ISSUE THREAD

**Issue by steveknott** [moneymanagerex/moneymanagerex#4807] opened 2022-07-10 08:32 UTC
> Latest version appears to have 'broken' functionality to enter stock transactions:

- Select Stock Portfolio
- Right Click to "Add Stock Transaction..."
- Enter details: Share Number, Share Price, Date, Payee, Category, click OK
- Application crashes (shuts down) without saving transaction
- Restarting application shows message database marked open etc......

> Please do not remove information attached below this text.

<hr>Version: 1.5.16 <br>
 • Build: Jun 23 2022 13:30:13<br>
 • db 7 •  (aes128cbc)<br>
 • git 9d7ca6e (2022-06-23)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 22000), 64-bit edition<br>
 •  English (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by tactilis** [comment] 2022-07-10 09:11
Duplicate of #4778 (fixed)

**Comment by tactilis** [comment] 2022-07-10 10:17
@steveknott
You can download the latest pre-release beta of 1.5.17 here:

[https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/imon5yir2y1vf32t/artifact](https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/imon5yir2y1vf32t/artifacts)

Use either the  .exe installer, or the .zip portable installation.

This build should address the problem you reported and fixes some other issues in 1.5.16

**Comment by n-stein** [comment] 2022-09-14 18:37
Still crashes in 1.5.20. Steps to reproduce:

In any investment account create a new investment.
In stock dialog enter shares & price, press "Save"
When prompted to create a new share account select "OK"
Select "OK" again on account dialog to use default share account details
On share transaction dialog enter Payee and Category. Press "OK"
Back on stock dialog press "Close" --> Application crashes

currently debugging...

**Comment by n-stein** [comment] 2022-09-14 19:32
Crash is on this line

https://github.com/moneymanagerex/moneymanagerex/blob/67c46474a68d312254423c5c1fed6b15bfdc051d/src/stockdialog.cpp#L370

**Comment by n-stein** [comment] 2022-09-14 19:42
Sorry... crash isn't on that line, that's the last line which executes successfully. Crash is immediately after, so maybe its in the redraw of the stock list?

**Comment by vomikan** [comment] 2022-09-14 20:37
@n-stein Here is a similar example, conda application crashes for no reason.

https://github.com/moneymanagerex/moneymanagerex/issues/4778

**Comment by n-stein** [comment] 2022-09-14 21:48
Thanks, I found the offending line was similar to the one in #4778, specifically a call to mmGUIFrame::RefreshNavigationTree.
Fixed by PR #5079

**Closed** 2022-09-14 21:57 UTC
Labels: fixed, needs more info, stocks-shares
