### ISSUE TITLE
numéro de chèque 

### ISSUE THREAD

**Issue by Doudou72** [moneymanagerex/moneymanagerex#4997] opened 2022-08-30 06:46 UTC
impossible de rentrer un numéro de cheque autrement que sous forme décimale.

<hr>Version: 1.5.19 64-bit<br>
 • Build: Août 19 2022 17:40:30<br>
 • db 7 •  (aes128cbc)<br>
 • git 5419414ab (2022-08-19)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.0 (wxMac 12.5)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.3.1<br>
 • libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.23.2<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 13.1.6 (clang-1316.0.21.2.5)
<br>
<br>
OS:<br>
 • macOS Monterey Version 12.5.1 (assemblage 21G83)<br>
 •  French (France) (Western (Mac OS Roman))<br>
 • 1920x1080 32bit 72x72ppi
![Capture d’écran 2022-08-30 à 08 37 26](https://user-images.githubusercontent.com/112466301/187368563-13e928f6-3214-46bd-b52a-47efde3f4bbc.png)

**Comment by tactilis** [comment] 2022-08-30 07:10
Duplicate of https://github.com/moneymanagerex/moneymanagerex/issues/4951

Thanks for reporting this. This is a known problem and will be fixed in v1.5.20.

Please revert to 1.5.18 until 1.5.20 is out if this bug is causing you problems

**Closed** 2022-08-30 07:17 UTC
Labels: duplicate
