### ISSUE TITLE
Reports - Income vs Expenses

### ISSUE THREAD

**Issue by esrxd57** [moneymanagerex/moneymanagerex#5096] opened 2022-09-17 08:40 UTC
MMEX version:
 - [ ] 1.5.17
 - [x] 1.5.18
 - [ ] 1.5.19
 - [ ] 1.5.20
 - [ ] 1.5.21 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Report no longer working

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by tactilis** [comment] 2022-09-17 09:19
You have ticked v1.5.18 above. If this _is_ the version you are using, could you please update to version 1.5.20 and test again as there have been many bug fixes since 1.5.18.

Or you could wait a few days until 1.5.21 is out and test that.

Also, just stating "Report no longer working"  doesn't give much to go on.

Could you please describe exactly what the problem is in more detail as follows:

Reproduction steps:

_1. Do this...
2. Do this...
3. Do this..._

Expected result:

_Please say what do you expect to see._

Actual result:

_Please say what do you actually see._

**Comment by whalley** [comment] 2022-09-23 18:13
Closing. @esrxd57 feel free to re-open if you can supply more detail.

**Closed by whalley** 2022-09-23 18:13 UTC
Labels: needs more info
