### ISSUE TITLE
Transaction value being changed prior to Save

### ISSUE THREAD

**Issue by hayeswt** [moneymanagerex/moneymanagerex#3658] opened 2021-06-28 15:34 UTC
> Transactions over $999.99 revert to a value of $1.00 when the Amount field loses focus.  Transactions over $1999.99 revert to a value of $2.00 etc.  This happens for both Deposits and Withdrawals. It appears that the entered value reverts to the most significant value (in this case thousands), but all less significant digits are removed.

<hr>Version: 1.5.3 64-bit<br>
 • Build: Jun 13 2021 15:28:37<br>
 • db 7 •  (aes128cbc)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1366x768 32bit 96x96ppi
Transactions over $999.99 revert to a value of $1.00 when the Amount field loses focus.  Transactions over $1999.99 revert to a value of $2.00 etc.  This happens for both Deposits and Withdrawals. It appears that the value reverts to the most significant value (in this case thousands), but all less significant digits are removed.

**Comment by whalley** [comment] 2021-06-28 15:43
nown problem. Duplicate of #3626

Fixed in next version. Please see: https://forum.moneymanagerex.org/viewtopic.php?p=22139#p22139

**Comment by hayeswt** [comment] 2021-06-28 15:53
I see it, thanks.

**Closed** 2021-06-28 15:54 UTC
Labels: duplicate

**Comment by hayeswt** [comment] 2021-06-28 15:57
Cheers Mark.
