### ISSUE TITLE
Screen geometry

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3222] opened 2021-04-10 10:10 UTC
Hi

I test each new version on my 3 screens.
Since the last MMEX versions, MMEX no longer starts on the screen on
which it was last closed.
MMEX starts on the screen (landscape, 1920x1080) defined for the main
Windows display.

Greetings @renato-mmex 

https://github.com/moneymanagerex/moneymanagerex/issues/2877
https://github.com/moneymanagerex/moneymanagerex/issues/2826

**Comment by whalley** [comment] 2021-04-10 19:30
I can't seem to reproduce this on my Mac. Tried with just laptop screen and saves/recovers position, tried with attached display and it saves/recovers on which ever screen I choose. Have opened and closed on external monitor, disconnected external, opened and it detects no screen position and opens on laptop correctly.

**Comment by vomikan** [comment] 2021-04-10 19:55
The same for me.

**Comment by vomikan** [comment] 2021-04-14 13:37
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10379

**Comment by vomikan** [comment] 2021-04-16 09:42
![image](https://user-images.githubusercontent.com/6836805/115006094-21e52f00-9eb1-11eb-99c9-b4ba09e950f0.png)

**Comment by whalley** [comment] 2021-04-16 20:10
Added diagnostics menu under Help Menu that we can enable/disable as needed and update code to collect more info if we need to investigate fault further. May help in this case.

**Comment by vomikan** [comment] 2021-04-17 08:52
I have tested again.
1) MMEX full screen always opens on main screen.
2) MMEX partial image is always opened at the previously closed location.

Maybe this helps.
regards Renato use MMEX since 2009

**Comment by whalley** [comment] 2021-04-17 09:50
Never thought of checking that..... that may indeed be the source of the issue. Will check.

**Comment by renato-mmex** [comment] 2021-04-17 18:21
I have tested again:
When MMEX is docked at the edge of the screen, MMEX is subsequently opened on the main screen

**Comment by renato-mmex** [comment] 2021-04-17 19:53
**I also notice that the screen resolution of the main screen is always listed under "About":**

Money Manager Ex
Version: 1.5.1-RC.1 64-bit
• Build on Apr 17 2021 19:26:39
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.4 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg 
• libcurl/7.61.0-DEV WinSSL
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.16.2
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
Running on:
• Windows 10 (build 21359), 64-bit edition
• German (Swiss) (windows-1252)
**• 1920x1080 32bit 96x96ppi**

**Comment by vomikan** [comment] 2021-04-18 10:01
{675644} normal block at 0x00000204D3E8B380, 8 bytes long.
 Data: <@       > 40 A2 98 CD 04 02 00 00 
Object dump complete.

**Comment by vomikan** [comment] 2021-04-18 11:15
>When MMEX is docked at the edge of the screen, MMEX is subsequently opened on the main screen

![image](https://user-images.githubusercontent.com/6836805/115143496-5d6a2f80-a050-11eb-82bd-2dcd56c3f6e2.png)

**Comment by vomikan** [comment] 2021-04-18 11:27
The app has been docked to the left side

![image](https://user-images.githubusercontent.com/6836805/115143833-3c0a4300-a052-11eb-8009-b0411105cb6e.png)

**Comment by vomikan** [comment] 2021-04-18 11:33
Full screen

![image](https://user-images.githubusercontent.com/6836805/115144011-f9953600-a052-11eb-844c-1c8114913785.png)

**Comment by whalley** [comment] 2021-04-18 16:21
### wxDisplay Class Reference
**wxRect wxDisplay::GetClientArea () const**
Returns the client area of the display. The client area is the part of the display **available for the normal (non full screen) windows**, usually it is the same as GetGeometry() but it could be less if there is a taskbar (or equivalent) on this display.

**wxRect wxDisplay::GetGeometry () const**
Returns the bounding rectangle of the display whose index was passed to the constructor. 

Think we may need to use GetGeometry for the screen fit checks?

**Comment by renato-mmex** [comment] 2021-04-18 19:09
What I still don't understand is why it depends on the resolution of the screen. 
What is important is on which screen the window was closed in order to open it again, of course in the same resolution.

**Comment by whalley** [comment] 2021-04-18 20:05
The screen layout may have changed between saving last and opening. E.g laptop may be connected to or not an external display. We need to make sure we don’t open in a place that would be off any screen.

**Comment by renato-mmex** [comment] 2021-04-18 20:22
Of course, MMEX cannot be opened on a screen that does not exist, then it must be opened on the main screen. 
Let's assume that the picture opened on 2 screens (in my case, for example, No. 3+2), then this should also work. From my point of view, the upper left corner is always the reference position. All office programmes and many other software do this correctly.

**Comment by vomikan** [comment] 2021-04-21 19:19
I only see a problem in negative values when the app is pressed to the edge of the screen. It is difficult to understand the nature and magnitude of these values. But we must somehow allow such a small exit over the edges. This will solve some of the problems.
About the different screens. We can probably save the geometry for all screens. If the screen is not available, then use the main one.
```
{
    "Dafault": 3,
    {
        "Monitor":  1,
        "Geometry":  [
            0,
            0,
            100,
            100
        ]
    },
    {
        "Monitor":  2,
        "Geometry":  [
            0,
            0,
            200,
            200
        ]
    },
    {
        "Monitor":  3,
        "Geometry":  [
            0,
            0,
            300,
            200
        ]
    },
    
}
```

**Comment by renato-mmex** [comment] 2021-04-21 20:57
I used to program many such solutions, but I am an old school programmer (software), because I retired 23 years ago.

I would save the following items when exiting MMEX:
a) Screen number
b) position of the upper left corner of the MMEX window
c) the size of the MMEX window

When starting MMEX:

the saved screen is not present 
Open MMEX in fullscreen on the main monitor.


If the screen is present:
Open MMEX with the saved positions a), b), c).

However, problems could arise if the saved screen has a different (too small) resolution in the meantime. this could be solved by saving the resolution of this screen and comparing it when starting MMEX, if it does not match, MMEX should be opened on the main monitor.

**Comment by whalley** [comment] 2021-04-21 22:07
At present we do something very similar but instead of holding onto screen numbers we check if the logical window co-ords fit into any window. As @vomikan notes there is an issue with window geometry in wxWidgets reporting -ve numbers off the screen co-ords when windows are pressed to the edge.

We will look to get a fix in there for the 1.5.1 release.

**Comment by renato-mmex** [comment] 2021-04-21 22:15
would be happy if you can solve this problem.
gladly help with the tests
Greetings Renato

**Comment by whalley** [comment] 2021-04-27 19:43
A looser match to check if the window 'fits' onto a screen has been implemented. Now if the window has at least 50% of its real estate on any screen then it will be opened in the saved position, otherwise a default position on the main screen will be used. This solves the original main problem of it potentially opening on a screen that no longer exists whilst allowing some flexibility on location. Now you can save the position when it spans screens, is slightly off screen, or the reported geometry is slightly off!

Change is in master at present. @renato-mmex  @vomikan - Please test.

**Comment by renato-mmex** [comment] 2021-04-27 20:17
Hello Mark
Congratulations, have tested various positions and it seems to work.
See: 
https://forum.moneymanagerex.org/viewtopic.php?f=23&t=10379&p=21933#p21933
Greetings Renato


Am 27.04.2021 um 21:43 schrieb Mark Whalley:

**Closed** 2021-04-28 15:17 UTC
Labels: bug, fixed
