### ISSUE TITLE
Invalid Amount

### ISSUE THREAD

**Issue by SelwynND** [moneymanagerex/moneymanagerex#3677] opened 2021-06-30 22:56 UTC
Hi, I'm using MM Ex Ver 1.5.3 64-bit on a Windows 10 Pro Ver 21H1 Laptop.
When I try to enter a Split Transaction I enter the figures correctly but it returns a message, "Invalid Amount. Please enter a positive or calculated value.  ......" and changes the value from say $2335.35 to $2.00".
I've tried everything I can think of to resolve this issue with no success. Do you have any suggestions for me?
Thanks and regards from New Zealand. (Down Under)
Selwyn

**Comment by whalley** [comment] 2021-06-30 23:16
Likely related to this issue: https://github.com/moneymanagerex/moneymanagerex/issues/3626

Can you confirm that values less that $1000 work as expected.

The issue is fixed in the imminent 1.5.4 release.

**Comment by Django84** [comment] 2021-07-02 09:31
I also have this problem and have not yet received a new version of the program. Do I have to wait now so that the error may not occur again?

**Comment by whalley** [comment] 2021-07-02 09:44
You can get the latest beta build, with the fix included here:

- Windows: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/id99ma244152d31y/artifacts
- Mac: : https://mmex.ipx.co.uk/

**Comment by Django84** [comment] 2021-07-02 15:30
Thank you for your info. All seams to be ok now.

**Closed** 2021-07-14 18:44 UTC
Labels: bug, duplicate, fixed
