### ISSUE TITLE
Recurring transactions

### ISSUE THREAD

**Issue by Big-Mug** [moneymanagerex/moneymanagerex#1217] opened 2017-07-05 11:20 UTC
make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [ x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
-  Check MMEX version
  - [ x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by callmenemo491** [comment] 2017-07-06 14:28
Duplicate of #1218.

**Closed** 2017-07-06 16:03 UTC
Labels: duplicate
