### ISSUE TITLE
Using transfer in editing multi-transactions

### ISSUE THREAD

**Issue by zer0feel** [moneymanagerex/moneymanagerex#3897] opened 2021-10-02 05:43 UTC
MMEX version:
 - [x] 1.5.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows

# Description of the bug

1. Select multiple entries
2. Right click and select "Edit Transactions"
3. Check "Type" and select "Transfer"
4. Check "Transfer to" and select an account
5. Click OK

# Reproduction

Is the bug reproducible? 
 - [x] Always 

Reproduction steps:
Same as above

Expected result:
The payee column of the multiple entries should change to the account selected with the arrow < or >.

Actual result:
There is no change to the entries after closing the dialog

**Comment by whalley** [comment] 2021-10-02 15:20
Yes the multiple edit does not support changed withdrawals/deposits to transfer, neither does it support changing transfers to withdrawals/deposits.

**Comment by tactilis** [comment] 2021-10-03 07:51
If it is intended that multiple edit should not support changing withdrawals/deposits to transfers or vice versa, then there probably should be a message informing the user of this.

It could be displayed when OK is clicked (or maybe even when Type is changed inappropriately), rather than silently closing the dialog, which leads to the user thinking that the change has been actioned.
 
 
Alternatively, if change of Type involving transfers could be made to work the problem would go away.

**Comment by whalley** [comment] 2021-10-03 09:08
Agreed, we can tidy this up.

**Comment by whalley** [comment] 2021-12-13 23:33
I have made the following changes to the multi-transaction edit option. Rather than the current logic of accepting user input and then trying to make changes to transactions if possible I have taken the approach that if the users wishes to edit a field then it should apply to all transactions in the set to be edited - ie.. it is explicit. I think this is clearer from a user perspective.

So, the following has been implemented:

1. Locked transactions are not updated.
2. The amount field cannot be edited if any transactions in the edit have split transactions.
2. The amount field cannot be edited if any transactions in the edit include transfers between accounts with differing currencies.
3. The payee field cannot be edited if any transactions in the edit are transfers, unless an explicit change to 'Deposit'/'Withdrawal' is specified in which case Payee is mandatory in order to change the transfer transactions
4. The 'To Account' field cannot be edited if any transactions in the edit are 'Deposit'/'Withdrawal' unless an explicit change to 'Transfer' is specified in which case 'To Account' is mandatory in order to change the 'Deposit'/'Withdrawal' transactions.
5. The category field cannot be edited if any transactions in the edit have split transactions.

Would appreciate some testing on this to ensure there are no bugs / odd combinations in there.

**Comment by zer0feel** [comment] 2021-12-27 17:19
I have installed version 1.5.11, here are the testing result:
Regarding point 4 and 5 by Whalley, it works accordingly. But nothing is updated after selecting the account and pressing OK.

Moreover, it is more logic that if it is a "transfer" deposit transaction, the field should display "From account". If it is a "transfer" withdrawal transaction, the field display "To account".

**Comment by whalley** [comment] 2021-12-28 19:04
@zer0feel The 'fix' for this is not in 1.5.11, it is in the latest beta - You can download latest version here: https://ci.appveyor.com/project/moneymanagerex/moneymanagerex

**Comment by zer0feel** [comment] 2021-12-30 17:01
Thanks, just tried. Would it be better to add "Transfer from" in addition to "Transfer to" to choose the transfer direction? Moreover, once the transfer done, the amount change to zero because "advance" is checked when I look into the transaction.

**Comment by whalley** [comment] 2021-12-30 18:25
@zer0feel I think having an option to change the 'Transfer From' would over complicate the logic, and would differ from the standard way of creating/modifying transactions where you start from the 'From' account and specify the transaction in terms of that.

I can't reproduce the issue with advanced transactions being 'checked' for the transactions being edited - seems to work for me. Do you have a sample DB or can explain exactly what the transactions looked like prior to invoking the transaction edit, together with what you changed in the edit.

**Comment by grachte** [comment] 2022-01-03 08:46
I have tested the latest 1.5.12-Beta build, and found that the amount value at transfer to side is always zero (modify 2 transactions). So a transfer from account A to B, A side is ok, B side is zero because advanced is checked in B side transaction.

**Comment by whalley** [comment] 2022-01-03 18:42
Should have now fixed the issue with 'advanced transaction' and zero values. In doing this I have adjusted the logic to consider transactions between accounts with differing currencies. The logic in now....

- Locked transactions are not updated.
- The amount field cannot be edited if any transactions in the edit have split transactions.
- The payee field cannot be edited if any transactions in the edit are transfers, unless an explicit change to 'Deposit'/'Withdrawal' is specified in which case Payee is mandatory in order to change the transfer transactions
- The 'To Account' field cannot be edited if any transactions in the edit are 'Deposit'/'Withdrawal' unless an explicit change to 'Transfer' is specified in which case 'To Account' is mandatory in order to change the 'Deposit'/'Withdrawal' transactions.
- The category field cannot be edited if any transactions in the edit have split transactions.
- Cannot change to 'Transfer' if any transactions in the edit have split transactions.
- **If changes result in a 'Transfer' between accounts with differing currencies then the amount specified is for the 'From' account and the  conversion rate on the date of the transaction will be used to calculate the 'To' account amount, otherwise the amount for the 'To' and 'From' account will be the same.**

**Comment by whalley** [comment] 2022-01-03 18:47
Pushed change - https://github.com/moneymanagerex/moneymanagerex/pull/4093/commits/56ad1b12d9a77b0c08a45b44db5030dd76363614

**Comment by grachte** [comment] 2022-01-03 21:33
Thanks for the quick fix! Is there a new build so that i can do some further testing?

**Comment by whalley** [comment] 2022-01-03 22:59
https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/build/job/yv8ku6ikxhlr43jf/artifacts

**Comment by grachte** [comment] 2022-01-04 11:37
Hi whalley, here some new findings with the latest build.
- The 'advanced transaction' problem looks ok now, thanks for that.
- However, I found a new problem with the modify to type Transfer: 
I have a mixture of transaction in 'account A', some Deposit and some Withdrawal that I modify to Type = 'Transfer', and Transfer To = 'account B'.
- In 'account A' all transaction are modified to 'Withdrawal' and Payee '> B'
- In 'account B' all transaction are modified to 'Deposit' and Payee '< A'
- It's clear that deposit/withdrawal values should remain the same in 'A' and the opposite in 'B'.
- Also, the Payee direction of transfer ‘<’ or ‘>’ should be adapted according to deposit/withdrawal values of the original transaction.

It’s a bit difficult to explain… but I hope you understand my point here.

**Comment by grachte** [comment] 2022-01-04 11:50
Also take care of the case when amount value is zero!

**Comment by whalley** [comment] 2022-01-04 12:36
> Hi whalley, here some new findings with the latest build.
> 
> * The 'advanced transaction' problem looks ok now, thanks for that.

Great !

> * However, I found a new problem with the modify to type Transfer:
>   I have a mixture of transaction in 'account A', some Deposit and some Withdrawal that I modify to Type = 'Transfer', and Transfer To = 'account B'.
> * In 'account A' all transaction are modified to 'Withdrawal' and Payee '> B'
> * In 'account B' all transaction are modified to 'Deposit' and Payee '< A'

The behaviour you describe is how it is designed to work, it simply just changes the Deposit/Withdrawal to a 'Transfer To' Account B.  **If you wanted deposits to appear as transfers to Account A then I would suggest first moving them to Account B and then changing to a Transfer to Account A.**

'> B' indicates a transfer to Account B which was what you requested and the 'Withdrawal' column is just showing that the money is moving from 'A' to 'B', i.e. being withdrawn form 'A'.  
Likewise the '< A' indicates a transfer from B to A and the 'Deposit' column is just showing that the money is moving from 'A' to 'B', i.e. being deposited into 'A'.   

This is how transfers are represented in MMEX.

**Comment by whalley** [comment] 2022-01-04 12:38
> Also take care of the case when amount value is zero!

Can you describe the issue with an amount of zero?

**Comment by grachte** [comment] 2022-01-04 13:24
Reversed logic for withdrawal would make it much more useful. To create a transfer from B to A, having to move first the transaction from A to B, then create the transfer is an extra action. You have to careful split deposits and withdrawals, possible make mistakes here, while it can be done automatic when you implement the reverse logic. I understand the current design logic which is also a valid way of implement it, but my proposal should maybe be called a different transfer option.
The zero amount is just the point to differentiate between deposit an withdrawal (+ 0 -).

**Comment by grachte** [comment] 2022-01-04 13:48
My goal is to take any transaction, and convert it to a transfer while keeping the original account A and payee B and amount value being it deposits or withdrawals (or zero). Depending on the amount value positive or negative, decide on the direction of the transfer. I believe it really would be an added value for mmex. Thanks for considering. Regards Eric

**Comment by tactilis** [comment] 2022-01-04 14:15
> My goal is to take any transaction, and convert it to a transfer while keeping the original account A and payee B and amount value being it deposits or withdrawals (or zero). Depending on the amount value positive or negative, decide on the direction of the transfer.

@grachte Could you please explain clearly your use case for this please? I am failing to understand at present.

How do you get into the situation where you have deposits (or withdrawals) recorded between Account A and **Payee** B that you then want to change into a Transfer?

Transfers are only between two MMEX accounts, not payees.

**Comment by grachte** [comment] 2022-01-04 15:23
I have several MMEX accounts, for each of them I have imported a lot of transactions using the CSV import feature. During import transactions are not directly converted to transfers. As such I have a lot of transaction where the Payee corresponds to one/several of my MMEX accounts. So, if a Payee corresponds with an existing MMEX account, that transaction must be converted to a transfer. If the payee does not correspond to an MMEX account, then transfer is indeed impossible.

**Comment by whalley** [comment] 2022-01-04 15:42
> Reversed logic for withdrawal would make it much more useful.
> ...
> I understand the current design logic which is also a valid way of implement it, but my proposal should maybe be called a different transfer option. 

My view is that
1) Use of the multi-transaction edits would be rare
2) They should be made with caution

Therefore I think it is sensible to keep the logic simplistic, yet provide the flexibility to make bulk changes. It seems we have the flexibility with Move/Edit of transactions to support your needs,

> The zero amount is just the point to differentiate between deposit and withdrawal (+ 0 -).

With current logic we don't need to consider +0 and -0.

**Comment by whalley** [comment] 2022-01-04 16:55
> In my transfer proposal, you only have to select the transaction that need to be converted to transfer, that’s all (no Transfer To, no Move needed), from user point of view dead simple logic, no any chance to make faults.
> Just add a menu option to initiate “Auto Modify Transaction – To Transfer”.

But you would need to specify the target/source 'Account'. 

> Every new MMEX user that imports a database from another program will face the same problem! If you want to make MMEX attractive for NEW users, then a simplification of the import/conversion process is highly needed.

I agree the import code needs to be potentially improved to support logic whereby it can create transfers. Again, I think including this in the multi-edit would lead to confusion.

**Comment by grachte** [comment] 2022-01-04 16:59
No the target/source account is already available in the original transaction (may even be different for several transaction in the set to be modified). Just use that to create the transfer.

**Comment by grachte** [comment] 2022-01-04 17:10
You are right, the best place to improve transfer is implement it during import, where you try to match a record to be imported against an existing transaction. But hey, I did not dare to ask for this. 
But for me this comes too late, since the import is already done, and I spent a lot of work on it already. I would greatly appreciate a workaround.

**Comment by whalley** [comment] 2022-01-04 17:40
> No the target/source account is already available in the original transaction (may even be different for several transaction in the set to be modified). Just use that to create the transfer.

In your case the Payee may have the same name as the Account you wish to transfer to, but there is no reason why a Payee and Account cannot exist with same name for different purposes. I feel it is dangerous to make such assumptions.  

> You are right, the best place to improve transfer is implement it during import, where you try to match a record to be imported against an existing transaction. But hey, I did not dare to ask for this.

Think we are in agreement we need a specialised function as part of the import logic (or can be run after all accounts are imported) that did a tidy-up of all such transactions by matching them and then perhaps removing the names from the Payee list when complete. That would be the most user-friendly fix.

> But for me this comes too late, since the import is already done, and I spent a lot of work on it already. I would greatly appreciate a workaround.

Why would this not work... for this imported data set (I'm assuming that this is what you have after import)

```
a. Acc=A, Payee=B, Withdrawal Amount=W
b. Acc=A, Payee=B, Withdrawal Amount=X
c. Acc=A, Payee=B, Deposit Amount=Y
d. Acc=A, Payee=B, Deposit Amount=Z

e. Acc=B, Payee=A, Deposit Amount=W
f. Acc=B, Payee=A, Deposit Amount=X
g. Acc=B, Payee=A, Withdrawal Amount=Y
h. Acc=B, Payee=A, Withdrawal Amount=Z
```

1. For each account, sort by payee
    1. Select and Delete all Deposits where Payee=*another account* **Bulk Delete**
    2. Select and Change the Withdrawal where Payee=*another account* to a Transfer To=*another account* **Multi Edit** which results in

This will remove (c), (d), (e), (f), and change (a), (b), (g), (h) into the transfers...

```
a. Acc=A, To Account=B, Transfer Amount=W
b. Acc=A, To Account=B, Transfer Amount=X

g. Acc=B, To Account=A, Transfer Amount=Y
h. Acc=B, To Account=A, Transfer Amount=Z
```

**Comment by grachte** [comment] 2022-01-04 21:33
If you think of it that an mmex account has a unique account number associated to it, and the same applies for any payee then it's fair to assume that corresponding account names and payee names are unique for the system. So for me there should not be a different meaning for an mmex account or payee with the same name. That has always been my assumption. If you don't enforce this rule, you are unable to create on one end a transaction from mmex account A to mmex account B, and another transaction from mmex account A to payee with the same name B. Both account B name and payee B name must then be part of the payee list but here the name is unique.

The workaround you describe here I understand completely that it's feasible, but it's the hard workaround not the soft workaround I am looking for.

Thanks for having this discussion with me! I have my viewpoints, you have yours based on how mmex has been developed I guess. I just want to be helpful to your project.

Best regards, Eric

**Comment by tactilis** [comment] 2022-01-04 22:17
> Both account B name and payee B name must then be part of the payee list but here the name is unique.

Your assumption is not correct @grachte

Accounts and Payees are separate entities within the MMEX database.

You are therefore free to name (and later rename) accounts and payees as you choose, including with the same name.

Look at this example, which shows a payment from account A to payee B and the a transfer from account A to account B.

![same name](https://user-images.githubusercontent.com/4060092/148130362-90ba7886-e6d5-41ff-abf7-0ed53dd74c97.png)
 
 
I don't know where you are based, but here in the UK there is a bank called Lloyds and a pharmacy also called Lloyds. They are different entities.

In MMEX, I could therefore have an account name of Lloyds and a payee name of Lloyds to reflect the real world.

**Comment by whalley** [comment] 2022-01-05 00:26
> The workaround you describe here I understand completely that it's feasible, but it's the hard workaround not the soft workaround I am looking for.
> 
> Thanks for having this discussion with me! I have my viewpoints, you have yours based on how mmex has been developed I guess. I just want to be helpful to your project.
> 
> Best regards, Eric

@grachte Your views are always welcome, and I appreciate your contribution to the project. It has opened my eyes to the concerns that people are facing in migrating transactions to MMEX. I have raised the priority (at least in my mind) to reviewing how we can better support imports of data like this. 

I do hope you stick with it and use the (admittedly) cumbersome workarounds in getting your transactions sorted. Hopefully your explanations will help others with the same issues.

**Comment by whalley** [comment] 2022-01-05 00:29
https://github.com/moneymanagerex/moneymanagerex/issues/2648
https://github.com/moneymanagerex/moneymanagerex/issues/2610

**Comment by grachte** [comment] 2022-01-05 08:59
Ok I now better understand how MMEX treats accounts and payees separately, and why you are afraid to assume an account – payee relationship. 

•	In my mind an account is just a specialized payee with some extra properties (being it also an MMEX account with matching unique name). I would (enforce to) use a unique name for the account “Lloyds bank” and payee “Lloyds pharma”. When creating the MMEX account “Lloyds bank”, I would create a corresponding payee with the same (linked) unique name. But ok I understand this is a different approach of implementation that may not fit how it is designed right now.

My confusing of having an account – payee relationship comes from the fact that the MMEX transaction’s view, displays a payment to payee “B” and a transfer to account “> B” both in the same column “Payee”… Also in the Edit Transaction dialog, for a Deposit “From” means a ‘payee’, for a Transfer “From” means an ‘account’ and “To” means an ‘account’. Maybe better indicate what the from and to mean for the user, e.g; “From/To Payee” an “From/To Account”.

Don’t worry, I will stay with MMEX because I like the program and the possibility to create custom reports.

**Comment by tactilis** [comment] 2022-01-05 10:08
@grachte 
> I would create a corresponding payee with the same (linked) unique name. I understand this is a different approach of implementation that may not fit how it is designed right now.

I have not (yet) encountered any money management application that works the way that you are proposing. Accounts and Payees are distinct real world entities and are modelled as such in the application.

> My confusing of having an account – payee relationship comes from the fact that the MMEX transaction’s view, displays a payment to payee “B” and a transfer to account “> B” both in the same column “Payee"

_You_ are of course free to avoid any "B" and "> B" confusion by naming your accounts and payees differently.

I agree with @whalley that the right thing to do would be to improve the import capabilities so that transfers could be recognised. To make it useful and simple to use, it would need careful consideration of the different ways that transfers can be represented in CSV files exported from banks and other money management applications as it isn't always a case of just matching the payee name.

It's a considerable amount of work to get right and _may_ not be cost effective in terms of the amount of use it would get. Lots of analysis and design required first.

**Comment by grachte** [comment] 2022-01-05 11:08
I recognize your way of working is also a good thing, and maybe this is exactly the way how ALL other money manager apps are implemented. This doesn’t mean that you can be the first to deviate and think out of the box. I just give my view here… Take it or leave it, I just accept your decision.

Yes, CSV import improvement is the way to go, but here anyway you must find a way to match transaction, and I think that ONE of the primary keys would be here the “Payee” field in the CSV file that must match an MMEX account name… So, we have to accept an account – payee relationship at least during the import (and later on void the payee?).

To conclude, I learned a lot out of this chat and thanks @whalley for your most useful help.

**Comment by tactilis** [comment] 2022-01-05 11:32
@grachte 
> think out of the box

Thinking out of the box when only looking at one small aspect of the application's functionality is easy.
Considering all of the ramifications of a change and implementing it correctly throughout the application is not easy.

> I think that ONE of the primary keys would be here the “Payee” field in the CSV file that must match an MMEX account name

It's more complicated than this. I have encountered bank CSV files where transfers to another account are shown using a combination of an account number plus a string of characters that is different for each transaction.  I have no idea how widespread this is but the fact that I have seen it with more than one bank suggests that a simple payee/account name match would not be sufficient.

It's great that you have raised the need to deal with transfers more elegantly and have provoked this discussion. There is no quick easy fix though, so the workarounds that @whalley has suggested are the way to go at the moment.

**Comment by zer0feel** [comment] 2022-01-05 14:29
Hi all, it's great to see my post has led to so many discussion and testing, and see that I am not the only one facing the issue. @grachte has completely voiced out what I want about the transfer. Because I have regular transaction between accounts, I have to mark different transfer direction between accounts, the lacking of the batch transfer feature has stopped me from using MMEX but now I feel comfortable to use it again.

@whalley While implementing that during import may be complicated, may I suggest that, when multiple entries are selected and if there are values in the "withdraw" field ONLY, the transfer type is automatically identified as "transfer to", then the user have to select "to" which account the transfer is going. On the other hand, if there are values in the "deposit" field ONLY, the transfer type is automatically identified as "transfer from" and the user have to select "from" which account the transfer is done. When the multiple entries contain both withdraw and deposit, the transfer direction is ambigorous and the batch-transfer is not allowed, an error message can be displayed.

By the way, you guys have done a great job to response comment and update the program promptly, thank you.

**Comment by whalley** [comment] 2022-01-07 08:16
Closing. Any work on import reconciliation of deposit/transfers will be tracked against https://github.com/moneymanagerex/moneymanagerex/issues/2648 and https://github.com/moneymanagerex/moneymanagerex/issues/2610

**Closed by whalley** 2022-01-07 08:16 UTC
Labels: enhancement, fixed
