### ISSUE TITLE
import csv - german format

### ISSUE THREAD

**Issue by herrxyz** [moneymanagerex/moneymanagerex#1122] opened 2017-04-11 10:01 UTC
hey, there seems to be a problem with importing from csv if its in german format (like 10.000,00€) (switched , and . in comparison to english numbers)

- Check OS
  - [X] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [X] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by slodki** [comment] 2017-05-06 13:12
This problem is not related to german files, but all countries using different monetary format then set as default in mmex.

Polish [example attached](https://github.com/moneymanagerex/moneymanagerex/files/980936/example1.zip). Data entered into spreadsheet with default settings was exported to csv then imported into mmex without errors or warnings, but imported values are wrong.

After changing separator definitions in Currency Manager imported values are ok.
This error is duplicate of more general problem #1150.

I don't think importing wrong values from external files (bank statements, other tools exports) is a feature.

**Comment by vomikan** [comment] 2017-10-04 12:40
To import the exemple file attached just enought to set properly account currency
![screenshot 559](https://user-images.githubusercontent.com/6836805/31176105-52c17c40-a91a-11e7-86f1-f46dfa9d5a05.jpg)

**Comment by slodki** [comment] 2017-10-04 15:20
> [...] just enough to set properly account currency **before and after each import**

I use standard polish locale setting (set in system settings) for entering numbers in applications.
I have multiple bank statements to be imported:
- English Bank, euro account
- English Bank, dollar account
- German Bank, euro account
- German Bank, dollar account
- Polish Bank, euro account
- Polish Bank, złoty account

All banks use different locale settings in their files. **Number formatting is not currency attribute but country/territory attribute (aka locale).** There is no one number formatting used for EUR across Europe. Even the same currency and same language can use different number formatting in different geography regions.

Now it's required in MMEX to change currency settings for all currency used before each file import and after (to restore user settings).
And to change all used currencies settings to system compatible settings before using MMEX (I don't want to use different keys on my keyboard to enter amounts in different currencies - I always use the same key on numpad which enters different char then printed label on it).

This should be implemented as:
1. Using user locale system-wide settings for number formatting for all numbers (all currencies) in application GUI. We don't need separate settings for this - user configured this already.
2. Option to overwrite this settings for importing external data (from files/web) only - for all currencies used in import. Ability to remember this setting in *import profile* as additional feature.

**Comment by vomikan** [comment] 2017-10-04 15:43
IMHO locale setting is not best practice to use in that case because banks can use other locale.
But we can add pulldown menu to choose number fomat mask like: 
ddd,ddd.dd
ddd.ddd,dd
ddd ddd.dd
etc

**Comment by slodki** [comment] 2017-10-04 15:44
We can read user preferences for currency format using:
```c
wxString a = wxLocale::GetInfo(wxLOCALE_THOUSANDS_SEP, wxLOCALE_CAT_MONEY);
wxString b = wxLocale::GetInfo(wxLOCALE_DECIMAL_POINT, wxLOCALE_CAT_MONEY);
```

**Comment by slodki** [comment] 2017-10-04 15:56
@vomikan: but MMEX is used by the user not by banks! Bank preferences cannot have impact on how MMEX format currency amounts. This is interface (aka import in MMEX) task to convert binary/xml/json/text formats between applications.

Yes, user must know file format used (if number formatting is not part of the format spec). And select it in manual interface (during import). This should be the only place we ask user for formatting details, when we exchange data with external systems out of user control.

It doesn't make sense for me to store separate formatting for each currency, different from user preferred one. It doesn't help to use GUI (see #1150) nor import external data from multiple sources (this issue).

**Comment by maneuss** [comment] 2018-03-14 21:45
Hi,
i just downloaded MMEX 1.3.3 (MacOS X) and ran into this error as well. Screenshots are attached. Even when i select the correct delimiters in European Eur (comma as decimal point and point as group) positive values as 2.500,00 (and likewise all the rest are rejected.

At least for me this error persists or am i overlooking something?

With best regards Martin
![bildschirmfoto 2018-03-14 um 22 30 29](https://user-images.githubusercontent.com/10476501/37432598-3370bc32-27d9-11e8-8551-1a11189f33d8.png)
![bildschirmfoto 2018-03-14 um 22 30 55](https://user-images.githubusercontent.com/10476501/37432642-5130c58c-27d9-11e8-9d30-7eb496243543.png)

**Comment by slodki** [comment] 2018-03-27 21:47
Quick solution: add 2 options to CSV import dialog for group and decimal delimiter. Every file can have different formatting and user can adjust settings per imported file.

**Comment by giorgiobeggiora** [comment] 2018-03-28 13:09
...and possibly remove the localization settings from currency settings

**Comment by slodki** [comment] 2018-03-28 18:20
Yeh, this was my proposal: use one uniform format from system settings (aka locale) for all currencies. They will vary in prefix/postfix currency symbol, but number formatting will be the same.
Also GUI input controls should use system-defined settings (locale) - user keyboard already has already customized layout to use proper char at numeric keypad.

I don't want to wonder at every transaction what the appropriate separator for a given currency is...

**Comment by vomikan** [comment] 2019-01-30 07:37
I can't reproduce this issue (v1.4.0). My settings:
![image](https://user-images.githubusercontent.com/6836805/51965504-d0405d80-247a-11e9-823b-1694cbfe3b80.png)

![image](https://user-images.githubusercontent.com/6836805/51965533-e3ebc400-247a-11e9-9d22-54b4a1860b70.png)

![image](https://user-images.githubusercontent.com/6836805/51965552-f6fe9400-247a-11e9-8764-25a4e319bda6.png)

**Comment by slodki** [comment] 2019-02-03 14:43
A single file with a single currency can be manually imported:
1. change MMEX currency settings for currency imported to the notation used in file
2. import data from the file
3. restore user-preferred currency settings in MMEX

But this is not acceptable to import multiple files from different banks with multiple currencies - it's impossible user preferred notation is the same as used in all banks all over the world.

**Comment by slodki** [comment] 2019-02-03 23:43
https://forum.moneymanagerex.org/viewtopic.php?f=8&t=8030

**Comment by giorgiobeggiora** [comment] 2019-02-04 10:50
I think this should not be closed. We need to choose the locale when importing.

**Comment by vomikan** [comment] 2019-02-10 18:20
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.iceg200/icemask.htm

**Comment by vomikan** [comment] 2019-02-10 20:16
I suggest to add additional field for amounts with mask
![image](https://user-images.githubusercontent.com/6836805/52538939-bd3a6100-2d89-11e9-9a8b-e9da3d9baf2d.png)

**Comment by vomikan** [comment] 2019-02-11 13:21
mask | regexp
------|----------
wddd ddd,dd | -?((\d){1,3})+([ ][\d]{3})*([,](\d)*)?
wddd.ddd,dd | -?((\d){1,3})+([.][\d]{3})*([,](\d)*)?
wddd,ddd.dd | -?((\d){1,3})+([,][\d]{3})*([.](\d)*)?
wddd'ddd,dd | -?((\d){1,3})+(['][\d]{3})*([,](\d)*)?

**Comment by vomikan** [comment] 2019-02-13 12:31
I've just tested new feature.
User can manually select decimal charicter then start import. Working fine.

![image](https://user-images.githubusercontent.com/6836805/52711853-f3ebc380-2fa3-11e9-8d1e-727d9080f6fa.png)

Test amounts:
```
-0,01
0,00
1 110,00
$-300,02
```

**Comment by giorgiobeggiora** [comment] 2019-02-13 15:17
Does it try to autodetect the selected value?

**Comment by vomikan** [comment] 2019-02-13 15:24
>Does it try to autodetect the selected value?

Not yet. May be in future I'll add this feature.

**Comment by vomikan** [comment] 2019-02-13 15:28
But it's already good option. You don't need to change currency settings regarding csv file format for import data.
I'll add option to save settings to file. In that case users can share options for some banks.

**Closed** 2019-02-21 16:24 UTC
Labels: bug, i18n, import
