### ISSUE TITLE
Crashes when adding Stock Transaction

### ISSUE THREAD

**Issue by Kinifwyne** [moneymanagerex/moneymanagerex#1420] opened 2018-02-01 03:47 UTC
1. Create new database, then create investment account.
2. Create New stock.
3. Input following information
    - Share Number: .2286
    - Share Price: 179.55
4. Save
5. Following dialog appears:
```
Share account not found.
Would you want to create one?
```
6. Click `OK`
7. Dialog appears for creating share account, click `OK`.
8. Money Manager Ex crashes, generating attached file:
[One.zip](https://github.com/moneymanagerex/moneymanagerex/files/1684111/One.zip)

9. Reopen Money Manager Ex
10. Navigate to investment account.
11. Right click Stock, and then click `Add Stock Transaction`.
12. Money Manager Ex crashes, generating attached file:
[Two.zip](https://github.com/moneymanagerex/moneymanagerex/files/1684109/Two.zip)

Note that this stock in question is actually a mutual fund.

Your OS:
- [ ] Windows
- [ ] Mac OSX
- [X] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [X] 1.3.3-2
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

```
               +                OS: Arch Linux x86_64
               #                Hostname: zyrock
              ###               Kernel Release: 4.14.15-1-ARCH
             #####              Uptime: 1:16
             ######             WM: Openbox
            ; #####;            DE: None
           +##.#####            Packages: 742
          +##########           RAM: 1857 MB / 7876 MB
         #############;         Processor Type: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
        ###############+        $EDITOR: None
       #######   #######        Root: 11G / 219G (5%) (ext4)
     .######;     ;###;`".      
    .#######;     ;#####.       
    #########.   .########`     
   ######'           '######    
  ;####                 ####;   
  ##'                     '##   
 #'                         `#  
```

**Comment by slodki** [comment] 2018-03-22 22:35
@Kinifwyne Could you try my [today's build](https://github.com/slodki/moneymanagerex/releases/tag/test1) Arch pkg.tar.xz package? It should [install](https://travis-ci.org/slodki/moneymanagerex/jobs/356825827#L1667) without errors.

**Comment by Kinifwyne** [comment] 2018-03-30 21:13
No improvement with that build:
1. Create new database.
2. Create Investment Account.
3. Following dialog appears:
```
mmex Error
Unexpected character in Number token:
```
4. Click OK.
5. Double click "Share Accounts" in Navigation.
6. Program Crashes with following report:
[mmex_dbgrpt-15432-20180330T150836.zip](https://github.com/moneymanagerex/moneymanagerex/files/1864788/mmex_dbgrpt-15432-20180330T150836.zip)

**Comment by slodki** [comment] 2018-04-22 10:58
This is next problem (see #1473) with webkit library under Arch:
```
    <frame level="20" function="g_object_new" offset="0000009a"/>
    <frame level="21" function="webkit_web_view_new_with_context" offset="0000006c"/>
    <frame level="22" function="wxWebViewWebKit::Create(wxWindow*, int, wxString const&amp;, wxPoint const&amp;, wxSize const&amp;, long, wxString const&amp;)" offset="0000017e"/>
```
I think it should be fixed upstream by Arch team...

**Comment by slodki** [comment] 2018-05-06 06:56
for webView problem compare #1612

**Comment by feimosi** [comment] 2018-09-29 08:51
It's still crashing on Arch (for built-in reports), is there any workaround available?

**Comment by vomikan** [comment] 2020-05-20 17:06
Can't reproduce this issue on Ubuntu 20.04

```
Money Manager Ex
Version: 1.3.5-Beta.7
• Database version: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.1.3 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1)
• RapidJSON 1.1.0
• Lua 5.3.3
• libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Build on May 20 2020 19:47:41 with:
• CMake 3.16.3
• GNU Make 4.2.1
• gettext 0.19.8.1
• GCC 9.3.0 • Ubuntu 20.04 'focal'
Running on:
• Ubuntu 20.04 LTS "focal"
• Linux 5.4.0-29-generic x86_64
• English (U.S.) (UTF-8)
• 1280x979 24bit 96x96ppi 
```

**Closed by vomikan** 2020-05-20 17:06 UTC
Labels: bug, linux
