### ISSUE TITLE
Account View sort order is not "sticky"

### ISSUE THREAD

**Issue by Timp58** [moneymanagerex/moneymanagerex#1387] opened 2017-12-29 15:20 UTC
I prefer to have the sort order of my account view with the latest date at the bottom of the list rather than the top which appears to be the default behaviour.  I can change the order by clicking pink chevron icon at the top of the date column but this option does not persist when the program is closed and opened again. I am not sure if this is a bug or is by design but it is an annoyance that the chosen mode does not persist between sessions

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment] 2018-02-05 13:35
@Timp58 I can't reproduce this issue

**Comment by Timp58** [comment] 2018-02-05 15:51
I find this surprising.  The chosen sort order will always open with the latest date at the top of the table.  I can invert it during the session so newest date is at the bottom of the table but once the program is closed and opened again it will revert to the default behaviour.
It may be a long shot but I am storing my database on One Drive could that make any difference?

**Comment by slodki** [comment] 2018-02-05 16:33
I can confirm there is problem with sorting grid views - it depends on account type. More details later...

**Comment by whalley** [comment] 2021-08-12 22:24
This cannot be reproduced on the latest MMEX v1.5.5. Closing.

**Closed by whalley** 2021-08-12 22:24 UTC
Labels: enhancement, not-reproducible
