### ISSUE TITLE
Double counting todays entry in 'Daily Cash Flow' report.

### ISSUE THREAD

**Issue by jpweaving** [moneymanagerex/moneymanagerex#6697] opened 2024-04-30 09:35 UTC
After updating to Version: 1.8.0 64-bit, I found that after transferring £170.00 from my 'Saving for Bills' account to a current account, the 'Daily' 'Cash Flow' report for the 'Saving for Bills' account counted the £170.00 twice. The report took into account the new balance which was £123.81, but then deducted the £170.00 again as if it were a Scheduled Transaction for today. The £170.00 was a one-off transfer and had never been a Scheduled Transaction. When I changed the date of the £170.00 transfer to yesterdays date, the report behaved properly. I assume this bug has arisen as a result of changes you have made to stop Scheduled Transactions that are overdue, from being ignored by the Daily Cash Flow reports.
Thanks so much for the work that you do. MMEx makes my life so much easier. Time to make another contribution I think.

<hr> • Version: 1.8.0 64-bit<br>
 • Built: Apr 29 2024 08:08:39<br>
 • db 19 (aes128cbc)<br>
 • git 3325705 (2024-04-29)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.4 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/8.5.0-DEV Schannel<br>
 • gettext 0.21<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.29.1<br>
 • MSBuild 17.9.8.16306<br>
 • MSVS17.0<br>
 • MSVSC  19.39.33523.0<br>
 • Windows SDK 10.0.22621.0<br>
<br>
OS:<br>
 • Windows 11 (build 22631), 64-bit edition<br>
 • System Locale: <br>
 • User Interface Language: en_US.windows-1252<br>
 • 1920x1080 32-bit 96x96ppi

**Comment by colinarcher** [comment] 2024-05-31 07:08
I have the same issue, once I have entered todays sheduled transactions they are double counted in the daily cashflow report.


Money Manager Ex
• Version: 1.8.0 64-bit
• Built on: Apr 29 2024 08:08:39
• Database version: 19 (aes128cbc)
• Git commit: 3325705 (2024-04-29)
MMEX is using the following support products:
• wxWidgets 3.2.4 (wxMSW 10.0)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/8.5.0-DEV Schannel
• gettext 0.21
• apexcharts.js
Built with:
• CMake 3.29.1
• MSBuild 17.9.8.16306
• Microsoft Visual Studio 17.0
• Microsoft Visual C++ 19.39.33523.0
• Windows SDK 10.0.22621.0
Running on:
• Windows 10 (build 19045), 64-bit edition
• System Locale: 
• User Interface Language: en_GB.windows-1252
• 1920x1080 32-bit 96x96ppi

**Comment by n-stein** [comment] 2024-05-31 14:34
Duplicate of  #6745. This has been fixed. Can you please test the 1.8.1 beta to check if your issue is resolved?

**Comment by jpweaving** [comment] 2024-05-31 16:27
I can't find ' 1.8.1 beta'. Could you please send me a link?

**Comment by jpweaving** [comment] 2024-06-01 00:59
There is loads of links to all sorts of stuff that I don't understand but
nothing that looks like a download.

**Comment by n-stein** [comment] 2024-06-01 01:25
Odd, for some reason my link lost the build ID. Here is the correct link:

https://ci.appveyor.com/project/whalley/moneymanagerex/builds/49928925/job/vcxwtxccsgue4vi6/artifacts

**Comment by jpweaving** [comment] 2024-06-01 11:02
Thanks. I have tested reports with 1.8.1 beta, the original glitch has
gone. However, something that I thought was part of my original fault in
1.8.0, is still there. I recently noticed that reports on *some* accounts,
not all, were reporting the current balance as starting months ago. I
expected it to go away when the original problem with the reports was
fixed, but it hasn't (see attached PDF). This problem is only on reports
that include this particular account, all the other accounts work fine. So
something in that one account is causing reports to start from March. The
balance of £1035.60 is the correct current balance from 2024-05-29 but the
graph and the list view show 2024-03-19 for no reason that I can detect.
There are no transactions on or near 2024-03-19, I have tried temporarily
moving transactions either side of that date. I don't know if the start
date will stay at  2024-03-19 or change to  2024-03-20 tomorrow. I have
also tried renaming the account to fool the glitch. Changing the "Further
Month:" setting produces the correct end date of the report but the start
date is still historic. This problem is minor for me, so long as the start
date doesn't get fixed on 2024-03-19.

**Comment by n-stein** [comment] 2024-06-01 14:07
If you see historical balances on a cash flow report it is likely due to how your scheduled transactions are set up. I gave a brief summary of this here, maybe it applies

https://github.com/moneymanagerex/moneymanagerex/issues/6225#issuecomment-1890065945

**Closed** 2024-06-18 21:56 UTC
Labels: duplicate
