### ISSUE TITLE
Share update

### ISSUE THREAD

**Issue by swjpanton** [moneymanagerex/moneymanagerex#5921] opened 2023-05-16 14:54 UTC
hi I am getting no update for fund prices when clicking Tools/download rates.

When I go into a stock portfolio and click the circle i get error message saying Invalid cookie.

I have looked on forum and see this was an issue a couple weeks ago but can see no fixes as yet. Is this an error from yahoo or bug in the MMex system?

My operating details below
regards Simon Panton

MMEX version:
 Version: 1.6.3 64-bit
• Built on: Jan 31 2023 18:27:40
• Database version: 17 (aes128cbc)
• Git commit: 48d856292 (2023-01-31)
MMEX is using the following support products:
• wxWidgets 3.2.1 (wxMac 13.3)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.87.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0
• gettext 0.21.1
• apexcharts.js
Built with:
• CMake 3.24.2
• GNU Make 3.81
• Clang Apple LLVM 14.0.0 (clang-1400.0.29.202)
Running on:
• macOS Ventura Version 13.3.1 (a) (Build 22E772610a)
• English (United Kingdom) (Western (Mac OS Roman))
• 2048x1152 32bit 144x144ppi

**Comment by tactilis** [comment] 2023-05-16 15:08
This report appears to be a duplicate of https://github.com/moneymanagerex/moneymanagerex/issues/5890

**Comment by n-stein** [comment] 2023-05-16 15:16
See also #5894

**Closed** 2023-05-16 17:04 UTC
Labels: duplicate
