### ISSUE TITLE
add credit limit (overdraft) for cheking and savings accounts

### ISSUE THREAD

**Issue by gtrioullier** [moneymanagerex/moneymanagerex#1444] opened 2018-02-20 19:53 UTC
Your OS:
- [ ] Windows
- [ ] Mac OSX
- [ ] Linux 
- [x] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [ ] 1.3.x
- [x] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment] 2018-03-22 12:32
Something like this already there:
![image](https://user-images.githubusercontent.com/6836805/37770659-2df777e2-2de6-11e8-81ff-a72ea623c751.png)

**Comment by slodki** [comment] 2018-05-01 10:45
I think this is duplicate of #1298 and we don't need separate issue

**Closed by slodki** 2018-05-01 10:45 UTC
Labels: needs more info
