### ISSUE TITLE
New release 1.8 - account line characters are no longer visible

### ISSUE THREAD

**Issue by Alouette44** [moneymanagerex/moneymanagerex#6709] opened 2024-05-01 06:58 UTC
MMEX version:
 - [ ] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [x ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

**With the new version 1.8.0 account line characters are no longer visible.**

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction
![Capture](https://github.com/moneymanagerex/moneymanagerex/assets/155957418/8157ec07-692d-41e8-91aa-aa097ee25da4)

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment] 2024-05-01 22:01
I can't reproduce this on MacOS. What theme is being used?

**Comment by vomikan** [comment] 2024-05-04 12:17
I can't reproduce on Win
![image](https://github.com/moneymanagerex/moneymanagerex/assets/6836805/53a60c2d-1b70-44ae-8071-f75c6186419c)

**Comment by PaulBP14** [comment] 2024-07-01 08:12
Is this referring to the bottom line of transaction screens? It is a small point but could do with being fixed.

![image](https://github.com/moneymanagerex/moneymanagerex/assets/45141401/54413050-812f-4cf1-962c-c30c8cdaace4)

(this is scrolled down as far as it can be)

**Comment by whalley** [comment] 2024-08-13 19:00
Closing as no further information supplied by originator.

**Closed** 2024-08-13 19:01 UTC
Labels: bug, needs more info
