### ISSUE TITLE
Excessive CPU usage while displaying certain reports

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#3029] opened 2021-03-08 17:55 UTC
MMEX version:
 - [x] 1.3.7 beta 6 

Bug exists in development code: 1.3.7 beta 6 - built 08/Mar/2021

Operating System:
 - [x] Windows
 - [ ] Mac OSX   Not tested
 - [ ] Linux     Not tested

# Description of the bug

Excessive CPU (sometimes >30%) is used continuously by MMEX when certain reports are displayed.

This happens:
a. Even though the report display is static (i.e. no mouse interaction with charts)
b. When the MMEX window is in the foreground or in the background/minimized. 

This bug _appears_ to be related to the display of reports with pie charts - but not those having bar charts. NB. I've not exhaustively checked this but see the steps to reproduce below where I display both chart types.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 
Reproduction steps:

See the CPU usage graph - the numbers on the graph correspond to the steps below:

![MMEX CPU usage](https://user-images.githubusercontent.com/4060092/110359229-2823f800-8035-11eb-8757-457dbf290102.png)

1. Display a checking account.
   Note the low CPU usage.

2. Display the 'Where the Money Goes' report (screenshot '2' attached).
   Note the continuous _high_ CPU usage after the initial report generation spike.
   
3. Display a checking account.
   Note the low CPU usage.
   
4. Display the 'Where the Money Comes From' report (screenshot '4' attached).
   Note the continuous _high_ CPU usage (lower than at step 2 but still too high) after the initial report generation spike.
   
5. Display a checking account.
   Note the low CPU usage.
   
6. (and 7). Display the 'Income vs Expenses Monthly' report (screenshot '6' attached).
   Note the low CPU usage after the initial report generation spike.

Expected result:

1. After the initial generation of a report, CPU usage should not stay high.

2. MMEX should not consume CPU when it is in the background/minimized.

Actual result:

Continuous high CPU usage when some reports (possibly only those having pie charts) are displayed.

# Additional information

This bug may be in the chart library, or it may just be a result of the way MMEX is using it.

The higher CPU usage when the 'Where the Money Goes' report is displayed compared to 'Where the Money Comes From' _may_ be because the pie has a larger number of slices (NB speculation. Not tested)

![MMEX Where The Money Goes](https://user-images.githubusercontent.com/4060092/110359570-8c46bc00-8035-11eb-9b2a-3c11ded01c4d.png)

![MMEX Where The Money Comes From](https://user-images.githubusercontent.com/4060092/110359662-aa142100-8035-11eb-8ace-46e5b2143abd.png)

![MMEX Income vs Expenses](https://user-images.githubusercontent.com/4060092/110359685-b13b2f00-8035-11eb-8539-48ca6d6173a1.png)

**Comment by vomikan** [comment] 2021-03-08 18:08
I can't reproduce this.
Could you try to disable "Send anonymous statistics usage data" ?

**Comment by tactilis** [comment] 2021-03-08 18:39
1. Turned off "Send anonymous statistics usage data".
2. Repeated steps 1-7 in initial issue above. Behaviour here is still as reported.

3. Exited MMEX.
4. Restarted MMEX.
5. Repeated steps 1-7 in initial issue above. Behaviour here is still as reported.

6. Displayed each of the reports in turn.
 - All of those with pie charts (including 'My Usage') have continuous high CPU usage.
 - Bar charts and transaction reports have low CPU usage.

**Comment by vomikan** [comment] 2021-03-08 18:48
I suggest the following test.
1) Right click on Usage report.
2) View source code of html
![image](https://user-images.githubusercontent.com/6836805/110366328-2ec36700-8057-11eb-979b-9f96710bcb68.png)
3) save it to test.html file
4) replace memory: to emptuy string in the whole test.html file
5) copy master.css, apexcharts.min.js, sorttable.js (polyfill.min.js, classlist.min.js, findindex.min.js, umd.min.js) files from ....\mmex\res folder.
6) open test.html file in Iexplore

![image](https://user-images.githubusercontent.com/6836805/110366846-e8223c80-8057-11eb-89a2-9b4036f81b03.png)

[test.zip](https://github.com/moneymanagerex/moneymanagerex/files/6103483/test.zip)

**Comment by whalley** [comment] 2021-03-08 20:16
I can't reproduce on MacOS either.

**Comment by tactilis** [comment] 2021-03-08 20:37
> I suggest the following test.

Performed the test as specified, except that I used Firefox.

![image](https://user-images.githubusercontent.com/4060092/110377953-ebfc9180-804c-11eb-9134-7e1767311486.png)

1. Opened test.html in Firefox
2. Displayed the page for a while (7% CPU - same as background level)
3. Switched MMEX from showing a checking account to the My Usage report
4. Displayed the page for a while (19-20% CPU)

**Comment by tactilis** [comment] 2021-03-08 20:46
Happy to do whatever testing you can think of to help to nail it

**Comment by vomikan** [comment] 2021-03-08 20:54
Mmex use Internet Explorer to render reports.
How many CPU usage if test.html opend in Iexplore?

**Comment by tactilis** [comment] 2021-03-08 22:08
> Mmex use Internet Explorer to render reports.

Ah, I see.

![image](https://user-images.githubusercontent.com/4060092/110386805-acd43d80-8058-11eb-9347-89ef99d306d7.png)

1. IE open and displaying a blank page.
2. Opened test.html in IE.
3. Minimized IE.
4. Restored IE.

So:
a. the CPU usage with the 'My Usage' report rendered in Internet Explorer is similar to when it is rendered in MMEX; i.e. high compared to rendering in Firefox (or Chrome).

b. The CPU usage drops (stops?) when IE is minimized but does not when MMEX is minimized.

**Comment by grumpy235** [comment] 2021-03-09 08:25
Just to add what I have discovered using a fully patched win10 and MMEX Master source at commit aa86a590
1. Sitting on Home Page uses effectively no cpu
2. Displaying usage frequency for current month gives the first attachment, i.e a small amount of cpu is continuously used.
3. Hide the chart and that small amount of cpu disappears.
4. Display a pie chart with much more data and mmex cpu usage increases again running under the IE process - attachment 2 again hiding the chart and cpu usage drops to zero.
5. Not done much with bar charts but it would appear that mmex under IE process uses next to no cpu

Looks to me like pie charts in apexcharts is the culprit ? Perhaps continually refreshing the display ?

![Capture](https://user-images.githubusercontent.com/24897056/110440652-cc975000-80b0-11eb-8476-261fcadc9354.PNG)


![Capture1](https://user-images.githubusercontent.com/24897056/110438956-c7d19c80-80ae-11eb-85cd-55e98abb2665.PNG)

**Comment by vomikan** [comment] 2021-03-09 08:50
> Looks to me like pie charts in apexcharts is the culprit ? Perhaps continually refreshing the display ?

I think so.

**Comment by whalley** [comment] 2021-03-09 09:07
Best next step then is to raise an issue here: https://github.com/apexcharts/apexcharts.js/issues with a set of HTML that can be used to demonstrate the issue. That team would be better placed to investigate further.

**Comment by grumpy235** [comment] 2021-03-10 12:23
Having tried a few things, now I am not so sure if this is an apexcharts issue _**or if it is an issue at all**_ as the cpu usage I am seeing is small on an i7-8750H

The attached is a snap shot of a minimised IE displaying Nikolay's test from yesterday i.e. the html run from a file and at the same time a minimised mmex displaying a Usage report. IE shows no cpu usage whilst mmex shows varied cpu values always less than 1 and working set size is also bouncing around. This usage drops to zero when the chart part is switched off.
![Capture4](https://user-images.githubusercontent.com/24897056/110625726-b3b59a00-8197-11eb-8912-e8d4cfbe9f3e.PNG)

Just for my own interest when I find some time I'll run a debug session to try and pin-point where cpu is being consumed - might be wxWidgets related?

Already done some digging in the wxWidgets source code and with my limited understanding, it looks like under Windows then wxLaunchDefaultBrowser uses an "old" Registry key that always resolves to IE even though Firefox/Chrome/Opera etc. may be set as the default browser - defined in a different key on a per user basis.

**Comment by tactilis** [comment] 2021-03-10 14:28
> [grumpy235] the cpu usage I am seeing is small

It's strange that the high CPU usage for pie chart reports affects some people (i.e. me, so far) and not others.
It's 100% repeatable here as initially reported.

NB, I'm running Windows 7 SP1 on an i7-3520M at 2.9GHz with plenty of free memory.

> [grumpy235] Just for my own interest when I find some time I'll run a debug session to try and pin-point where cpu is being consumed - might be wxWidgets related?

If there is anything I can do to assist with that here, please do let me know.

**Comment by vomikan** [comment] 2021-03-10 14:46
In case if I is quickly moving the cursor over the graph

![image](https://user-images.githubusercontent.com/6836805/110646934-75849e80-81c8-11eb-9ac4-0370159d1437.png)


Version: 1.3.7-Beta.7 64-bit
• Build: Mar 9 2021 22:10:41
• db 7 • (aes128cbc)

Libs:
• wxWidgets 3.1.4 (wxMSW 10.0)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.3.5
• lunasvg
• libcurl/7.61.0-DEV WinSSL
• gettext 0.19.8.1
• apexcharts.js

Build using:
• CMake 3.16.2
• MSBuild 15.9.21.664
• MSVS15.0
• MSVSC 19.16.27035.0
• Windows SDK 10.0.14393.0

OS:
• Windows 10 (build 19042), 64-bit edition
• Russian (windows-1251)
• 2752x1152 32bit 96x96ppi

**Comment by whalley** [comment] 2021-03-10 14:49
Yes, that I can understand as it will react to mouse position/hover to process and display things like tool tips.

**Comment by grumpy235** [comment] 2021-03-10 15:15
@tactilis
Your unique position is I guess Windows 7, I'm assuming @vomikan is using Win 10 and @whalley is using either or both Win 10/Mac.
I certainly do not see anything like you and in fact my cpu usage is trivial compared to yours and probably a red-herring

**Comment by tactilis** [comment] 2021-03-12 22:49
> Your unique position is I guess Windows 7, I'm assuming @vomikan is using Win 10 and @whalley is using either or both Win 10/Mac.

I will soon be able to test this on a Win 10 PC and on another Win 7 PC.  I'll report my findings.

In the meantime, having left MMEX running in the background on my Win 7 PC, this dialog eventually appeared:

![image](https://user-images.githubusercontent.com/4060092/111006478-c5a86000-8384-11eb-850f-6d43ed3cb3cb.png)

While the dialog was displayed, the CPU usage dropped to a low background level. Presumably the running of the script is stopped pending the user responding.

**Comment by tactilis** [comment] 2021-03-15 10:57
@grumpy235
> Your unique position is I guess Windows 7

That turns out not to be the case.

I've now re-run the CPU usage test on a Windows 10 PC using the same 1.3.7 beta version of MMEX and the same .mmb

I get the similar results on Windows 10 as on my Windows 7 PC, i.e. continuous high CPU usage when displaying the Where the Money Goes chart shown in my original post.

![image](https://user-images.githubusercontent.com/4060092/111140843-b7239980-857a-11eb-81de-a120b75ea4d2.png)

1. Display a checking account
2. Display Where the Money Goes chart
3. Display a checking account
4. Display Where the Money Goes chart
5. Minimize MMEX window
6. Restore MMEX window and display checking account

It's pretty clear that the level of CPU usage is related to the complexity of the pie chart:

a) High CPU - Where the Money Goes: 46 category slices
b) Medium CPU: Where the Money Comes From: 8 category slices
c) Low CPU: My Usage: 1 report slice (when I first ran it on Windows 10)

**Comment by grumpy235** [comment] 2021-03-15 12:58
@tactilis 
In that case I'm stumped - I am sorry I do not have the necessary technical skills to take this any further, perhaps @vomikan or @whalley can as they are the main developers.
This modern stuff is a steep learning curve for me, too many years working with old fashioned stuff like COBOL and assembler on mainframes! 
I have just run a report with 50+ slices and I see a 2.5% cpu usage for mmex which disappears when I hide the chart so something odd is happening.
As vomikan agreed earlier, it looks like Apexcharts is the "culprit" and getting that looked at/fixed might take some time as they appear to have a back log of issues and like a lot of projects which rely on volunteers limited people to look into issues.
Your only option as far as I can see at the moment, if the cpu usage really is a problem to you, is to "hide" the chart.

**Comment by tactilis** [comment] 2021-03-15 13:14
To help others try to reproduce this CPU usage issue, I have created an .xlsx file, which I save as .csv for Importing into a checking account.

The .csv contains:

  10 deposits, each with a different category
100 withdrawals, each with a different category

I see continuous high CPU usage on the left chart, and lower (but still high) on the right.

![image](https://user-images.githubusercontent.com/4060092/111157360-b563d100-858e-11eb-9413-dd5118f0d6a2.png)

The .xlsx file is attached. Save it as a .csv (GitHub won't let me attach the .csv directly)

The Import settings are:

![image](https://user-images.githubusercontent.com/4060092/111157575-f0fe9b00-858e-11eb-9440-7d6d7ed66f4e.png)

[Test data.xlsx](https://github.com/moneymanagerex/moneymanagerex/files/6141544/Test.data.xlsx)

Do you get similar results to me now?

Could this data now be used to create the HTML to raise an issue with apexcharts (assuming MMEX it is not using the chart library incorrectly)?

**Comment by vomikan** [comment] 2021-03-15 13:59
It's not a problem for strong CPU

![image](https://user-images.githubusercontent.com/6836805/111164969-96296b80-85af-11eb-8ba4-41490cfea766.png)

[CPU_test.zip](https://github.com/moneymanagerex/moneymanagerex/files/6141841/CPU_test.zip)

**Comment by vomikan** [comment] 2021-03-15 15:27
CPU usage for Where the Money Goes report is high on weak CPU.

![image](https://user-images.githubusercontent.com/6836805/111177344-2e791d80-85bb-11eb-8001-81bf4cca6a7b.png)

In any case, this is not a bug, but simply the consumption of CPU time for the maintenance of this diagram.
If optimization is possible, then within the project apexcharts.
 https://github.com/apexcharts/apexcharts.js/issues

**Comment by whalley** [comment] 2022-04-19 18:09
No planned changes for this, so closing.

**Closed by whalley** 2022-04-19 18:09 UTC
Labels: bug, wontfix
