### ISSUE TITLE
saisie montant MMEX  1.5.16 64 bit Jammy

### ISSUE THREAD

**Issue by pivantable** [moneymanagerex/moneymanagerex#4724] opened 2022-06-27 08:42 UTC
MMEX version:
 - [x] 1.5.16 64 bit
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x ] Linux UBUNTU

# Description of the bug

Please describe your issue with details.
Add screenshot or other files if needed.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

ASSERT INFO:
../src/unix/utilsx11.cpp(2631): assert ""Assert failure"" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used

BACKTRACE:
[1] wxGetKeyState(wxKeyCode)
[2] mmCalcValidator::OnChar(wxKeyEvent&)
[3] mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
[4] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[5] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[6] wxEvtHandler::TryHereOnly(wxEvent&)
[7] wxEvtHandler::ProcessEventLocally(wxEvent&)
[8] wxWindowBase::TryBefore(wxEvent&)
[9] wxEvtHandler::ProcessEventLocally(wxEvent&)
[10] wxEvtHandler::ProcessEvent(wxEvent&)
[11] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[12] wxWindow::GTKDoInsertTextFromIM(char const*)
[13] g_closure_invoke
[14] g_signal_emit_valist
[15] g_signal_emit_by_name
[16] g_cclosure_marshal_VOID__STRINGv
[17] g_signal_emit_valist
[18] g_signal_emit_by_name
[19] g_cclosure_marshal_VOID__STRINGv
[20] g_signal_emit_valist
[21] g_signal_emit_by_name
[22] g_closure_invoke
[23] g_signal_emit_valist
[24] g_signal_emit
[25] gtk_window_propagate_key_event
[26] g_closure_invoke
[27] g_signal_emit_valist
[28] g_signal_emit
[29] gtk_main_do_event
[30] g_main_context_dispatch
[31] g_main_loop_run
[32] gtk_main
[33] wxGUIEventLoop::DoRun()
[34] wxEventLoopBase::Run()
[35] wxDialog::ShowModal()
[36] TransactionListCtrl::OnEditTransaction(wxCommandEvent&)
[37] mmGUIApp::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&), wxEvent&) const
[38] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[39] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*)
[40] wxEvtHandler::TryHereOnly(wxEvent&)
[41] wxEvtHandler::ProcessEventLocally(wxEvent&)
[42] wxEvtHandler::ProcessEvent(wxEvent&)
[43] wxEvtHandler::ProcessPendingEvents()
[44] wxAppConsoleBase::ProcessPendingEvents()
[45] wxApp::DoIdle()
[46] g_main_context_dispatch
[47] g_main_loop_run
[48] gtk_main
[49] wxGUIEventLoop::DoRun()
[50] wxEventLoopBase::Run()
[51] wxAppConsoleBase::MainLoop()
[52] wxEntry(int&, wchar_t**)
[53] main
[54] __libc_start_main
[55] _start
…

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment] 2022-06-29 09:55
A similar problem is described here. There doesn't seem to be a solution.

https://raywoodcockslatest.wordpress.com/2021/11/05/veracrypt-wxgetkeystategtk/

**Comment by whalley** [comment] 2022-06-30 08:30
Previously reported here: https://github.com/moneymanagerex/moneymanagerex/issues/2279

**Comment by PMaff** [comment] 2022-07-01 19:41
@pivantable can you describe the exact steps that lead you to that bug?
What does the "About" dialog of mmex show, can you copy that here or make a screenshot?

**Comment by PMaff** [comment] 2022-07-02 21:23
> Previously reported here: #2279

I tried to reproduce this with the Opensuse Tumbleweed version of 1.5.16 by typing in a number in
a newly created account window "Konto bearbeiten" == "Edit Account" but there was no assertion or alike.

**Comment by Eduardo3382** [comment] 2022-07-04 18:58
In my case when I tried to enter an amount for any transaction, after press enter a message came up saying 
ASSERT INFO:
../src/unix/utilsx11.cpp(2631): assert ""Assert failure"" failed in wxGetKeyStateGTK(): Unsupported key, only modifiers can be used. For more detail see:https://forum.moneymanagerex.org/viewtopic.php?t=10625

**Comment by PMaff** [comment] 2022-07-08 17:39
What happens if you install wxWidget 3.1.5 before that?
Do you have the prerequisites as described here:
https://github.com/moneymanagerex/moneymanagerex/blob/master/BUILD.md#linux
?
See "List of required packages for each distribution is available in dockerfiles..."

My assumption is that you have installed one of the libraries with some other version.

**Comment by PMaff** [comment] 2022-07-08 17:53
Do you use Wayland?
I found this one:
https://github.com/wxWidgets/wxWidgets/pull/320
therefore I am asking.

**Comment by Eduardo3382** [comment] 2022-07-09 13:54
> 

Hi 
Right Ubuntu 22.04 use Wayland as default. In this case, is any way to use MMEx 1.5.16?

**Comment by PMaff** [comment] 2022-07-20 14:05
> > 
> 
> Hi Right Ubuntu 22.04 use Wayland as default. In this case, is any way to use MMEx 1.5.16?

Ok, since I made this for XUbuntu 22.04 this might be the error.
@whalley : I do not know, if you want to rename the Ubuntu 22.04 version of 1.5.16 to
something with "...X11..." or do this for 1.5.17 only?

But there is also a compile error currenty in mmex 1.5.17 so I will wait to check:
https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1190324939

I will try with Wayland in 22.04 later.

**Comment by PMaff** [comment] 2022-07-23 23:08
I've installed a 22.04 with Wayland on a Virtual Machine.
After compiling wxWidget 3.2  the webview sample does not work.
Maybe there is a problem:
`** (webview:76811): WARNING **: 00:47:02.808: GDK is not able to create a GL context, falling back to glReadPixels (slow!): Unable to create a GL context`
Looks like something like this:
https://gitlab.gnome.org/GNOME/gtk/-/issues/2619

**Comment by Eduardo3382** [comment] 2022-07-24 14:06
> I've installed a 22.04 on a Virtual Machine. At first I think Wayland was not set. 
I have confirmed my Ubuntu 22.04 use Wayland as default, I will change to x11 to check if this is the problem still in place using this x11.

> Eduardo3382 are you using nVidia drivers? (for some reason I cannot select your github username with '@' ).
Not I am not using a nVidia drivers

But my question based on my limited knowledge about technology is why does MMEx v 1.5.14 working well on Ubuntu 22.04 but v 1.5.16 does not work properly in the same OS? Checking MMEx about differences only there is a change in lunsvg library but not in wxWidget.

Difference:
- lunsvg v 2.0.1 in current MMEx instead of 2.3.1 in MMEx v 1.5.16.

Is there a linux version 1.5.17 in anywhere for checking with wayland and/or x11?

**Comment by PMaff** [comment] 2022-07-26 19:27
> > I've installed a 22.04 on a Virtual Machine. At first I think Wayland was not set.
> > I have confirmed my Ubuntu 22.04 use Wayland as default, I will change to x11 to check if this is the problem still in place using this x11.
> 
> > Eduardo3382 are you using nVidia drivers? (for some reason I cannot select your github username with '@' ).
> > Not I am not using a nVidia drivers
> 
> But my question based on my limited knowledge about technology is why does MMEx v 1.5.14 working well on Ubuntu 22.04 but v 1.5.16 does not work properly in the same OS? Checking MMEx about differences only there is a change in lunsvg library but not in wxWidget.
> 
> Difference:
> 
>     * lunsvg v 2.0.1 in current MMEx instead of 2.3.1 in MMEx v 1.5.16.
> 
> 
> Is there a linux version 1.5.17 in anywhere for checking with wayland and/or x11?

In https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1166317245 I see that 1.5.16 has wxWidget  3.1.5 whereas 1.5.14 has wxWidgets 3.1.6 so maybe the error is there?
Afair the 1.5.14 was also compiled for X11 and not for Wayland so I wonder, why this is working for you.

What does
`echo $XDG_SESSION_TYPE`
say if you type that at command line?

The 1.5.17 has some compile errors under Linux: https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1190324939
and since this is released, the code will not be changed.

Would you be willing to try a 1.5.18 Beta?

**Comment by Eduardo3382** [comment] 2022-07-26 22:44
Hi
> What does `echo $XDG_SESSION_TYPE` say if you type that at command line?
> 

CLI shows "wayland"


> Would you be willing to try a 1.5.18 Beta?

Sure, but where can I get the 1.5.18 Beta deb file to test?

**Comment by PMaff** [comment] 2022-08-02 15:37
> Hi
> 
> > What does `echo $XDG_SESSION_TYPE` say if you type that at command line?
> 
> CLI shows "wayland"
> 
> > Would you be willing to try a 1.5.18 Beta?
> 
> Sure, but where can I get the 1.5.18 Beta deb file to test?

Ok so it is really Wayland.
Beta: I would place Betas here:
https://onedrive.live.com/?authkey=%21AE%2DkxNeZZqW45a4&id=A0FB83D788D2D744%21105301&cid=A0FB83D788D2D744

But: I was able to reproduce your problem with Ubuntu 22.04 Jammy, Wayland and wxWidget 3.2.0:
```
Money Manager Ex
Version: 1.5.19-Beta.1 64-bit
 Build on Aug 2 2022 17:01:57
 Database version: 7  (aes128cbc)
 Git commit: 2b26c214e (2022-08-02)
 Git branch: master
MMEX is using the following support products:
 wxWidgets 3.2.0 (wxGTK 3.24)
 wxSQLite3 4.6.0 (SQLite 3.31.1)
 RapidJSON 1.1.0
 Lua 5.3.6
 lunasvg v2.3.1
 libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.12
 gettext 0.21
 apexcharts.js
Build using:
 CMake 3.22.1
 GNU Make 4.3
 GCC 11.2.0  Ubuntu 22.04 'jammy'
Running on:
 Ubuntu 22.04.1 LTS "jammy"
 Linux 5.15.0-43-generic x86_64
 GNOME English (United States) (UTF-8)
 0x0 0bit 96x96ppi
```

I was testing:
`[...]/moneymanagerex/build$ ../_CPack_Packages/Linux/DEB/mmex-1.5.19-Beta.1-Linux/usr/bin/mmex`
and
`[...]/moneymanagerex/build$ WEBKIT_DISABLE_COMPOSITING_MODE=1 ../_CPack_Packages/Linux/DEB/mmex-1.5.19-Beta.1-Linux/usr/bin/mmex`

I get the same assertions, see screenshots.
Also one cannot move the mmex windows (e.g. transaction window) on such a Wayland-Jammy.
I have to recheck this with the X11 version on Ubuntu (recompiling wxWidget and mmex).

So @whalley @vomikan  we do have a problem with Jammy + Wayland + wxWidget 3.2.0 and the current mmex.
:-(

![mmexcrashassertion](https://user-images.githubusercontent.com/93879362/182414104-1c8f3f85-3f1e-4e71-8c13-f0f85a9ea1c5.jpg)

**Comment by Eduardo3382** [comment] 2022-08-02 18:11
Hi @PMaff 
Thanks again for checking it.

> But: I was able to reproduce your problem with Ubuntu 22.04 Jammy, Wayland and wxWidget 3.2.0:

Assuming the problem came out when MMEX changed the library wxWidget 3.2.0.
The MMEX version MMEx 1.5.15 is working without any issue with Ubuntu 22.04 and Wayland, but was the last version using wxWidget 3.1.5, right? And pending to know what is the behavior using Ubuntu 22.04 + x11 +  MMEx 1.5.19 beta (with wxWidget 3.2.0), right?

**Comment by whalley** [comment] 2022-08-02 18:56
> For myself, I still use wxWidgets 3.1.7 (wxMSW 10.0).
> 
> Make a downgrade and don't suffer.

Think you are right, I'll drop the linux CI builds down to 3.1.7.

**Comment by Eduardo3382** [comment] 2022-08-02 19:50
> Think you are right, I'll drop the linux CI builds down to 3.1.7.

Can somebody share with me the deb file with new MMEx version with wxWidgets 3.1.7 or make it available in the any place for being able to upgrade my MMEx, if it would be possible?  Thanks

**Comment by whalley** [comment] 2022-08-02 20:04
Will be available later.... Will add link here.

**Comment by PMaff** [comment] 2022-08-02 20:33
> And pending to know what is the behavior using Ubuntu 22.04 + x11 + MMEx 1.5.19 beta (with wxWidget 3.2.0), right?

Right.
That will be the next step.
Hopefully it is all only a matter of Wayland.

**Comment by whalley** [comment] 2022-08-02 22:52
Latest CI builds (against wx3.1.7) here...
https://app.circleci.com/pipelines/github/whalley/moneymanagerex/24/workflows/e51508ef-6142-4aed-bf07-e22b37614395/jobs/28/artifacts

**Comment by whalley** [comment] 2022-08-02 23:28
> We should delete the sentence "If you have issues with the Ubuntu builds then review the advice [here](https://github.com/moneymanagerex/moneymanagerex/issues/4154#issuecomment-1106597921)" here: https://moneymanagerex.org/docs/downloads/latest/ since i18n is not there anymore (thanks @whalley ).

Done.

**Comment by Eduardo3382** [comment] 2022-08-03 00:05
@whalley  & @PMaff 
Thank you very much, I have installed mmex_1.5.19-Beta.1-1~jammy_amd64.deb and confirming it is working without any problem. 
![Screenshot MMEx 1 5 19beta](https://user-images.githubusercontent.com/39868347/182496978-0e3c918a-e27a-4612-b57f-980a9348221e.png)

**Comment by whalley** [comment] 2022-08-03 09:16
Can we close this now and track the wx3.2.0/Wayland issue against https://github.com/moneymanagerex/moneymanagerex/issues/4895

**Comment by vomikan** [comment] 2022-08-03 12:38
![image](https://user-images.githubusercontent.com/6836805/182609713-59499f4f-7bac-4cd2-ab63-df08f8a9bc38.png)

**Closed by vomikan** 2022-08-03 12:38 UTC
Labels: bug, help wanted, linux
