### ISSUE TITLE
Split Category Transactions Do Not Appear on Transaction Report

### ISSUE THREAD

**Issue by steveknott** [moneymanagerex/moneymanagerex#5033] opened 2022-09-02 18:27 UTC
When a transaction has split categories - it no longer appears on the transaction report, even when no transactions are selected.

e.g. Just selecting a date range does not result in split transactions getting reported.

**Comment by tactilis** [comment] 2022-09-02 19:27
Confirmed as a bug in 1.5.20.

Top report: Account with a single £100 withdrawal transaction categorised as Food.

Bottom report: Same transaction changed to a split of Food £75 and Healthcare £25
 
![image](https://user-images.githubusercontent.com/4060092/188223168-16f2b2e8-5c8e-4836-96eb-2ce96351442a.png)

**Comment by whalley** [comment] 2022-09-02 19:39
Was buggy in v1.5.19 also, last working version seems to be 1.5.18.

**Comment by whalley** [comment] 2022-09-02 19:45
@steveknott As a workaround specify `.*` as the category. This should use a regular expression to match all categories

**Comment by tactilis** [comment] 2022-09-02 19:46
> As a workaround specify .* as the category

Nice solution

**Comment by steveknott** [comment] 2022-09-02 19:59
Thanks, that works!!!!

In fact better than or previously, which while it reported the transaction, would put all transactions on one line.  This workaround outputs multiple lines

⁣Get BlueMail for Android ​

On 2 Sept 2022, 20:46, at 20:46, Martin ***@***.***> wrote:
>> As a workaround specify .* as the category
>
>Nice solution
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/moneymanagerex/moneymanagerex/issues/5033#issuecomment-1235843577
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by tactilis** [comment] 2022-09-02 21:20
> In fact better than or previously, which while it reported the transaction, would put all transactions on one line.  This workaround outputs multiple lines

It's not the '.*' workaround that is _producing_ the display of multiple lines.

It's other changes to the code that have enabled that, however there is a bug that prevents split transactions actually being included in the report. 

The .* filter ensures that they are.

It will be fixed in the 1.5.21 release and the workaround will no longer needed.

**Comment by tactilis** [comment] 2022-09-03 18:17
Tested 1.5.21-Beta.1  commit: 8dece5e (2022-09-03)

Confirmed fixed.

**Closed** 2022-09-04 12:03 UTC
Labels: bug, fixed
