### ISSUE TITLE
Add Custom Fields to Recurring Transactions

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4159] opened 2022-02-01 18:43 UTC
# Description of the feature

Custom Fields can be defined and added **manually** to transactions within a regular account (i.e. bank, credit card, cash, asset, loan, term account).

In MMEX 1.5.x it is not currently possible to add Custom Fields to a Recurring Transaction.

This feature request is to **provide the capability to add Custom Fields to Recurring Transactions** so that, when each single transaction is automatically generated on the appropriate date, the generated transaction inherits the Custom Fields that have been set in the parent Recurring Transaction.

# Use case

In #4144, @sharkei2018 puts forward a compelling use case for the addition of Custom Fields to Recurring Transactions.

> I have over 100 Recurring Transactions which get generated every month, so editing the custom field for each of those is not practical. I need to be able to set a custom field value when I create the Recurring Transaction.

The ability to set Custom Fields in Recurring Transactions was previously mentioned in #1585, however that issue also covers several other potential enhancements to Recurring Transactions, which were part of the abandoned 1.4.x development, which is why I have created a specific 1.5.x feature request here.

# Example dialog

![image](https://user-images.githubusercontent.com/4060092/152030399-286b0ee7-3a8c-4e7d-8866-428a8f590783.png)

**Comment by whalley** [comment] 2022-02-18 14:53
@vomikan I like the idea, but suggest we update to add extra field in DB@v8. 

I've noticed that when duplicating the recurring transaction the custom fields are not duplicated - was this intentional? Personally I thing we should duplicate and allow user to review before pressing OK.

**Comment by vomikan** [comment] 2022-02-18 15:00
> @vomikan I like the idea, but suggest we update to add extra field in DB@v8.
> 
> I've noticed that when duplicating the recurring transaction the custom fields are not duplicated - was this intentional? Personally I thing we should duplicate and allow user to review before pressing OK.

I am working on stage 3

**Comment by vomikan** [comment] 2022-02-18 15:14
@whalley I also thought that there should be an additional field. But it is better not to use different types of custom fields for transactions and recurring transactions. Since they should have a single setup (structure). Therefore, negative IDs fit perfectly.

**Comment by gabriele-v** [comment] 2022-03-06 20:41
@vomikan @whalley not sure why it has been implemented in this way with negative ID which is a really poor workaround.

When I've developed custom fields (and attachments), I've already considered all this future scenarios without any need for DB change, and used a refkey like "Transaction", but there may be also "RepeatingTransaction" or "Budget" or "SplitTransactions" or whatever you want, but then I think @vomikan simplified it becoming only transaction, not sure why, probably when he backported 1.4.x changes.

REFTYPE should be used and filtered for this:
![image](https://user-images.githubusercontent.com/7106290/156941117-9ba16b50-4965-4f2c-846c-e97cd5026ca7.png)

Same feature for attachments:
![image](https://user-images.githubusercontent.com/7106290/156941150-7c61808c-1987-4b9b-80ff-6244f7b91771.png)

REFTYPE_CHOICES were declared here (and maybe moved in another shared model):
![image](https://user-images.githubusercontent.com/7106290/156941197-59233c44-f876-49ba-9f0c-35f5a3598447.png)

**Comment by whalley** [comment] 2022-05-12 13:10
@sharkei2018  Confirmed. Yes, this is a bug.

**Comment by vomikan** [comment] 2022-05-26 18:40
Is "Reference" okey for this field name?

![image](https://user-images.githubusercontent.com/6836805/170554815-0cd91e09-6f83-4214-a787-6d52b310dcd8.png)

**Comment by tactilis** [comment] 2022-05-26 21:36
> Is "Reference" okey for this field name?

I'm trying to understand where that dialog fits into MMEX and how it is intended to work.

I do not have a view on whether Reference is an okay name for the field until I understand the dialog. What are the possible values for 'Reference' in addition to Transaction?

**Comment by vomikan** [comment] 2022-05-26 21:40
![image](https://user-images.githubusercontent.com/6836805/170584497-e1c059b5-b46b-4373-a406-b245b80b64c3.png)

**Comment by tactilis** [comment] 2022-05-26 21:52
Ok, but what does 'Reference' actually mean?

For example, what is meant by setting Reference to Payee on the New/Edit Custom Field dialog?

**Comment by vomikan** [comment] 2022-05-26 21:58
Custom fields can be linked to :
Transaction (Recurring Transaction)
Stock
Asset
[Bank]Account
Payee

A reference is a relation to a particular dialog (data type).

**Comment by whalley** [comment] 2022-05-26 22:41
> Is "Reference" okay for this field name?

Sounds OK to me. Personally, I think we are overcomplicating the application with the custom field. Though that may be because I don't use them (as I guess applies to 90%+ of the users).

The existing extent of this to cover the transactions seems fine.

**Comment by tactilis** [comment] 2022-05-27 07:12
@vomikan
> Is "Reference" okey for this field name?

I think 'Reference' could be mean different things to different people.

Some suggestions:

 
![image](https://user-images.githubusercontent.com/4060092/170646547-c3f1e82c-753a-4197-8d16-8909ce8f5975.png)
 
 
I think 'Associated with' has greater clarity of purpose than 'Reference'.

If you do use 'Associated with', then you might consider changing the list to say:

- Transactions
- Stocks
- Assets
- Bank Accounts
- Recurring Transactions
- Payees

It reads better with the plural form (and with spaces between multiple words).

You might also want to consider the order of items in the list because the Navigation tree has them in this order:

![image](https://user-images.githubusercontent.com/4060092/170649198-43afd2bf-a2fc-40b8-8409-7f435c0da627.png)

So the order becomes:

- Transactions
- Accounts
- Stocks
- Assets
- Recurring Transactions
- Payees

Or, if you want to put the most common usages first, then I'd suggest:

- Transactions
- Recurring Transactions
- Accounts
- Stocks
- Assets
- Payees

**Comment by vomikan** [comment] 2022-05-27 08:30
@tactilis thanks. Unfortunately, it is not so easy to change this menu. 
![image](https://user-images.githubusercontent.com/6836805/170662110-81c9fb4b-27bb-41bd-9af0-aa7f5c1a1ded.png)

It will have to be translated from English into English.

What about the word "Target" ?

**Comment by tactilis** [comment] 2022-05-27 09:43
> Unfortunately, it is not so easy to change this menu.

OK I understand.

> What about the word "Target"

That still feels to be the wrong way around (like Reference).

To my mind, the custom field doesn't really _target_ or _reference_ an account type.

It feels to me as though it is an _attribute of_, or is _associated with_, an account type.

Just trying to make the meaning as clear as possible because, as you know, we don't have anyone who can keep the Help/User Manual up to date.

**Comment by gabriele-v** [comment] 2022-05-27 09:43
What about "Available for"?

**Comment by vomikan** [comment] 2022-05-27 09:50
The winner is:

![image](https://user-images.githubusercontent.com/6836805/170675781-843209d4-9a33-4a50-b2f2-73ad9bca4a14.png)

**Comment by tactilis** [comment] 2022-05-27 10:07
![image](https://user-images.githubusercontent.com/4060092/170678055-016ebaed-9003-4db1-be5a-25468af81b32.png)

Maybe the tooltip should say: "Select the item that the custom field is associated with"

By using those words we reinforce the understanding that the custom field is an attribute of/associated with the chosen item type, i.e we are explaining it two ways.

**Comment by gabriele-v** [comment] 2022-05-28 12:16
As discussed here https://github.com/moneymanagerex/moneymanagerex/issues/4216 it may be useful to have different custom fields between Recurring Transactions and Transactions, which also keep more clean the DB, without negative IDs.

> Transactions has their own cutomfields, while recurring has their own which may be different. During the creation of the normal transaction from recurring, if there is any customfield who exactly match between the two, then it's copied, otherwise is skipped.

In order to help users, we may consider adding something like the mockup below when editing a custom field which is recurring transaction type.

![image](https://user-images.githubusercontent.com/7106290/170825043-257b3453-4a67-4c6a-887e-97f1ec2d2021.png)

**Comment by vomikan** [comment] 2022-05-28 12:37
![image](https://user-images.githubusercontent.com/6836805/170825829-0a443ef2-a654-4cee-8abf-497b4654dbda.png)

**Comment by whalley** [comment] 2022-05-28 12:54
> As discussed here #4216 it may be useful to have different custom fields between Recurring Transactions and Transactions, which also keep more clean the DB, without negative IDs.
> >Transactions has their own cutomfields, while recurring has their own which may be different. During the creation of the normal transaction from recurring, if there is any customfield who exactly match between the two, then it's copied, otherwise is skipped.

I'm not convinced about this as the recurring transactions ultimately manifest themselves as transactions. It gets complicated from a user perspective if they differ and some data gets transferred and other data doesn't.

**Comment by gabriele-v** [comment] 2022-05-28 12:59
> > As discussed here #4216 it may be useful to have different custom fields between Recurring Transactions and Transactions, which also keep more clean the DB, without negative IDs.
> > >Transactions has their own cutomfields, while recurring has their own which may be different. During the creation of the normal transaction from recurring, if there is any customfield who exactly match between the two, then it's copied, otherwise is skipped.
> 
> I'm not convinced about this as the recurring transactions ultimately manifest themselves as transactions. It gets complicated from a user perspective if they differ and some data gets transferred and other data doesn't.
> 
> My view is that a recurring transaction == normal transaction, it's just not been posted yet.

Unfortunately I cannot agree with this, because they are two different entities and recurring transaction has already different fields from normal one (occurency etc..) so why it can't have its own custom field? What if I want a custom field related to occurrency? It doesn't make any sense to have it then replicated in each normal transaction.

**Comment by whalley** [comment] 2022-05-28 13:14
A recurring transaction should have two sets of custom fields by that logic. One for the recurring transaction data itself and one for the transaction it creates - this is cleaner rather than trying to match. 

I'm not proposing this as iI see it as a lot of work for little benefit as I see it, but trying to match fields between recurring and normal transactions strikes me as messy.

**Comment by tactilis** [comment] 2022-05-28 13:15
I understand what @gabriele-v is saying but from a UX point of view, I don't like the complexity and the scope for user confusion by having two sets of custom fields.

And, IMO, a message like this does not solve the problem:

![image](https://user-images.githubusercontent.com/4060092/170826924-f4b4a1b4-4509-4080-964f-73141cbc0747.png)

We we really need to know whether there are any good real-world use cases for custom fields that are specific to the parent recurring transaction, that a user wouldn't want to have copied to the child transaction. We then need to balance the importance of supporting those use cases for the (probably few) people who need them against the additional UX complexity for the majority of users.

**Comment by gabriele-v** [comment] 2022-05-28 14:38
@tactilis custom fields are there exactly to match scenarios which are not considered by developers and to suit even more MMEX on everyone needs, otherwise we would have just added that fields with the system ones.
Considering this direction, I'd prefer to have (especially around them) the maximum flexibility, instead of limit them.

@whalley potentially you are right, problem is how to manage it DB side? You will anyway end in the same case that we have now, my proposal of the "matching" it was something to find a good compromise between UX/UI and DB

UX it's important, but also having a clear DB both structure and data side. IMHO the actual "negative" workaround it's not acceptable at all on the backend side.

**Comment by sharkei2018** [comment] 2022-05-28 15:26
As an MMEX User who asked for Custom Fields to be included in Recurring Transactions and for them to be copied into accounts, I can't think of a situation where I would include a Custom Field in a Recurring Transaction that I wouldn't want to be replicated in the transaction itself.
IMO. this right hand side of the New Recurring Transaction should be the same as for an ordinary new transaction, unless there is another reason that users don't see.

![New Recurring Transaction](https://user-images.githubusercontent.com/44469703/170831862-6968392d-2311-4ae1-baf9-a76d5c1335fb.jpg)

**Comment by vomikan** [comment] 2022-05-29 16:16
I have solved the task. And I made preparations for further expansion of this functionality. As part of the 1.5.15 release, I consider the task completed.

**Closed by vomikan** 2022-05-29 16:16 UTC
Labels: enhancement, fixed
