### ISSUE TITLE
Reconciling of entries

### ISSUE THREAD

**Issue by TimBUK-2** [moneymanagerex/moneymanagerex#1778] opened 2018-08-23 19:29 UTC
When reconciling a transfer item in one account, I don't think it should reconcile in the other.

So if I make a transfer from my current account to a savings a account, I would like to reconcile them individually.

And a 2nd request related to reconciliation. Could there be a column for the reconciled balance? This would help when working through a bank statement as the balance should update as the items reconcile, matching the statement.

**Comment by slodki** [comment] 2018-08-23 19:48
Duplicate of #1180 
It's already implemented in version 1.4.0 as PR #1208 - please look at #1777 for screenchots.

For reconciled balance you can look at home screen or account panel just above a grid:
![mmex](https://user-images.githubusercontent.com/3155552/44548248-d721b200-a71d-11e8-82ef-f2a89d317d05.png)
![mmex2](https://user-images.githubusercontent.com/3155552/44548252-dab53900-a71d-11e8-9feb-4690654f7e7d.png)

We need #1298 before releasing 1.4.0...

**Closed by slodki** 2018-08-23 19:48 UTC
Labels: duplicate
