### ISSUE TITLE
new recurring transaction problem with pay date

### ISSUE THREAD

**Issue by themnd** [moneymanagerex/moneymanagerex#381] opened 2015-02-03 20:57 UTC
I'm using mac version 1.2-beta.
When you insert a new recurring transaction, when the dialog open, both the due date and the pay date are set to 1/1/2001, however you can change the due date to what you want but the pay date remains unchanged and you cannot modify it.
When you go to the recurring transactions view, your newly inserted recurring transaction will get the due date warning even if its due date is far away because the pay date is still set to 1/1/2001.

![recurring transactions](https://cloud.githubusercontent.com/assets/895523/6029262/b03832c2-abef-11e4-8488-00e150993a79.png)

**Comment by guanlisheng** [comment] 2015-02-09 03:44
@stef145g , please help to fix the bug

**Comment by stef145g** [comment] 2015-02-09 08:15
In order to make this facility work, the **calendar** sets the payment date and due date.
The due date is then set to the correct value using the dropdown calendar control.

**For Windows:**
For a new entry, the calendar control displays the current system date, being today.

**For Mac**
Not sure if this is the case.
1. Was the calendar displaying the correct date in V1.2.0-Alpha?
2. Was there any change in the dates when using the calendar?

**Comment by themnd** [comment] 2015-02-09 11:49
I'm speaking of the Mac version.
I didn't try the V1.2.0-Alpha, but it was working in 1.1.2.
On Mac there is no a Calendar control...i.e. there are no calendars that pop up when you click on the date in the same way you do on the windows version.
When you say:

"The due date is then set to the correct value using the dropdown calendar control"

It is true for me also, the problem is that it will change one day at a time, starting from year 2001 (month and date are set to the current day and current month), so it takes a lot to get to the correct year.

Just to be clear, in the example above, the due date was set to 1/2/2001 (first February 2001), if I click on the due date and start clicking on the up key, the date will change to 2/2/2001, 3/2/2001 and so on...I did not find a way to change directly the month or the year.

If i remember correctly, previously, the two dates were set equals, and when you click on the month or the year, you can change just that with up/down keys.

**Comment by guanlisheng** [comment] 2015-02-10 02:35
hi @themnd , would you mind to provide some screenshots here?

**Comment by themnd** [comment] 2015-02-15 16:02
I understood what you mean with the "Calendar Control"...silly me.
It is present in the dialog on left, if you click there you can automatically set the due date (the date on the left), however it seems that you can't quickly change the year, you can only change the day and month.

**Comment by stef145g** [comment] 2015-02-16 10:41
In windows the calendar works as follows:

**Selecting the month will bring up the months.**
![repeattransdialog](https://cloud.githubusercontent.com/assets/6927151/6210307/585a5714-b622-11e4-866b-1c2519ed5d2f.png)

**Selecting the year, displays the years.**
![repeattransdialog2](https://cloud.githubusercontent.com/assets/6927151/6210319/8007eca4-b622-11e4-9d02-a8a639b55c55.png)

**Selecting the year range , displays a range of years...**
![repeattransdialog3](https://cloud.githubusercontent.com/assets/6927151/6210328/a6f4a92e-b622-11e4-9658-2d485f3ac178.png)

Selecting the required year, month, and day, sets the calendar.

Navigating back to today can become a problem and this can be fixed, with the addition of extra control buttons.

Not sure how it works for a Mac. Perhaps pictures can be displayed.

**Comment by themnd** [comment] 2015-02-16 10:58
The calendar on the mac is more "basic", when you create the transaction you have:
![screen shot 2015-02-16 at 11 51 55](https://cloud.githubusercontent.com/assets/895523/6210707/83f1dc3a-b5d2-11e4-9bf5-7675adfe9585.png)

If you select a day in the calendar, the both dates are updated:

![screen shot 2015-02-16 at 11 52 08](https://cloud.githubusercontent.com/assets/895523/6210716/9c5adcc2-b5d2-11e4-8fd5-708245f9d6da.png)

However, you can select the year in the left date field and you can change it:

![screen shot 2015-02-16 at 11 52 26](https://cloud.githubusercontent.com/assets/895523/6210734/c8a23d48-b5d2-11e4-9bf7-1e06cdb45552.png)

You can't do that on the right date field which is set only by clicking on the calendar.

**Comment by stef145g** [comment] 2015-02-16 11:53
The Transactions Details (Right hand side) date represents the **Payment Date**, and can only be changed by the calendar for New, or Edit. **Logic:** Transaction_Date = Payment_Date

The transaction date can be changed when the panel is used for **Enter next Occurrence...**. 
No change from previous functionality.

Thanks for the pictures on Mac. Your demonstration of year change is the same as Windows.
On the calendar control, do the arrows navigate the calendar back and forward?
They do in Windows.

This highlights system incompatibilities, and can only be fixed by someone using a Mac.

**Comment by themnd** [comment] 2015-02-16 13:04
As far as I remember, when you use "Enter next occurrence" the transaction date was not set to the current day which is happening now (this defeat, somehow, the purpose of setting a detailed date).
When you click the left and right arrow on the calendar control, you switch the month. In my third screenshot you can seen that the calendar has different abilities then the windows version (btw on windows it is a standard system component), you can't change the year of the calendar, you can change the year of the date field only.

**Comment by stef145g** [comment] 2015-02-17 09:53
With @themnd's reference to: **when you use "Enter next occurrence"** above, this is a new issue.

The logic and reason for the Next Occurrence split was this:
Reference: http://sourceforge.net/p/moneymanagerex/feature-requests/348/

**Summary**
A bill or invoice is issued weeks in advance with a request to pay the account by the due date. Failure to do this date would usually incur a fee. Payment in most cases is actually done sometime between the **Date of Issue** and the **Due Date**, being the **Payment Date**. Thus on entering the transaction, the date is set to the **Payment Date**. When payment is delayed, the actual payment is assumed to be today, rather than the due date. This satisfies the original request, and thus the reason for the change.

A second request: http://sourceforge.net/p/moneymanagerex/feature-requests/365/ has been made, that would have a button set the transaction to the due date when entering a transaction.

Personally I don't agree with having the transaction date set to the due date on entry, but I do agree to the second request of having a button to allow the user to set the transaction date to the due date.

**Comment by omalleypat** [comment] 2015-02-25 03:01
@stef145g I think that some of the confusion comes in because the Transaction date appears to only change if the calendar is clicked. If you manually type the date in the "Due Date" (left) control, the "Transaction Date" is not updated. Is this also true on Windows?

I'm glad you posted, because I could not figure out how it worked because I never used the calendar. The reason for that is the default date issue and the poor usability of switching years on Mac.

I think that we may want to change the initialization for the control. It appears that on Mac that using wxDefaultDateTime does not actually set the control to today as is stated in the documentation here: http://docs.wxwidgets.org/trunk/classwx_date_picker_ctrl.html#acd8017cd43d31da4e60e7933c2d76be9
but instead sets it to 12/31/2000 for me and 1/1/2001 for @themnd (probably time zone difference). Anyway, if we explicitly set it to the current date, that may alleviate that incompatibility. The calendars are very different as you can see and the mac version is much less friendly.

Let me know what you think about these options.

**Comment by stef145g** [comment] 2015-02-25 10:14
@omalleypat  When you manually type the date in the **Due Date** (left) control, the **Transaction Date** is not updated for both Windows and Mac. This is by design because the date field in the transaction panel, displays the payment date. To negate the Payment and Due Date feature, make the dates the same. Manual entry may still pose a problem therefore your suggestion of the button has merit.

The posted Mac pictures has showed me the incompatibilities and I intend to address this issue by providing controls to improve the calendar as follows:

- Provide a button to set calendar to today.
- Provide backward and forward spin control to move year forward and backward.
- Selecting Days and months are already provided by the control.

This will fix the **New** and **Edit** issue.
For the **Enter Entry** issue, a button on the transaction panel can set the date to the due date as you suggested. Now I also realise that the date of the date controls need to be set for the Mac.
This will assist users for both Windows and Mac.

I will post pictures on this as I progress for evaluation as time permits.

**Comment by omalleypat** [comment] 2015-02-25 14:32
> To negate the Payment and Due Date feature, make the dates the same.
@stef145g , It seems like the Payment date cannot be set when creating or editing a repeating transaction, the control is disabled.

**Comment by stef145g** [comment] 2015-02-25 19:01
@omalleypat  This is done using the Calendar control, (Top Left).  Works on Windows and Mac as demonstrated above. The Due Date (Bottom Left) is NOT changed.

**Comment by omalleypat** [comment] 2015-02-25 20:29
@stef145g - in the mac screenshots above, changing the calendar control on the top left seems to update both dates, confirmed by the caption above the second picture.
>If you select a day in the calendar, the both dates are updated

I just downloaded the portable version of 1.2 beta for windows and it seems to change both the payment and due dates when you click on the calendar (maybe this has changed in master since then). I can click the payment date in the calendar, then manually enter the due date (by typing over the digits) to get a difference as you suggester earlier. 



I tested out a few cases and it seems that the repeating transaction will preserve the difference between payment date and due date (example: payment date 2/25 for due date 2/28 will become 3/25 and 3/28 next month). What if we just added a field in the "repeating transaction details" area for "pay x days before due date"? Then the date on the right half of the panel is not involved on "New" or "Edit", only "Enter". I think that would simplify the UI a bit - would anything be lost in this change that I am not thinking of?

**Comment by stef145g** [comment] 2015-02-26 10:51
@omalleypat - your suggestion leads me back to the original problem I had in planning this and I will explain my original planning process.

**Planning Problems:**
- How do we get the number of days in the GUI?
- How do we store this information? I did not want to add extra fields in the existing table.

I discovered that the date in the transaction was not used. Fantastic!

**My Logic:**
Paying something X days before the "Next Occurrence" equates to a date of payment or "Payment Date". This means that the Next Occurrence must be the Due Date. Not wanting to reorganise a lot of other sections, the logical step was to have the Next Occurrence date preserved. Therefore, the Next Occurrence date was reclassified as the Due Date. Same internal functionality.

Now I had a problem of  how do I get x days before the Due Date being the Payment Date, and implement this in the GUI?
Not knowing the problems it would cause for Mac users, I chose the calendar control, to provide the initial dates, and thus giving the calendar control some useful functionality. This seams logical as it is on the left side being the reoccurrence settings side.

**Next problem:**
- What happens on next iteration, set by the repeating parameter?
- This setting must be continuous, therefore the due date and payment date must advance equally.

The last thing we need is to have to change the settings of a repeating transaction for the next time this occurs.

**This dialog has 2 stages:**

**Setting up the transaction.**
- I can see that when are setting up the repeating transaction, we need to be able to set the dates easily.
- When is this payment actually made? Obviously it must be the payment date. Reason for showing this date on the Transaction Panel, but not activating it in setting up stage.

**Entering the transaction:**
- Only one date needs to be changed. The date of the entry. (Right Hand Side)
- If we this set to auto manual, and we cancel it, therefore the payment must be delayed.
- Next time we run MMEX, and we accept the payment and assumed that it is today. If this is not the case, we can simply readjust the date before we accept.
- If this is set to Fully Auto, the payment date and due date become irrelevant, as it will be the same as having a Next Occurrence date. On setting this up, the calendar control sets up both dates and that is it.
- Making a manual entry, the Transaction Date comes up as today. Same reasoning as Auto Manual.

If the dialog is confusing, then perhaps we need to redesign the dialog. Maybe by removing the calendar or providing extra functionality for the calendar. Perhaps even splitting the actions on setting up and enter.

**Comment by omalleypat** [comment] 2015-02-26 14:10
@stef145g Thanks for the detailed description. I think most of the confusion came in because of the calendar differences on each platform and the "requirement" to use the calendar to set the payment date. Is there any reason why we couldn't allow manual entry of the dates for both "due date" and "payment date" on "New" or "Edit" (i.e. removing the ->Disable() lines in the code). That would allow the user to manually type the date and I probably would have never thought twice about it. If you don't like that solution, the other option would be to make the date control on the right hand side invisible instead of disabled, since it is really set on the calendar. One of these, combined with the default date calendar date fixes, I think this should be sufficient for v1.2 - what do you think?

In regard to your last point, I've always thought it strange that the dialog has left and right halves like it does. If it were just a two step process for "New" or "Edit" where Step 1 is basically the left half of the panel and Step 2 is the right half of the panel (but underneath is the transdialog code, modified to accept the output of the billsdeposits code), that would make the code a lot more maintainable. I've started to work on this a couple times, but have not carried it through.

**Comment by stef145g** [comment] 2015-02-28 02:03
@omalleypat - I have taken your first suggestion on board, and have now come up with a solution. This has been created in a new branch:  https://github.com/moneymanagerex/moneymanagerex/tree/bills_date_setting_stef145g from the master branch. If this solution is good, the fix commit can be either merged into or cherry-picked using the master branch.

If we want to include this in the V1.2.0 release, the fix commit can also be cherry-picked using the V1.2.x branch.

** Way it works**
Calendar control usage is now optional.
- When used, will set both dates for a new Repeating Transaction.

Payment Date and Due date can be set separately.

The Payment Date will affect the calendar control, and an extra button has been provided to set Payment date to Due date.

**Comment by omalleypat** [comment] 2015-02-28 03:07
@stef145g - I tested your changes and they seem to be working as described on mac. Thanks for your effort! 

As far as whether to include it in 1.2, it would be nice since the fix makes repeating transactions much more usable on mac. The biggest issue is the home screen if the user can't figure out how to get the pay date out of 2001. I understand the translation is a concern.

**Comment by guanlisheng** [comment] 2015-03-11 02:02
@stef145g  and @omalleypat , would i close this issue now?

**Closed** 2015-03-11 07:34 UTC
Labels: bug
