### ISSUE TITLE
Can´t add Initial Balance on Polish Zloty (PLN) Currency

### ISSUE THREAD

**Issue by spint0** [moneymanagerex/moneymanagerex#5643] opened 2023-02-12 11:05 UTC
Trying to set up a Checking Account with Polish Zloty opening from 01.01.2019 and it shows the following error:

![image](https://user-images.githubusercontent.com/58642359/218307151-2963d0d8-5b26-42eb-bddf-70433eb4f022.png)

Running on:
Windows 10 (build 19044), 64-bit edition
MMEx Version: 1.6.3 64-bit

The account can still be created if you hit cancel, however, it is going to create with the date of today which will then conflict with the other accounts in case you have transactions in the past between accounts or past expenses. Trying to set up a formula does not work also.

**Comment by n-stein** [comment] 2023-02-12 13:00
Confirmed in 1.6.4 Beta. Seems to only be an issue if PLN is not also the base currency.

**Comment by n-stein** [comment] 2023-02-12 18:27
If I change PLN to use decimal separator of `.` in CURRENCYFORMATS_V1 I do not receive this issue. So it seems this is because the amount field is expecting the decimal separator of the base currency rather than the account currency.

**Comment by n-stein** [comment] 2023-02-12 21:18
@spint0 As a workaround, go to Tools->Organize Currency, Right click on the zloty and select 'Edit', then change the decimal and group chars to be the same as your base currency.

**Comment by n-stein** [comment] 2023-02-13 01:16
After further debugging, the issue is due to the mismatch between the account currency decimal/group separator and the Locale (not the base currency), specifically this else condition:

https://github.com/moneymanagerex/moneymanagerex/blob/b664833b1d1758fbb69260108690d14c584c0d89/src/model/Model_Currency.cpp#L347-L360

**Comment by spint0** [comment] 2023-02-14 19:53
Great! Thanks, @n-stein . Much appreciated!

**Comment by n-stein** [comment] 2023-02-17 22:34
Fixed by removing the default "en_US.UTF8" from `auto locale = Model_Infotable::instance().GetStringInfo("LOCALE", "en_US.UTF8");'

**Closed** 2023-03-28 09:39 UTC
Labels: bug
