### ISSUE TITLE
Cashflow reporting errors

### ISSUE THREAD

**Issue by FreedomSOM** [moneymanagerex/moneymanagerex#6809] opened 2024-07-02 10:35 UTC
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] MacOS Monterey version 12.7.5
 - [ ] Linux 

# Description of the bug

Hi, If I go Reports/Cashflow/Transactions the forecast sometimes is incorrect. I have noticed that if I check on a day that transactions have gone and are listed, it re-lists those transactions in the report and therefore duplicates the transaction on the forecast. If I check on a day when no transactions have gone through, the forecast is correct. Basically it needs to not include the transactions of the day that you check as they are already included in the starting balance and just add transactions from the next day. Hope that makes sense. I saw there was a similar issue listed twice with the answer it was fixed but it is not on my version (iOS) version 1.8.0 which it says is the latest.
Thanks for looking and any help in advance.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Expected result:

Actual result:

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by n-stein** [comment] 2024-07-02 14:35
The fix has been implemented for 1.8.1 which is not yet released. 

You can try the latest 1.8.1 beta for macOS here https://link.ipx.co.uk/mmex-mac-betas.

Let us know if the problem is not resolved in that version.

**Comment by ringola96** [comment] 2024-09-10 07:15
Hi, I have the same problem, I downloaded the beta version but I can't open a db with password

**Comment by wolfsolver** [comment] 2024-11-12 10:41
there is a preview for release of 1.8.1?
I have same issue and cashflow forecast is amazing feature (and this is why I use Money Manager Ex!!)

**Comment by whalley** [comment] 2024-11-13 06:29
> there is a preview for release of 1.8.1? I have same issue and cashflow forecast is amazing feature (and this is why I use Money Manager Ex!!)

https://moneymanagerex.org/docs/downloads/development/

**Comment by whalley** [comment] 2024-11-13 06:34
https://github.com/moneymanagerex/moneymanagerex/issues/6745

**Closed by whalley** 2024-11-13 06:34 UTC
Labels: duplicate
