### ISSUE TITLE
In "All Transactions" view, show total ammount of selected transactions

### ISSUE THREAD

**Issue by ApZero** [moneymanagerex/moneymanagerex#6804] opened 2024-06-24 17:24 UTC
# Description of the feature

When I have an Account open and I select many transactions, the total ammount of those transactions is shown in the box below:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/173719275/1f65c8c9-104d-44c3-94eb-22aa5de59b10)

But this doesn't happen when I do it in the **All Transactions** view:
![image](https://github.com/moneymanagerex/moneymanagerex/assets/173719275/41e7ff32-0b15-4deb-9b1c-7c734224b9d5)

Having the total ammount selected would be really useful and I'll appreciate it.

**Comment by whalley** [comment] 2024-06-24 20:05
The balance can be somewhat meaningless on the 'All Transactions' view where multiple accounts are displayed.

**Comment by n-stein** [comment] 2024-06-24 20:36
> The balance can be somewhat meaningless on the 'All Transactions' view where multiple accounts are displayed.

Agreed. Also, the 'All Transactions' view shows multiple currencies, so the total would have to be converted to base currency to make sense.

**Comment by rmelillo76** [comment] 2024-06-24 22:00
Ageeed, duplicate of #6233 - the possibility of different currencies is the main driver for not being able to implement this functionality

**Closed** 2024-06-25 21:50 UTC
Labels: wontfix
