### ISSUE TITLE
Collapse when displayed graphically 

### ISSUE THREAD

**Issue by Heny67** [moneymanagerex/moneymanagerex#3758] opened 2021-08-07 11:03 UTC
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [] Mac OSX
 - [x] Linux 

# Description of the bug
In a graphical statement, mmex crashes when requesting a second statement. It still displays the first statement properly, but in most cases it crashes at the second. I have attached the xml file. 

[mmex.xml.zip](https://github.com/moneymanagerex/moneymanagerex/files/6948975/mmex.xml.zip)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. 
2. 
3. 

…

Expected result:

Actual result:

# Additional information

Money Manager Ex
Version: 1.5.1 64-bit
• Build on Apr 24 2021 14:50:51
• Adatbázis verzió: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.0.4 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.3.3
• lunasvg 
• libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.16.3
• GNU Make 4.2.1
• GCC 9.3.0 • Ubuntu 20.04 'focal'
Running on:
• Ubuntu 20.04.3 LTS "focal"
• Linux 5.4.0-81-generic x86_64
• Hungarian (UTF-8)
• 1366x768 24bit 96x96ppi

**Comment by tactilis** [comment] 2021-08-07 12:47
@Heny67 Please could you describe the **exact steps** to reproduce this problem.

Reproduction steps:

1. Do this...
2. Do that...
3. Do...

It is not clear at all what you mean by "graphical statement".  It could be a transaction list. It could be a report.

More details would help find the bug.

Thank you

**Comment by whalley** [comment] 2021-08-08 00:13
From XML looks like a webkit issue similar to this - https://github.com/moneymanagerex/moneymanagerex/issues/1612.

**Comment by Heny67** [comment] 2021-08-08 06:40
1. I open the Investment Summary
2. I open another report eg: Accounts Balance - Monthly report and the program crashes

**Comment by Heny67** [comment] 2021-09-04 10:33
The error persists. As soon as I select the "where the money goes" report the program immediately crashes.

**Comment by whalley** [comment] 2021-09-05 14:42
What version of MMEX and wxWidgets are you using?

**Comment by Heny67** [comment] 2021-09-05 15:23
Additional information

Money Manager Ex
Version: 1.5.1 64-bit
• Build on Apr 24 2021 14:50:51
• Adatbázis verzió: 7 • (aes128cbc)
MMEX is using the following support products:
• wxWidgets 3.0.4 (wxGTK 3.24)
• wxSQLite3 4.6.0 (SQLite 3.31.1) • RapidJSON 1.1.0
• Lua 5.3.3
• lunasvg
• libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
• gettext 0.19.8.1
• apexcharts.js
Build using:
• CMake 3.16.3
• GNU Make 4.2.1
• GCC 9.3.0 • Ubuntu 20.04 'focal'
Running on:
• Ubuntu 20.04.3 LTS "focal"
• Linux 5.4.0-81-generic x86_64
• Hungarian (UTF-8)
• 1366x768 24bit 96x96ppi

**Comment by tactilis** [comment] 2021-09-05 16:06
> Money Manager Ex
> Version: 1.5.1 64-bit

You have an out of date version of MMEX. The latest version is 1.5.6

**Comment by Heny67** [comment] 2021-09-05 17:31
And can I find a deb package for ubuntu 20.04 somewhere?
That's all I found.

**Comment by whalley** [comment] 2022-10-18 07:32
Closing. We now have deb packages are now part of CI build. Not reports of this error being present.

**Closed by whalley** 2022-10-18 07:32 UTC
Labels: duplicate, outdated, linux
