### ISSUE TITLE
Account summary not showing assets or shares

### ISSUE THREAD

**Issue by swjpanton** [moneymanagerex/moneymanagerex#5346] opened 2022-11-18 12:59 UTC
> I have uploaded latest version but the account summary does not show asset or share accounts in monthly or yearly. (This is in the apple mac version)
> Please do not remove information attached below this text.

<hr>Version: 1.6.1 64-bit<br>
 • Build: Nov 18 2022 10:35:22<br>
 • db 16 •  (aes128cbc)<br>
 • git 09cb03154 (2022-11-18)<br>
 • master<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMac 13.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.84.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0<br>
 • gettext 0.21.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.24.2<br>
 • GNU Make 3.81<br>
 • Clang Apple LLVM 14.0.0 (clang-1400.0.29.202)
<br>
<br>
OS:<br>
 • macOS Ventura Version 13.0.1 (Build 22A400)<br>
 •  English (United Kingdom) (Western (Mac OS Roman))<br>
 • 2560x1440 32bit 144x144ppi

**Comment by whalley** [comment] 2022-11-18 13:09
> the account summary does not show asset or share accounts in monthly or yearly. 

Can you please be more specific. When you say '**does not show**' does this imply teh columns are missing, all values are zero, or the values are wrong.

A screenshot may help.

**Comment by tactilis** [comment] 2022-11-18 13:41
@swjpanton 

Please could you paste your screenshot here https://github.com/moneymanagerex/moneymanagerex/issues/5346 rather than replying via email (where the screenshot does not appear)

**Comment by swjpanton** [comment] 2022-11-18 14:11
screenshots attached

[screenshot 1.pdf](https://github.com/moneymanagerex/moneymanagerex/files/10041962/screenshot.1.pdf)
[screenshot 2.pdf](https://github.com/moneymanagerex/moneymanagerex/files/10041966/screenshot.2.pdf)
[screenshot 3.pdf](https://github.com/moneymanagerex/moneymanagerex/files/10041969/screenshot.3.pdf)

**Comment by tactilis** [comment] 2022-11-18 15:02
The problem is not the report, which appears to be correctly showing your assets' Current Values of £0.00

The question is why do your assets have a Current Value of £0.00 as shown in your _screenshot 3.pdf_ given that you have 'Change in Value' set to None.

Testing...

I have just run **1.6.0** with 3 assets having:

Initial Values: 10,000.00 / 20,000.00 / 30,000.00
'Change in Value' set to None.
Current Values: 10,000.00 / 20,000.00 / 30,000.00

I upgraded to **1.6.1** and the current values are now:
Current Values: 0.00 / 0.00 / 0.00

Reverted to **1.6.0** and the current values are now back to:
Current Values: 10,000.00 / 20,000.00 / 30,000.00


Bug confirmed in 1.6.1

**Comment by whalley** [comment] 2022-11-18 16:03
https://github.com/moneymanagerex/moneymanagerex/issues/5197

**Comment by tactilis** [comment] 2022-11-18 16:22
> Think this change (https://github.com/moneymanagerex/moneymanagerex/issues/5197) now only calculates the appreciation/depreciation if asset transactions are present.

Ah. That's an oversight.

**Comment by n-stein** [comment] 2022-11-18 20:41
> Think this change (#5197) now only calculates the appreciation/depreciation if asset transactions are present.

That's true. But this is in line with how asset values are calculated whenever you enter an asset transaction in 1.6.0 and all prior versions -- MMEX assumes all value on an asset has arrived there via asset transaction. It doesn't store the "Initial Value" then add the asset transactions as ASSETS_V1 only has a single field for VALUE.

I think this is one of the major misconceptions about asset values in MMEX. The asset value is recalculated _as the sum of all asset transactions_ any time you create/change/delete an asset transaction. You can test this in 1.6.0 or any prior release -- if you create a $10,000 asset _without_ entering an asset transaction and then try to increase the value to $11,000 by entering a $1,000 asset transaction you'll find the value actually drops to $1,000 since there is no record of that initial $10,000 in the transaction register.

We can use the ASSETS_V1-VALUE field to calculate current value if no asset transactions exist, but that doesn't solve the issue of asset transactions resetting the value of the asset. Ideally the initial asset transaction should be mandatory. If the user chooses not to enter it then auto-create an asset account with an initial balance = the asset value and auto-create the withdrawal asset transaction from the asset account to the asset using the "Transfer" checkbox so that it isn't included in income/expense.

**Comment by tactilis** [comment] 2022-11-18 22:01
> Other option (maybe simpler) is to store the INITIALVALUE separately in ASSETS_V1 and always use INITIALVALUE and STARTDATE as the basis for value calculation, adding in other asset transactions on top and storing the final sum in the VALUE column. In this scenario we would not automatically prompt for an asset transaction upon asset creation.

This is a much simpler solution and matches the mental model that most people would have.

Create an asset for 10,000, set its 'Change in Value' to None and it should be valued at 10,000 for ever more unless the user makes any transactions to add or subtract the value.

Same applies appreciation and depreciation. The % should apply over time to the initial value to produce the current value.

In 1.6.0 the Current Value is equal to the Initial Value (with  'Change in Value' set to None)

![image](https://user-images.githubusercontent.com/4060092/202809707-aaf636df-de03-4c7f-87af-d7e9bbc375cb.png)
 
![image](https://user-images.githubusercontent.com/4060092/202809958-7729665d-6b9d-4cbf-a580-fed76d02782e.png)

In 1.6.1 (same database) we have:

![image](https://user-images.githubusercontent.com/4060092/202810181-6578fbbf-38af-434a-a76c-ad8356bde86e.png)
 
 
![image](https://user-images.githubusercontent.com/4060092/202810238-f998d5ed-5ddb-45ef-b430-6309b73e9dab.png)

The 1.6.1 behaviour is not logical for the user.

**Comment by n-stein** [comment] 2022-11-18 22:02
@whalley can we add INITIALVALUE to ASSETS_V1 in DB v17 to facilitate this?

**Comment by n-stein** [comment] 2022-11-18 22:28
If we make the initial value always count towards the current value we will break asset values for everyone who did use an initial asset transaction. Maybe the best fix is just to use VALUE only when there are no asset transactions.

**Comment by tactilis** [comment] 2022-11-18 22:30
> Maybe the best fix is just to use VALUE only when there are no asset transactions.

Yes. That is the way that 1.6.0 seems to have worked. Current Value = Initial Value if there are no transactions _and_ Change of Value is None.

**Comment by tactilis** [comment] 2022-11-18 22:38
I think the fundamental problem is that, unlike bank accounts, where the MMEX account corresponds _exactly_ to an account in the real world (a simple and obvious mental model) - for assets people think that they are entering _the_ asset itself (house, car, artwork, etc) into MMEX - not that they are creating an account. My house doesn't have an account - it's a real world thing that hopefully appreciates at some rate (and, _maybe_, also changes in value if I do some renovations to it). The mental model is not one of making transactions in an account - rather it is one of making changes to the value of the asset itself.

**Comment by n-stein** [comment] 2022-11-18 23:00
> The mental model is not one of making transactions in an account - rather it is one of making changes to the value of the asset itself.

If you enter any asset transactions you can no longer control the value of the asset itself in the current design.

**Comment by n-stein** [comment] 2022-11-18 23:07
Fixed in PR #5349

**Comment by n-stein** [comment] 2022-11-18 23:12
@swjpanton

Add an asset transaction for the value of your asset to get it to show in the reports until 1.6.2 is released.

**Comment by tactilis** [comment] 2022-11-19 09:07
@n-stein 
> If you enter any asset transactions you can no longer control the value of the asset itself in the current design.

Yes, I understand.

I think that the problem of assets not aligning with the obvious mental model (https://github.com/moneymanagerex/moneymanagerex/issues/5346#issuecomment-1320608238) is compounded by the fact that when you make an asset transaction, you have to specify an account for the deposit/withdrawal/transfer, whereas in reality, the asset may have changed value due to external factors; e.g. house values have increased or an artist has become more sought after.

![image](https://user-images.githubusercontent.com/4060092/202841612-62846507-f352-4546-a6bb-4a4081d9defb.png)

If the user did not elect to create an asset account, then as shown above, they have to select another of their accounts for the change in value, even though the asset's value change is unrelated to a real world transaction that the user has made. It's all very confusing.

I suspect that the answer to the question below when creating a new asset is _"Err, I have no idea"_.

![image](https://user-images.githubusercontent.com/4060092/202842861-20a2f083-778a-4482-a93d-d1e94d01f3ed.png)


Additionally, in a users' mind, there shouldn't need to be any transactions to apply a % appreciation or depreciation; it should 'just happen' and be expressed as the Current Value of the asset at a given time.

Apologies if the above seems like a bit of a ramble. I'm finding it hard to get my head around this and I don't know what we should do about the confusion. It does feel as though assets were originally shoehorned into MMEX's way of handling of accounts (maybe for valid reasons?) but unfortunately that doesn't match the way (most?) people think about tangible assets.

**Comment by swjpanton** [comment] 2022-11-19 10:59
For asset values such as property why not just have a separate box to record current value. That way depreciation/appreciation % is irrelevant. Keep it simple.

Also is there a reason for share accounts not showing any value at all.

**Comment by n-stein** [comment] 2022-11-19 14:45
> For asset values such as property why not just have a separate box to record current value. That way depreciation/appreciation % is irrelevant.

The issue with this is you have no way to report changes in current value over time if you are manually maintaining it outside of the transaction register. In the monthly/yearly report would you show initial or current value? Or automatically distribute the difference at time intervals between the current date and start date (which may be incorrect)?

>Also is there a reason for share accounts not showing any value at all.

Share accounts are analogous to asset accounts in that they don't hold the value of the stock/asset themselves. They are just a pseudo "bank" account that holds normal and stock transactions that don't belong anywhere else. For example, if your stock pays a dividend that is automatically reinvested, you would add a normal deposit to the share account as the payout then immediately add a withdrawal stock transaction from the share account for the repurchase. It wouldn't make sense to record this in your checking account as the dividend is never transferred there.

The same thing is true of asset accounts. If you have a piece of artwork that has appreciated MMEX expects that value to come from somewhere. It doesn't make sense for it to come from a regular bank account (you didn't pay for your artwork to be worth more), so the additional value comes from the asset account (i.e. it is the asset itself that provides the increase in value).

That's not to say all of the assets value should come from the asset account. For example your houses value could be viewed as a sum of transfers from a loan account (the mortgage), a checking account (the down payment), and an asset account (any equity above that contributed by the other two transactions). In such cases it is beneficial to choose what account the asset value comes from.

**Closed** 2022-12-08 17:54 UTC
Labels: bug, fixed
