### ISSUE TITLE
Xchange rate (advanced box) not picking up rate after currency update

### ISSUE THREAD

**Issue by marty008** [moneymanagerex/moneymanagerex#4648] opened 2022-06-18 09:43 UTC
MMEX version:
 - [x] 1.5.x
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
On existing transactions, clicking twice on Advanced box picks up new exchange rate. 
On new s/w version, exchange rate is seemingly ignored, i.e amount becomes same in both boxes. 
On  inspecting exchange rate  table , it shows current value pound/euro 1.1638 as expected

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Select existing transaction in account view and open
2. Transaction shows pound and euro values because Advanced box is selected
3. Click on advanced box and euro value blanks out
4. Click again on advanced box and euro value appears as equal to pound value
…

Expected result: Euro equivalent of pound value (e.g £10 becomes 11.64 euros)

Actual result:  Euro value = Pound value

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by didikrm** [comment] 2022-06-18 17:43
I am experiencing the 'opposite' problem so to speak. When transferring from one account to another that uses the same currency, the other side gets the amount converted into the 1/forex of the base currency even if the advanced box is not selected.

Example based on the data above: when transfer 10 from an EUR to EUR account where the base currency is GBP, the amount in gets converted into GBP at a rate of 1.1638 so 11.6EUR, although both accounts use the same EUR currency.

This issue occurs with using an existing database with existing account, and not when creating a new database with new accounts.

**Comment by whalley** [comment] 2022-06-19 10:53
> I am experiencing the 'opposite' problem so to speak. When transferring from one account to another that uses the same currency, the other side gets the amount converted into the 1/forex of the base currency even if the advanced box is not selected.

I can't reproduce this on my DB. (Euro -> Euro, Base = GBP)

**Comment by gombosg** [comment] 2022-06-19 11:38
I'm experiencing a similar problem, though I want to enter a manual from-to amount for a transfer. When 'advanced' is checked and I enter a 'to' amount, after tabbing out from the input field, the 'from' amount is autofilled with the 'to' amount and I'm unable to manually specify a 'to' amount.

**Comment by gombosg** [comment] 2022-06-19 13:22
@vomikan ☝🏽 that PR should fix entering amounts.

**Closed** 2022-06-19 13:23 UTC
Labels: bug
