### ISSUE TITLE
QIF File import procedure improvement

### ISSUE THREAD

**Issue by speedygh** [moneymanagerex/moneymanagerex#5496] opened 2023-01-04 10:32 UTC
When you import a QIF file of an account ‘A’ which includes a transfer transaction from this account ‘A’ to another account ‘B’, the system imports the transfer transaction to account ‘A’ and also creates the relevant transaction to account ‘B’. 
In case you import the QIF file of account ‘B’, the system imports again the same transfer to account ‘B’ and also creates again the relevant transaction to account ‘A’. 

So, this **one transfer transaction is registered and presented twice** in both accounts’ ‘A’ and ‘B’ ledgers. 

I think that in case of an import job for a full set of accounts from another system e.g. MS Money, Quicken etc., it would be great if a flag in the import form could be added, which when selected, the system for each imported account, will **not import the transfer transactions originated from the other accounts**. This way, when you import account ‘A’ the system will create the transaction to accounts ‘A’ and ‘B’, but when you import account ‘B’ the system will ignore this specific transaction.

A relevant case is #2610

**Comment by tactilis** [comment] 2023-01-04 11:40
@speedygh The issue you have raised is essentially a duplicate of #2610, except that your issue involves the importing from two separate QIF files, whereas #2610 has the transfers for the two accounts in the same file.

So that we don't have a proliferation of duplicate issues, could you add your comment to #2610 please and close this one.

**Closed** 2023-01-04 12:55 UTC
