### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by k2ironman** [moneymanagerex/moneymanagerex#1779] opened 2018-08-25 09:28 UTC
The mobile app has dark theme and it would be great if I can set a dark theme on my PC also.
Thanks :)

**Comment by slodki** [comment] 2018-08-25 15:44
For Linux and Mac it's very easy - you can change GTK+ theme in the system settings:

![mmex](https://user-images.githubusercontent.com/3155552/44620054-7bc30180-a88e-11e8-8d10-14a71036120e.png)

**Comment by slodki** [comment] 2018-08-26 15:51
From [wxWidgets blog](https://wxwidgets.org/blog/2018/06/post-3.1.1-progress/) about Mac and dark theme:
> Stefan Csomor, Daniel Kulp and others have added supported for the upcoming next macOS version: 10.14, a.k.a. Mojave, and, notably, its new dark mode. Some problems might still remain, so please test your Mac applications with Mojave and let us know if you notice anything wrong.

**Comment by k2ironman** [comment] 2018-08-26 16:02
I'm using windows, that's why I wrote here.

**Comment by vomikan** [comment] 2019-02-27 18:19
https://www.google.com/amp/s/www.howtogeek.com/222614/how-to-enable-windows-10s-hidden-dark-theme/amp/
https://forums.wxwidgets.org/viewtopic.php?t=34742

**Comment by vomikan** [comment] 2020-05-12 18:41
https://gist.github.com/ZachSaucier/8295d9dc926d7064ff0d4f3f04b35b55

**Comment by vomikan** [comment] 2020-05-12 18:48
![image](https://user-images.githubusercontent.com/6836805/81733177-4020fe80-949a-11ea-9afe-92525893e119.png)

**Comment by valsamis-d** [comment] 2020-08-08 07:00
> 
> 
> ![image](https://user-images.githubusercontent.com/6836805/81733177-4020fe80-949a-11ea-9afe-92525893e119.png)

@vomikan this one looks great. For what I understand, though, there's a lot of techie work involved to achieve this look :( Is there anyway to share the css file you're using? I'm using Windows 10. Thanks!

**Comment by vomikan** [comment] 2020-08-08 08:05
Hi there,

It would working only on Linux or Mac. Unfortunatly, on Windows Black theme does not change app color settings.
But you can change homepage color settings by merge 
https://gist.githubusercontent.com/ZachSaucier/8295d9dc926d7064ff0d4f3f04b35b55/raw/06a8cc03bbdbb7e36f7ae192f834226320f752cd/dark-theme.css
file into res\master.css

**Comment by whalley** [comment] 2021-06-10 00:44
Have developed a Dark Theme that I will release shortly... Example as below using some test data

![image](https://user-images.githubusercontent.com/487345/121446407-5514dd80-c98b-11eb-93b3-67db00ef2793.png)

![CleanShot 2021-06-10 at 01 33 53](https://user-images.githubusercontent.com/487345/121446659-edab5d80-c98b-11eb-8dd7-3127a0b7eb20.png)

![CleanShot 2021-06-10 at 01 40 24](https://user-images.githubusercontent.com/487345/121447070-d9b42b80-c98c-11eb-9d9d-0e3b16d961de.png)

**Comment by reddyshyam** [comment] 2021-06-10 04:47
Looks great! Well done! 👍 👌🤝👏

Taking latest snapshot.

**Comment by whalley** [comment] 2021-06-10 07:55
@reddyshyam Try this with the latest build - https://mmex.ipx.co.uk/dark-mode.mmextheme

**Comment by reddyshyam** [comment] 2021-06-10 09:02
> @reddyshyam Try this with the latest build - https://mmex.ipx.co.uk/dark-mode.mmextheme

Thanks @whalley. 👍 Looks awesome on windows too. Font sizes other than homepage are a tad larger. May be fine tuning is required?

Now I only wish the MMex icon can get an overhaul. 🙂

**Comment by whalley** [comment] 2021-06-10 09:43
Sure we can fine tune over time. I’ll get it added as a system theme so we can get more people to test.

**Comment by vomikan** [comment] 2021-06-10 11:01
I'm afraid I'll have to make a separate theme for Windows.

**Comment by whalley** [comment] 2021-06-10 11:23
> I'm afraid I'll have to make a separate theme for Windows.

Whats the issue on Windows? @reddyshyam seemed to imply it works fine on Windows, keen to make sure the themes are platform agnostic if possible.

**Comment by grumpy235** [comment] 2021-06-10 13:33
@whalley Nice theme.
Just downloaded latest master,compiled on Win10 and VS2019 and Account View I only see every other line

![Capture](https://user-images.githubusercontent.com/24897056/121533246-03ef0300-c9f8-11eb-8672-3b73361cd4f2.PNG)

Click on non-visible line, background lightens and text is faintly visible in black

![Capture1](https://user-images.githubusercontent.com/24897056/121533714-73fd8900-c9f8-11eb-8e2c-833e026b0612.PNG)

**Comment by whalley** [comment] 2021-06-10 13:37
You need to:
1. Enable Dark-Mode in Windows 10
2. Start MMEX
3. Enable the dark-mode theme in MMEX
3. Restart MMEX

That at least works in MacOS. The trick is not to switch to dark mode whilst MMEX is running as it will not pick up the change.

Does that solve things?

**Comment by whalley** [comment] 2021-06-10 13:44
@grumpy235 Out of interest what does the default theme look like under dark-mode on Windows.

**Comment by tactilis** [comment] 2021-06-10 14:07
@whalley 
> The trick is not to switch to dark mode whilst MMEX is running as it will not pick up the change.

If you haven't done so already, it would be a good idea to make this clear in the descriptive text of the theme that is displayed in the Theme Manager. Otherwise, I foresee a lot of forum and GitHub issues being raised saying that the theme doesn't work properly

**Comment by whalley** [comment] 2021-06-10 14:14
Should have been clearer. You can switch OS to dark-mode whilst MMEX is running, it is just the fact that once the change is made you need to restart MMEX.

If this is the cause of the issue @vomikan and @grumpy235 have then we can make it clearer.

**Comment by vomikan** [comment] 2021-06-10 16:01
Not all types of apps support the dark theme in Windows. wxWidgets apps do not support it. Here's an example.

![image](https://user-images.githubusercontent.com/6836805/121557982-e9c81b80-ca1d-11eb-91a9-bb9862771506.png)

Only some parts of the applications can be repainted in a dark color. But those elelents who do not understand that the theme is dark globally use a black font.

**Comment by vomikan** [comment] 2021-06-10 16:04
![image](https://user-images.githubusercontent.com/6836805/121558786-a28e5a80-ca1e-11eb-9e8b-6d3462db9f0c.png)

**Comment by grumpy235** [comment] 2021-06-10 17:21
@whalley, followed your instructions and no change get the same as before and recurring transactions shows the same alternate lines visible. Looks like @vomikan is right - the joys of programming for multiple systems :-)

**Comment by valsamis-d** [comment] 2021-06-10 17:26
> @whalley, followed your instructions and no change get the same as before and recurring transactions shows the same alternate lines visible. Looks like @vomikan is right - the joys of programming for multiple systems :-)

I tested it myself (Win 10 64bit w/ dark theme already enabled + MMEX 64bit Portable) and have the same issue as Graham. I only see every other line. The theme will be an awesome addition!

**Comment by whalley** [comment] 2021-06-10 17:33
Just pushed a fix that should help with the list font problem. Not sure if we can fix the wider Windows application frame color issue without a wxWidget update. But at least this will allow somebody to perhaps create a pseudo-dark mode theme for Windows now.

**Comment by vomikan** [comment] 2021-06-10 20:18
Also, please, update submodule
https://github.com/moneymanagerex/themes/commit/4565e969516f4d2ea822274ed927510d10fb23a8

**Comment by grumpy235** [comment] 2021-06-11 06:20
I think I'll stay with colorful for the time being. Changes now make the data visible although a little bright :-) I get the following with and without windows dark mode

![Capture2](https://user-images.githubusercontent.com/24897056/121639856-12cfc700-ca85-11eb-80d3-fee8e68a5a83.PNG)

Still better than when I started with screens when you could have any colour as long as it was green!

**Comment by whalley** [comment] 2021-06-11 11:40
@grumpy235 That coloring looks very odd.  The layout should be as Vomikan posted earlier, are you using the latest build? At least that is how it looks on my Windows test box.
![image](https://user-images.githubusercontent.com/487345/121681008-29d8de00-cab2-11eb-9968-313c03f23621.png)

**Comment by reddyshyam** [comment] 2021-06-11 11:56
> @grumpy235 That coloring looks very odd. The layout should be as @vomikan posted earlier, are you using the latest build? At least that is how it looks on my Windows test box.
> ![image](https://user-images.githubusercontent.com/487345/121681008-29d8de00-cab2-11eb-9968-313c03f23621.png)

Mine looks exactly like this 👆 and I dont use Windows dark mode too.

**Comment by whalley** [comment] 2021-06-11 12:11
> Mine looks exactly like this 👆 and I dont use Windows dark mode too.

Yes the forcing of panel colors works well on machines not using OS dark mode. But looks really pretty in Dark Mode on MacOS.

** dark-mode theme with MacOS 'Light' mode**
<img width="1434" alt="CleanShot 2021-06-11 at 13 05 11@2x" src="https://user-images.githubusercontent.com/487345/121684045-1b8cc100-cab6-11eb-95bb-f9c561cdb39f.png">

** dark-mode theme with MacOS 'Dark' mode**
<img width="1434" alt="CleanShot 2021-06-11 at 13 06 10@2x" src="https://user-images.githubusercontent.com/487345/121684082-29dadd00-cab6-11eb-9804-7d9d390181d3.png">

**Comment by reddyshyam** [comment] 2021-06-11 12:25
> > Mine looks exactly like this 👆 and I dont use Windows dark mode too.
> 
> Yes the forcing of panel colors works well on machines not using OS dark mode. But looks really pretty in Dark Mode on MacOS.
> 
> ** dark-mode theme with MacOS 'Light' mode**
> <img alt="CleanShot 2021-06-11 at 13 05 11@2x" width="1434" src="https://user-images.githubusercontent.com/487345/121684045-1b8cc100-cab6-11eb-95bb-f9c561cdb39f.png">
> 
> ** dark-mode theme with MacOS 'Dark' mode**
> <img alt="CleanShot 2021-06-11 at 13 06 10@2x" width="1434" src="https://user-images.githubusercontent.com/487345/121684082-29dadd00-cab6-11eb-9804-7d9d390181d3.png">

Ah yes, I see the difference but Light mode isn't bad either. 🙂

**Comment by grumpy235** [comment] 2021-06-11 12:46
@whalley - all I did is Git applied your latest fixes under VS2019 and recompiled but I will re-download the master and compile again. As it stands at present if I hover over the white lines then they turn black. My guess is that introducing this may lead to a few questions/moans in the future from Windows users

**Comment by whalley** [comment] 2021-06-11 13:04
@grumpy235 Sounds like you need to update the themes sub module.

**Comment by grumpy235** [comment] 2021-06-11 13:06
@whalley - I guess so still on a learning curve with Git, last source manager I used in anger was Panvalet in the '70s !

**Comment by vomikan** [comment] 2021-06-11 13:57
@grumpy235 
> git submodule update --init --recursive

**Comment by vomikan** [comment] 2021-06-12 13:22
![image](https://user-images.githubusercontent.com/6836805/121777381-66800480-cb9a-11eb-8dee-f2266d4ce9f2.png)

**Closed by vomikan** 2021-06-12 13:22 UTC
Labels: enhancement, theme
