### ISSUE TITLE
Version 1.4.0-alpha.6 randomly crashes on report selection

### ISSUE THREAD

**Issue by avma** [moneymanagerex/moneymanagerex#1802] opened 2018-09-05 11:53 UTC
**Describe the bug**
MMEX randomly crashes on build-in reports selection. Sometimes on first selected report, sometimes after 2nd or 3rd sequentially. 

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Any report' then keep clicking on some other reports
3. See error: mmex crashed generating a 'Debug Report'

**Your OS:**
- [X] Linux Mint 19 Tara "tara"
       Linux 4.15.0-33-generic x86_64
       English (U.S.) (UTF-8)
       1920x1080 24bit 96x95ppi 

**MMEX version:**
- [X] 1.4.0 alpha.6
- [X] development version (git master branch), installed package: mmex_1.4.0-alpha.6-1.bionic_amd64.deb
       Database version: 13 (aes128cbc)
       Git commit: adf6c7bc (2018-09-03)

My best regards
Avi

**Comment by slodki** [comment] 2018-09-05 12:40
This could be duplicate of #1473 or #1612. Both are caused by system packages.

**Comment by vomikan** [comment] 2019-01-11 08:06
I think you should wait till report finished then click next.
Other words - click reports slowly.

**Closed** 2020-12-22 07:45 UTC
Labels: linux, outdated
