### ISSUE TITLE
Can't filter recurring transaction page

### ISSUE THREAD

**Issue by magius96** [moneymanagerex/moneymanagerex#5311] opened 2022-11-04 13:51 UTC
It does not seem to matter what filters I use.  If I apply any filters to the recurring transactions page, it shows nothing.  I have to remove all filters to be able to see anything.

I'm experiencing this in version 1.6.0.

**Comment by magius96** [comment] 2022-11-04 13:53
![image](https://user-images.githubusercontent.com/17016935/199989216-b83367f9-29b9-40cf-a085-3775fb5a66c4.png)

**Comment by magius96** [comment] 2022-11-04 13:53
![image](https://user-images.githubusercontent.com/17016935/199989275-a2ce45d7-9235-47f3-9b1e-894e6c5fe6fa.png)

**Comment by magius96** [comment] 2022-11-04 13:54
Do note from the screenshots how I selected the Payee of BlueBird and get no results,  But clearly, in the first screenshot, you can see that there is in fact a transaction with that payee included in the data set.

**Comment by tactilis** [comment] 2022-11-04 14:06
@magius96 
The ability to filter Recurring Transactions is planned to be removed in the next release. As you have observed, it does not work and is effort to make it do so. See https://github.com/moneymanagerex/moneymanagerex/issues/5281.

I see from your screenshot above, that you are wanting to filter on Payee (BlueBird in your example).

A simple way to find all the transactions with the BlueBird payee is to sort the transactions by payee name (just click on the header of the Payee column) and then scroll to BlueBird.

You can click on a header to sort by any of the other columns too, which will group similar items together.

It would be helpful for us to know how many Recurring Transactions you have in total please.

**Comment by magius96** [comment] 2022-11-04 14:16
I've currently got about 53 recurring transactions programmed in.  I'm in the progress of slowly migrating over from YouNeedABudget.  Realized that recurring transactions don't filter when I was trying to get monthly totals on the recurring for setting up a budget.  The idea was to filter down to a category and enter the total amount in the budget as expected.

**Comment by tactilis** [comment] 2022-11-04 14:40
Filtering to a Payee (or a Category) wouldn't still not have given you the answer you need because you'd still need to total up the monthly total yourself, assuming there are multiple recurring transactions with that Payee or Category.

So sorting by a column is the easiest way to group related transactions.

I can't think of any other way to set up your budget. @whalley might have some thoughts on this.

Thanks for letting us know the number of Recurring Transactions you have. Once you have migrated from YouNeedABudget, will you ever have to go through this setup exercise again - or will it simply be a case of adjusting your now existing budget by the deltas as you add, remove, or change a recurring transaction?

**Comment by magius96** [comment] 2022-11-04 14:55
it's mostly a one-time setup, but yes, I do see needing to adjust the budget ongoing based on changes in the recurring transactions.

**Comment by n-stein** [comment] 2022-11-07 12:06
Maybe there is a case to be made for add an option to automatically include recurring transactions when setting up a new budget?

**Comment by tactilis** [comment] 2022-11-07 12:19
@n-stein
> Maybe there is a case to be made for adding an option to automatically include recurring transactions when setting up a new budget?

If that capability was provided, I think there would be a reasonable expectation from users that any subsequent edits to recurring transactions (i.e. new RTs, modified RTs, deleted RTs) would also be reflected in the budget.

**Comment by n-stein** [comment] 2022-11-07 12:34
> any subsequent edits to recurring transactions (i.e. new RTs, modified RTs, deleted RTs) would also be reflected in the budget

I think that sounds quite useful.

**Comment by tactilis** [comment] 2022-11-07 13:24
> I think that sounds quite useful.

Agreed.

Just highlighting that the UI and implementation will be a bit more complex than for a one-off inclusion of recurring transactions when setting up a new budget.

**Comment by whalley** [comment] 2022-11-07 19:12
If we want to enhance the budgeting functionality to accommodate recurring transactions then it should be raised as a feature request.

For issue I'll mark as duplicate of https://github.com/moneymanagerex/moneymanagerex/issues/5281

**Closed by whalley** 2022-11-07 19:12 UTC
Labels: duplicate
