### ISSUE TITLE
All Transactions panel currencies

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#3209] opened 2021-04-05 19:00 UTC
All values in the panel are presented in the base currency format.

I suggest redoing this to the following view:
![image](https://user-images.githubusercontent.com/6836805/113613508-03ce3200-965a-11eb-8993-d8446055f937.png)

**Comment by vomikan** [comment] 2021-04-21 07:56
Hi Vomikan,

I am on 1.5.1 RC2 and can see this implementation. One issue I see is if there was a cross currency transfer, then the deposited value is showing the 'from' currency rather than the 'to' currency. Hope I made myself clear.

**Comment by reddyshyam** [comment] 2021-04-22 13:43
Hi Vomikan,

I am on 1.5.1 RC2 and can see this implementation. One issue I see is if there was a cross currency transfer, then the deposited value is showing the 'from' currency rather than the 'to' currency. Hope I made myself clear.

Adding this again on the main feature ticket so that the issue is known.

**Comment by vomikan** [comment] 2021-04-22 17:27
It is possible to make the values appear in two cells. But I don't want to load the UI and do unnecessary calculations in this screen.

**Comment by reddyshyam** [comment] 2021-04-23 04:45
> It is possible to make the values appear in two cells. But I don't want to load the UI and do unnecessary calculations in this screen.

I understand, atleast those that are manually filled (both withdrawal and deposit) as in my case?

**Comment by whalley** [comment] 2022-10-18 23:29
This can be closed it has been implemented.

**Closed by whalley** 2022-10-18 23:29 UTC
Labels: enhancement, outdated, fixed
