### ISSUE TITLE
Recurring Transaction Date Paid and Date Due Mix-up

### ISSUE THREAD

**Issue by MarcusGHub** [moneymanagerex/moneymanagerex#3536] opened 2021-05-29 14:24 UTC
MMEX version:
 - [x] 1.5.1
 - [ ] 1.6.x

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

Since I've updated to this version of MMEX, I noticed a slight hindrance when I click 'Enter next Occurence' for a recurring transaction. I get the Date Due field to adjust instead of the Date Paid field. When I modify the Date Due field and submit the transaction, the value for the Date Paid is used instead of the modified Date Due.

![Screenshot_1](https://user-images.githubusercontent.com/8460723/120073696-13b53180-c05f-11eb-9e27-12bbb9506239.jpg)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1.  Go to recurring transaction
2.  Right-click a transaction and click 'Enter next Occurence'
3.  The Date Due field is adjustable instead of the Date Paid field. I think this is in the reverse order.

…

Expected result: The date paid field should be modifiable instead of the date due field. So when I submit the transaction, the correct date is used instead of the planned due date. 

Actual result: I am given the due date to be modified instead of the date paid. 

# Additional information

If you have a backtrace for a crash or a warning, paste it here.

**Comment by vomikan** [comment] 2021-05-29 21:16
#2647

**Comment by MarcusGHub** [comment] 2021-05-31 05:49
Sorry, was searching opened issues.

**Comment by tactilis** [comment] 2021-05-31 08:30
I may be misunderstanding things but I'm not sure that this issue should be closed yet.

The duplicate issue mentioned above, #2647, is already marked as Closed, and _that_ issue mentions #2434, which references #2647, which in turn references #2649...

 _All_ of these issues are marked as Closed but it appears that a problem (or more than one problem) still remains.
 
 #2649 also links to [https://forum.moneymanagerex.org/viewtopic.php?f=10&t=9988](https://forum.moneymanagerex.org/viewtopic.php?f=10&t=9988), which refers to the Date Due/Date Paid mix up among other things.

**Comment by tactilis** [comment] 2021-05-31 08:31
Ah!  I posted at the same time @vomikan re-opened the issue!

**Comment by vomikan** [comment] 2021-05-31 08:31
The case above has been closed.  I need to understand, should I make changes before the release?

**Comment by whalley** [comment] 2021-05-31 22:16
Apologies, not had chance to look yet. Your suggestion to move to 1.5.3 for now seems sensible.

**Comment by tactilis** [comment] 2021-06-01 07:38
@vomikan
> I don't see any inconsistencies.

 _If_ the Recurring Transactions dialog is functioning as intended, then it's clear from the issues raised here and the posts in the forum that there is confusion about how to use this part of MMEX.

I've never had reasons to use Recurring Transactions for my accounts (so far), but looking at Section 13 of the Help pages, I think I would have difficulty understanding exactly how I was supposed to use the dialog.

So, are the problems people are having simply due to an inadequate description of what the dialog is intended to do and how to use it?

**Comment by vomikan** [comment] 2021-06-01 09:58
Unfortunately, the man pages can be lagging behind.My priority task is to correct obvious errors.

**Comment by whalley** [comment] 2021-06-01 18:49
Having reviewed this I would agree with @MarcusGHub and @tactilis that there is an issue here in that the Date Paid / Date Due behavior is misleading and does not work when manually posting the transactions. I have the following observations / suggestions.

For recurring transactions:
- Date Paid = The date the user is requested to enter this transaction 
- Date Due = The date when the Bill or Deposit is due

When manually entering the next occurrence:
- The Date Due should not be amendable
- The Date Paid should be amendable if the user wants to adjust the actual payment date, and this should be used when posting the transaction.

More generally the positioning of the Date Paid and Date Due should be reversed on the dialogs.
![image](https://user-images.githubusercontent.com/487345/120374911-0ecbd880-c312-11eb-9f9f-b9d5f57a5442.png)

**Comment by whalley** [comment] 2021-06-02 18:45
There is also logic present that sets the **Date Paid** to the **Date Due** if Date Paid > Date Due. I.e. you can never post a date paid after the date due. 

I do not see why we should not allow this, but think it would be wise to issue a warning if this is setup as a reoccurring transaction or an attempt to do this is made when entering the next transaction manually.

What do people think?

**Comment by tactilis** [comment] 2021-06-02 21:28
I think it is essential that MMEX allows the user to post a Date Paid after the Date Due as that may reflect the reality of what happened, e.g the payment was due on 1st June but I didn't actually pay it until 3rd June.

My bank statement will show 3rd June, so I'd expect MMEX to be capable of showing the same.

**Comment by whalley** [comment] 2021-06-02 21:43
@tactilis Please pay your bills on time Martin….. 😀

**Comment by tactilis** [comment] 2021-06-02 21:45
Another oddity...

The 'Advance next' button is only active if 'In (x) Days' or 'In (x) Months' is selected.

![image](https://user-images.githubusercontent.com/4060092/120555536-1e6f1e00-c3f3-11eb-80d3-bea8fe2735d8.png)

Why is this? Shouldn't it be active for all repeat periods?

Also, pressing the 'Advance next' button advances the Date Due (i.e. the date on the left) and the Date Paid (on the right). If Date Due is to be not amendable, then this is in conflict.  Should it advance only the Date Paid?   I really don't understand how this dialog is intended to work.

**Comment by tactilis** [comment] 2021-06-02 21:51
@whalley 
>When manually entering the next occurrence:
>  The Date Due should not be amendable
>  The Date Paid should be amendable if the user wants to adjust the actual payment date, and this should be used when posting the transaction.

Under what conditions, if any, would you permit the user to amend the Date Due?

What if I enter a Date Due in the future, OK the dialog, then reopen the dialog and try to change (perhaps correct) the Date Due? Is that allowed?  Is it only not amendable if a payment has been made?  Again, I really don't understand how this dialog is intended to work.

**Comment by tactilis** [comment] 2021-06-02 21:53
@whalley 
> @tactilis Please pay your bills on time Martin…..

Ha ha! Yes.

**Comment by whalley** [comment] 2021-06-02 23:27
> Under what conditions, if any, would you permit the user to amend the Date Due?
> 
> What if I enter a Date Due in the future, OK the dialog, then reopen the dialog and try to change (perhaps correct) the Date Due? Is that allowed? Is it only not amendable if a payment has been made? Again, I really don't understand how this dialog is intended to work.

Yes, the **Edit Recurring Transaction** will allow the full detail to be edited, as below:
![image](https://user-images.githubusercontent.com/487345/120560572-d94eea00-c3fa-11eb-87b8-641d2dae1de0.png)

It is just the **Enter Next Occurrence** that will only allow the transaction detail and payment date to be edited.
![image](https://user-images.githubusercontent.com/487345/120560707-203cdf80-c3fb-11eb-93e7-97f3ab147e5e.png)

Auto posted recurring transactions will be posted on the **Date Paid** date.

Warning if **paid date** > **due date**
![image](https://user-images.githubusercontent.com/487345/120564194-4d40c080-c402-11eb-97f7-d3a81e7d16f5.png)

**Comment by whalley** [comment] 2021-06-02 23:30
> The 'Advance next' button is only active if 'In (x) Days' or 'In (x) Months' is selected.

That is odd, I've never used that feature before, and actually never spotted it before. But it should be consistent! Will fix that.

**Comment by tactilis** [comment] 2021-06-03 06:46
Thanks for the screenshots and the clear explanation @whalley.  I'll have a good play once a build is available.

In the meantime, could we consider whether the terminology used in the context menu and the button tooltips:

![image](https://user-images.githubusercontent.com/4060092/120597305-c78e3680-c43c-11eb-8c30-4bb13efcd5ce.png)

![image](https://user-images.githubusercontent.com/4060092/120598282-ff49ae00-c43d-11eb-9c22-516b45b4d68c.png)

The MMEX capability is called Recurring Transactions and the dialog title is 'Edit / Enter Recurring Transaction', so I don't understand why the menu and tooltip uses the term Bills & Deposit Series. The MMEX Help text uses the term Recurring Transaction only.

I feel that MMEX should say 'New/Edit/Delete Recurring Transaction' on the menu and the first 3 buttons, and 'Enter/Skip next Occurrence' on the other 2 buttons to be consistent with the menu.

**Comment by tactilis** [comment] 2021-06-03 06:50
The Ctrl+1 .. Ctrl+7 and Ctrl +0 keys don't work on Recurring Transactions even though there is the facility to change the colour when doing New/Edit.

**Comment by vomikan** [comment] 2021-06-03 08:52
It would be great to have a function when you press Shift + Skip, roll back the date.

**Comment by whalley** [comment] 2021-06-03 23:11
Can now move back/forward through dates based on recurring pattern.
![image](https://user-images.githubusercontent.com/487345/120723310-68c2ce80-c4c9-11eb-92ca-ed22d53feecc.png)

**Closed** 2021-06-06 19:06 UTC
Labels: bug, duplicate, fixed
