### ISSUE TITLE
macOS: 1.5.17b Crash When Changing HTML Scale Factor

### ISSUE THREAD

**Issue by 2BeeOrNot** [moneymanagerex/moneymanagerex#4786] opened 2022-07-05 16:18 UTC
MMEX version:
 - [ ] 1.5.14
 - [ ] 1.5.15
 - [] 1.5.16
 - [X] 1.5.17 Beta
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [] Windows
 - [X] Mac OSX
 - [ ] Linux 

Working back from current beta to first beta crash started with 07-01-2022 build. Immediately crashes with crash report screen then dies. Did not happen with first two builds. Noticed when I was looking at the nifty popup calendar for macOS users and noticed the too high toolbar height which also started with the 07-01-2022 build. Tried changing scale factor and icon sizes but all I got was a crash when changing scale factor.

![Toolbar_1517_062922](https://user-images.githubusercontent.com/63317977/177371896-7061c940-65f0-4147-862f-e560316af637.jpg)

![Toolbar_1517b_070122](https://user-images.githubusercontent.com/63317977/177371917-e82bfb30-1aec-49b3-a5c8-55bbd318bfda.jpg)

**Comment by tactilis** [comment] 2022-07-05 16:40
I am not able to reproduce the crash on Windows

**Comment by whalley** [comment] 2022-07-05 18:14
@tactilis Good spot, it is in a piece of code that handles a needed MacOS workaround. Inadvertently changed as part of this https://github.com/moneymanagerex/moneymanagerex/commit/5a1d69361eb8fa529c1ce9468bf8785f8ace5870. Fixed now.

**Comment by whalley** [comment] 2022-07-05 19:31
@2BeeOrNot New MacOS beta uploaded https://mmex.ipx.co.uk/

**Comment by 2BeeOrNot** [comment] 2022-07-05 20:43
No crash in today's beta build. Is there a reason the toolbar is so high? it started with the July 1st build. In the previous two beta builds it was not so high, like in 1.5.16.

**Comment by tactilis** [comment] 2022-07-05 21:11
Set the Toolbar Icon Size to Normal

![image](https://user-images.githubusercontent.com/4060092/177417124-0bbe994e-bec3-4e0a-bc58-baa6c893da19.png)

**Comment by tactilis** [comment] 2022-07-05 21:18
...although looking at the icons, they are the correct size but are displayed in a toolbar that is too tall.

Try setting the size to Small, exiting and restarting MMEX, then set to Normal, exit and restart.

Does that fix it?

**Comment by whalley** [comment] 2022-07-05 21:20
Yes think @vomikan made some changes in this area around these settings and defaults. Just resetting fixed it.

**Comment by vomikan** [comment] 2022-07-06 14:28
> Yes think @vomikan made some changes in this area around these settings and defaults. Just resetting fixed it.

I did nothing regarding this.

**Comment by whalley** [comment] 2022-07-06 14:49
> > Yes think @vomikan made some changes in this area around these settings and defaults. Just resetting fixed it.
> 
> I did nothing regarding this.

Oh, OK I'll do a bit of digging as something affect my toolbar height also and I needed to reselect the icon size.... Not a major issue but may annoy users...

**Comment by whalley** [comment] 2022-07-06 18:40
I've found some oddity with respect to the window positioning that seems to cause the odd toolbar behaviour. I'll raise another issue for this as it will require further investigation and possibly referring to the wXWidgets dev team.

**Closed** 2022-07-06 18:55 UTC
Labels: bug, fixed
