### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by Speigy** [moneymanagerex/moneymanagerex#2324] opened 2020-02-21 11:07 UTC
> Please follow these tasks before submitting new bug:
> 1. Use Help->Check for Updates in MMEX to get latest version - your problem can be fixed already. **Have done that.**
> 2. Search https://github.com/moneymanagerex/moneymanagerex/issues?q=is:issue. **No results.**
> 3. **This not in help!** Use Help->Report a Bug in MMEX if possible 
> 6. Included steps to reproduce your issue, attach screenshots where appropriate.

I am running Version 1.3.3 (DB v7) on a windows 10 PC.
First, for no obvious reasons the database runs very slow.
On opening the program there is a long delay before the program opens.
Selecting an account - slow to open.
Entering a transaction, the debit or credit, once entered, balance is slow to adjust to new credit or debit addition.
**Transaction filter:-**
Attached are screenshots.
I selected an active account with several transactions. The report shows no entries!

Selecting some reports, for example 'Monthly summary of account', shuts the program down.
Reports are very slow to respond.
![Trans Filter](https://user-images.githubusercontent.com/39367770/75028886-0216ce80-5499-11ea-85b7-092b95ba930c.jpg)
![Trans-Result](https://user-images.githubusercontent.com/39367770/75028896-0642ec00-5499-11ea-9dfe-fd0e2bb64cd7.jpg)

alasdairnolan@btinternet.com (alas)

**Comment by vomikan** [comment] 2020-02-21 11:10
Please try to redefine the dates. It was a bug regarding this.

**Comment by siowena** [comment] 2020-02-24 12:33
"Selecting some reports, for example 'Monthly summary of account', shuts the program down."

Re this issue - it's likely you have one or more Assets with associated Asset Accounts.

If not removing the Asset solves the Monthly Summary of account crashing.

I've managed to re-add the Asset, but select No to creating an Asset Account when prompted.

**Comment by vomikan** [comment] 2020-03-01 14:47
I can't reproduce this issue.
@siowena could you create DB from scratch with this issue with bug included?

**Comment by siowena** [comment] 2020-03-01 19:23
Hi @vomikan - take a look at #2288 

My comment on #2288 (https://github.com/moneymanagerex/moneymanagerex/issues/2288#issuecomment-568773260) has some files attached.

This seems to be resolved in 1.4.x if I upgrade the DB.

Let me know if you need anything else.

**Comment by vomikan** [comment] 2020-03-02 09:08
I was testing the file attached to the case 2288 with mmex v.1.3.4.
Working. Seems the bug has gone.

**Closed** 2020-03-14 16:43 UTC
Labels: bug, fixed
