### ISSUE TITLE
Transaction Report Filter does not work with Split Transaction Notes

### ISSUE THREAD

**Issue by stardust7951** [moneymanagerex/moneymanagerex#5752] opened 2023-03-13 09:27 UTC
MMEX version:
1.6.3  Windows

# Description of the bug

Everything is in the title, when I do a search on an existing Split Tansaction Note there is nothing in the Transaction Report.

# Reproduction

Is the bug reproducible? 
 - [x] Always

**Comment by renato-mmex** [comment] 2023-03-13 09:57
Please use the current version 1.6.3
https://github.com/moneymanagerex/moneymanagerex/releases

**Comment by stardust7951** [comment] 2023-03-13 10:30
I'm sorry but I made a mistake in writing my first message.

**I'm using version 1.6.3** :

Money Manager Ex
• Version: 1.6.3 64 bit
• Based on: Jan 31 2023 12:09:35
• Database version: 17 (aes128cbc)
• Git commit: 48d8562 (2023-01-31)
MMEX uses the following products:
• wxWidgets 3.2.1 (wxMSW 10.0)
• wxSQLite3 4.9.1 (SQLite 3.40.0)
• RapidJSON 1.1.0
• Lua 5.3.5
• libcurl/7.82.0-DEV Schannel
• gettext 0.19.8.1
• apexcharts.js
Developed with:
• CMake 3.16.2
• MSBuild 15.9.21.664
• Microsoft Visual Studio 15.0
• Microsoft Visual C++ 19.16.27035.0
• Windows SDK 10.0.14393.0
Started on:
• Windows 11 (build 22621), 64-bit edition
• French (France) (windows-1252)
• 2560x1440 32bit 96x96ppi

**Comment by vomikan** [comment] 2023-03-13 14:26
I can't reproduce this issue.

**Comment by n-stein** [comment] 2023-03-13 14:53
I am able to reproduce on the current 1.6.4 Beta build. Here is a transaction with a split note "TX29 Split 1 note":

![image](https://user-images.githubusercontent.com/16599929/224737390-2e2c68db-62bc-47be-9bf8-3cbeff63a35b.png)

Transaction filter for Notes TX29*:

![image](https://user-images.githubusercontent.com/16599929/224737786-110f946e-3699-48aa-b1df-502a25797dda.png)

Transaction report is empty:

![image](https://user-images.githubusercontent.com/16599929/224738336-2cc4817d-5d9b-425a-9567-0416e7180728.png)

**Comment by n-stein** [comment] 2023-03-13 16:58
If the "Notes" box is checked but the text field is left blank, should a transaction be returned only if the main transaction and ALL of its splits have no note, or if at least ONE split has no note?

**Comment by tactilis** [comment] 2023-03-13 17:24
> If the "Notes" box is checked but the text field is left blank

On WIndows, at least, you cannot have an empty Transaction Filter Notes text field if the 'Notes' box is checked. The text field always contains an asterisk, so that should be matching zero or more characters in the main or split notes and should therefore return all transactions.

**Comment by vomikan** [comment] 2023-03-13 17:58
> The text field always contains an asterisk

That's not so. If the field is left empty, transactions with empty notes will be searched.

With the advent of split, it has become somewhat more difficult to make the correct search logic.

**Comment by vomikan** [comment] 2023-03-13 18:10
@n-stein I think this fix is incorrect https://github.com/moneymanagerex/moneymanagerex/pull/5754/files

it would be correct to make a separate transaction for each split transaction, and only then to filter it.
```
    for (const auto& tran : Model_Checking::instance().all())
    {
    
      here should be 
            for (const auto& split : full_tran.m_splits)
            {
                 tran = split
            }
      
      
        if (!dlg.get()->mmIsRecordMatches(tran, ~splits~)) continue;

```

**Comment by tactilis** [comment] 2023-03-13 18:25
>> The text field always contains an asterisk

> That's not so. If the field is left empty

I find it impossible to create an empty field empty.

In this video I do:
1. Check the Notes box.
2. Attempt to delete the asterisk - you cannot, it is always shown.
3. Type a character, then delete it. The asterisk reappears.

https://user-images.githubusercontent.com/4060092/224794079-592aa428-0694-4b20-98a2-50e83f4af0bf.mp4

The asterisk means 'match zero _or more_ characters' but it seems that is not what is happening. Perhaps the asterisk should not be shown.

**Comment by n-stein** [comment] 2023-03-13 18:33
The asterisk is a "Hint" for the notes field, meant as a suggestion of what types of data can be entered there. The field itself is blank. I agree that it is confusing and should be changed.

**Comment by n-stein** [comment] 2023-03-13 18:40
> it would be correct to make a separate transaction for each split transaction, and only then to filter it.
> 
> ```
>     for (const auto& tran : Model_Checking::instance().all())
>     {
>     
>       here should be 
>             for (const auto& split : full_tran.m_splits)
>             {
>                  tran = split
>             }
>       
>       
>         if (!dlg.get()->mmIsRecordMatches(tran, ~splits~)) continue;
> ```

@vomikan It seems you are suggesting we implement #5465. Is that right?

**Comment by n-stein** [comment] 2023-03-13 18:53
Let me rework it, I'll implement #5465 as well.

**Comment by n-stein** [comment] 2023-03-14 17:02
Also, no more asterisk
![image](https://user-images.githubusercontent.com/16599929/225081788-932045de-f6e3-4550-98e7-75f19f8dc1ad.png)

**Closed** 2023-03-15 08:56 UTC
Labels: bug
