### ISSUE TITLE
Where to translate?

### ISSUE THREAD

**Issue by ikkoup** [moneymanagerex/moneymanagerex#1791] opened 2018-09-01 07:13 UTC
Hi,

I'd like to ask about where should I start translating MMEX? on Crowdin as mentioned on Android's about menu or launchpad or I just edit the PO file locally on my computer? And why are you using ar_SA as a locale for Arabic language instead of just "ar"?
I'm looking for translating both the Android and Desktop apps and the Help files too.

The language is Arabic.

**Comment by slodki** [comment] 2018-09-01 19:31
Duplicate of #1345?
I edit .po files with a text editor then post the changed file as PR using GitHub/git.

You are right - we have a file with ar_SA inside but with ar filename. I know nothing about Arabic and differences between ar and ar_SA. Can you confirm it uses generic ar language and we can change ar_SA to simple ar?

**Comment by ikkoup** [comment] 2018-09-13 06:32
Here's a little update to the Arabic translation, I revamped the old translation completely and re-did it again because it was 90% machine translation that doesn't make sense.
Also, I translated about 30% of the strings and still going strong. But it won't be useful so much because the UI needs RTL support to properly deal with strings (%s for example).

A little off-topic: updated the android translation too, but the Arabic layout is a total mess. Will make a detailed issue later in the android's repo.
-
Here's a link to the translation file, don't know how to make a pull request, sorry.
[Dropbox Link](https://www.dropbox.com/s/vfylpeihsva8xa4/arabic.po?dl=0)

**Comment by slodki** [comment] 2018-09-13 08:33
I'll update mmex sources with your file - just publish it somewhere.
I've already noticed some problems with RTL support in wxWidgets - see #115 for result mixing LTR and RTL in mmex UI.

We can prepared bug report for RTL in wxW project - but I cannot give examples as I don't use RTL.

**Comment by ikkoup** [comment] 2018-09-13 10:28
Published it in #1814 . I hope this is the right way to do a PR.

**Comment by vomikan** [comment] 2018-10-25 16:13
Source file updated: The file mmex.pot in project MMEX was updated with new content

**Comment by slodki** [comment] 2019-01-09 21:53
#1913 ?

**Comment by vomikan** [comment] 2019-01-10 06:30
@avma Avi, I am testing poeditor.com service. And I like it.
I've moved Hebry yranslation to it.

**Comment by vomikan** [comment] 2019-01-27 09:46
https://crowdin.com/project/moneymanagerex
Best service for now.

**Closed by vomikan** 2019-01-27 09:46 UTC
Labels: i18n, question
