### ISSUE TITLE
Allow more than 10 saved transaction filters

### ISSUE THREAD

**Issue by cmbarbu** [moneymanagerex/moneymanagerex#4250] opened 2022-03-09 19:49 UTC
# Description of the feature

Currently, up to 10 transaction filter settings can be saved. This limit could be increased (or even removed altogether).

I sometimes discover new filter settings that I would like to save for future reference, but I am unable to save them since all available "slots" are already taken.

![mmex-feature-trans-filter-settings](https://user-images.githubusercontent.com/1184162/157521762-98de65b5-f9f2-48c1-86d9-59ce21706781.PNG)

To prevent the drop-down menu from becoming too large, a scrollbar could be added (however, I am not sure whether this is supported by wxWidgets).

**Comment by vomikan** [comment] 2022-05-15 08:40
@cmbarbu Could you please check out the new functionality?

https://ci.appveyor.com/project/moneymanagerex/moneymanagerex/builds/43545863/job/28ohv9xwc60ymagc/artifacts

**Comment by whalley** [comment] 2022-05-15 23:50
@vomikan 

Initially I can no longer select accounts:
![CleanShot 2022-05-16 at 00 43 29](https://user-images.githubusercontent.com/487345/168499395-9371d24d-37f5-4153-9802-97be5af81720.png)

I can no longer select Payees:
![CleanShot 2022-05-16 at 00 44 06](https://user-images.githubusercontent.com/487345/168499426-7e83f824-b796-4f7e-95ff-2544b53c4763.png)

**However, after saving my first Filter I can then select Accounts and Payees.**
![CleanShot 2022-05-16 at 00 46 58](https://user-images.githubusercontent.com/487345/168499569-7b08bd7d-7a5d-4f64-8d01-8f417a368d8b.png)

If I delete my filters, exit the dialog and go back in I am again unable to select accounts or payees.

One further thing. I cannot update an existing filter without removing and re-creating it.

**Comment by vomikan** [comment] 2022-05-16 10:29
I confirm this bug. Suddenly. I will fix it right after refactoring the Navigation Panel.

**Comment by whalley** [comment] 2022-05-16 19:51
> One further thing. I cannot update an existing filter without removing and re-creating it.

I can't see a fix for this, is this intentional? Perhaps a warning if an existing filter name is entered before overwriting? 

Also I think we should pop a warning when deleting a filter, asking for user confirmation.

What do you think?

**Comment by whalley** [comment] 2022-05-16 20:00
Also noted that new filters are not displayed or removed from the navigation menu (i.e. it is not refreshed) until the transaction report is run. 

E.g. If I create a filter and save a filter then press cancel the filter is created but is not accessible from the navigation manu until I restart app or run a report.

E.g. If I create and run filters they appear in the navigation menu. If I then delete each filter and press cancel when all are deleted the navigation menu is not updated. If I then restart the app they are gone (same as if I run another transaction report).

**Comment by vomikan** [comment] 2022-05-16 20:21
> > One further thing. I cannot update an existing filter without removing and re-creating it.
> 
> I can't see a fix for this, is this intentional? Perhaps a warning if an existing filter name is entered before overwriting?

This has not been implemented yet.



> Also I think we should pop a warning when deleting a filter, asking for user confirmation.
Good idea.




> Also noted that new filters are not displayed or removed from the navigation menu (i.e. it is not refreshed) until the transaction report is run.
I cannot reproduce this and the following points. I will look more closely.

**Comment by whalley** [comment] 2022-05-16 22:26
Not sure what stage you are at, but at present:

1. I can no longer save any settings, when I press the save button it does nothing.
2. I can click the erase button with no settings available and it gives me the warning. I would have expected the delete button to be unavailable in this instance.
![CleanShot 2022-05-16 at 23 23 08](https://user-images.githubusercontent.com/487345/168692108-a1047e9f-56d8-4cf3-bebc-769d33aa04c6.png)

If you want me to hold off testing until you have something stable then let me know.

**Comment by whalley** [comment] 2022-05-17 13:50
@vomikan  Thanks. This is looking really good and very useful addition to the app.  Yes, looking stable I'll do some more testing and look to help tidy up any issues or make improvements as appropriate...

**Comment by whalley** [comment] 2022-05-17 19:17
Couple of points I have noticed. We may wish to create some of these as future features.

1. No ability to order the list of filters, the order can sometimes change when adding/deleting filters
2. Would be good to have the ability to invoke Edit/Rename/Delete via right-click menu on the navigation menu
3. The date range settings don't seem to work when the filter is invoked from the navigation menu. I get a date range of 
```
From 2922-89-4- till 2922-89-4-
User specified start day: 1634758764
```

**Comment by vomikan** [comment] 2022-05-17 19:34
Saving a list with no size limit, I conceived as recent files. The element that is added is placed at the top of the list. LIFO.
I agree that sorting would not be superfluous, but it will require additional efforts. This can be postponed for later.

The date is saved as a phrase. But I don't see any processing of this value.
```"FROM": "Since 30 days ago"```
I suggest creating a separate bug report.

**Comment by vomikan** [comment] 2022-05-17 20:45
> 3\. The date range settings don't seem to work when the filter is invoked from the navigation menu. I get a date range of

I can't resolve this puzzle :(

**Comment by whalley** [comment] 2022-05-18 13:26
> > 3. The date range settings don't seem to work when the filter is invoked from the navigation menu. I get a date range of
> 
> I can't resolve this puzzle :(

It had me scratching my head also... Until I noticed that the m_begin_date / m_end_date strings being used rather than local variables.

**Comment by vomikan** [comment] 2022-05-18 13:46
My test case:
```Label: Number 1, From: Start of Financial Year, Number: 1 ```

![image](https://user-images.githubusercontent.com/6836805/169054632-e2836603-c17d-4f6c-aabe-99c708e287fb.png)

**Comment by vomikan** [comment] 2022-05-18 15:36
@whalley I think I've found a solution.

**Closed** 2022-05-20 10:37 UTC
Labels: enhancement, fixed

**Comment by cmbarbu** [comment] 2022-06-20 18:45
Sorry for the late reply, I just got around to testing the new beta version. Looks great, thank you very much for your hard work!
