### ISSUE TITLE
Copy & Paste into "Amount" field with "$" in the pasting data causes crash

### ISSUE THREAD

**Issue by tiker** [moneymanagerex/moneymanagerex#557] opened 2015-08-31 00:43 UTC
Copying money amounts which include the $ and pasting into a new transaction causes the program to crash.  Also tested with characters such as "dfasdfsd".

While these are not valid characters to add to the "Amount" field, there should be something that validates the data to prevent the application from crashing.

**Comment by vomikan** [comment] 2016-01-08 14:43
I can't reproduce this issue.

**Comment by tiker** [comment] 2016-01-08 14:58
I just tried it again with the latest version 1.2.4 on Win7 x64 (portable version) and the problem still occurs.

I created a new mmb file
New account named test
Currency = CAD
In notepad, I typed $1234.42
Copied the notepad content to the clipboard
Created a new transaction in MMEX
Pasted the clipboard to the withdrawal value
Click OK
Got the following results:
http://imgur.com/5YsWdaH

**Comment by vomikan** [comment] 2016-01-08 17:38
Can't reproduce it anyway
![sample](https://cloud.githubusercontent.com/assets/6836805/12204816/b2296354-b647-11e5-90b5-375e70923c15.png)

**Comment by dwrj87** [comment] 2016-01-08 17:49
I can't reproduce this either

**Comment by vomikan** [comment] 2016-01-28 06:50
Closed as duplicate issue.
https://github.com/moneymanagerex/moneymanagerex/issues/659

**Closed by vomikan** 2016-01-28 06:50 UTC
Labels: bug, help wanted, invalid
