### ISSUE TITLE
Unexpected character in NUMBER token: ,

### ISSUE THREAD

**Issue by ul** [moneymanagerex/moneymanagerex#773] opened 2016-03-23 10:15 UTC
This error appears when I try to open “My Usage” report. Other reports are opened fine. I use USD, RUB and UAH accounts.

Linux cybercraft 4.3.6-1-ck #1 SMP PREEMPT Fri Feb 19 20:05:29 EST 2016 x86_64 GNU/Linux
MMEX 1.2.6

**Comment by guanlisheng** [comment] 2016-06-29 21:43
i am closing this issue since i can not reproduce it.

**Comment by ul** [comment] 2016-07-09 11:45
I believe it's a locale-specific issue. But I can't figure out what specific locale setting interfere MMEX expectancy: my system locale is en_US, but in KDE Russian language is set.

**Comment by J316** [comment] 2016-10-10 16:47
Hi @guanlisheng. I'm getting this error too. My locale is en_US, but everytime I open the application I get an error saying "locale 'en_GB' cannot be set." Opening the details of the error I also get a warning sign saying "Cannot set locale to language "English"." The displayed language is English though. I also put letters and spaces in the "number" field, because I use it to annotate the transaction's medium. I hope this helps to reproduce this error.

**Comment by Beast141** [comment] 2016-10-14 11:17
After just compiling and installing mmex 1.2.7 stable version on Ubuntu 16.04.
I am having the same issue whenever i click on My Usage report, it throws that error, and then my db disappears, then i have to close mmex and re-open my db.

**Comment by J316** [comment] 2017-03-07 21:36
@guanlisheng I confirm this error persists in version 1.3.2

**Comment by slodki** [comment] 2017-06-27 21:52
@guanlisheng I can confirm this bug exist in latest git master build. Please reopen this issue.

**Closed** 2018-03-14 19:21 UTC
Labels: bug, duplicate

**Comment by slodki** [comment] 2018-03-29 11:48
@ul @J316 @2SI3NX Please test [fixed build](https://github.com/slodki/moneymanagerex/releases/tag/test2)
