### ISSUE TITLE
Currency history ignored in transaction report and home page

### ISSUE THREAD

**Issue by keinejiang** [moneymanagerex/moneymanagerex#1183] opened 2017-06-06 09:01 UTC
- Check OS
  - [x] Windows
  - [ ] Mac OSX
  - [ ] Linux 
- Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

Calculate currency twice. Steps:
1. Create a database using a currency, eg. USD;
2. Create a bank account in the database using another currency, eg, HKD;
3. Create a new withdrawal transaction under the account, eg, HK$1000;
4. Update currency online;
5. Use report tool "Transaction Report" to export it by using "type=withdrawal";

Now, you can see that the "Amount" in report have error value.

**Comment by slodki** [comment] 2017-07-25 17:38
Only initial value (first stored in db) for currency value is used for transaction.
Next updates for currency values (online or manual) are ignored in existing or newly created transactions.

<hr><small><b>Version</b>: 1.4.0-Alpha.1 ⬥ db 7 ⬥ git 7e43643 (2017-07-24)<br><b>Libs</b>: wxWidgets 3.1.0 (wxMSW 6.3) ⬥ wxSQLite3 3.4.0 (SQLite 3.14.1) ⬥ Mongoose 6.5 ⬥ Lua 5.2.4<br><b>Build</b>: Jul 24 2017 20:28:26 ⬥ Microsoft Visual Studio 1900 ⬥ CMake 3.8.2 ⬥ GNU Make <br><b>OS</b>: Windows 8.1 (build 9600), 64-bit edition Little endian ⬥ Polish windows-1250 ⬥ 1680x1050x32bit 98x98ppi</small>

**Comment by vomikan** [comment] 2018-03-19 15:00
I can't reproduce this in 1.4.0

![image](https://user-images.githubusercontent.com/6836805/37603369-74c0e148-2b9f-11e8-829f-d5ccb59ee583.png)

**Comment by slodki** [comment] 2018-03-21 10:50
130 zł should be reported here:

![mmex1183cur](https://user-images.githubusercontent.com/3155552/37705792-73bd3684-2cfd-11e8-8a21-8532c3f9f021.png)
![mmex1183rep](https://user-images.githubusercontent.com/3155552/37705796-77440bb6-2cfd-11e8-9714-b491f8437471.png)

**Comment by slodki** [comment] 2018-03-21 10:54
We should remove Conversion to Base Rate from currency IMHO. Then use 1:1 ratio if history is empty. And auto-generate last entry in history window with *before* and *1* values.

User can define base rate as old history entry.

**Comment by slodki** [comment] 2018-03-21 10:57
Same problem with home page summary
![mmex1183home](https://user-images.githubusercontent.com/3155552/37706228-05ce1e3e-2cff-11e8-9782-0e65dff0133e.png)

**Comment by vomikan** [comment] 2018-03-21 14:18
I don't see a problem here. In the sample above I have 100$ and today it is 300zl.
Before it was 130zl but now it does not metter.

**Comment by slodki** [comment] 2018-03-21 22:54
Does user have to manually update *Conversion to Base Rate* field each time he downloads currency rates from internet?

Yesterday it was $100=120zł and today it's $100=130zł. 3.00 ratio was entered few months ago when database was created and after that currency rates were updated multiple times - as seen in history panel.

**Comment by gabriele-v** [comment] 2018-05-06 14:31
Will be fixed with https://github.com/moneymanagerex/moneymanagerex/issues/1541

**Closed** 2018-05-10 16:25 UTC
Labels: bug
