### ISSUE TITLE
Items in Navigation keep disappearing in Ubuntu and MacOS

### ISSUE THREAD

**Issue by alex-gee** [moneymanagerex/moneymanagerex#658] opened 2016-01-23 10:18 UTC
Hi!
I noticed that Items in the Navigation drawer keep disappearing if I click on them.

I recorded a Screencast on both Platforms to show you the effect:
[Demo Ubuntu 14.04 - MMEX 1.2.4](http://sendvid.com/mij5bi88)
[Demo MacOS 10.10.5 - MMEX 1.2.3](http://sendvid.com/q5dknt5c)

greetings!

**Comment by vomikan** [comment] 2016-01-23 15:08
https://sourceforge.net/p/moneymanagerex/bugs/615/

https://github.com/moneymanagerex/moneymanagerex/pull/516

**Comment by ipa-frm-ag** [comment] 2016-01-23 21:40
sorry about the duplicate. will research better next time.

**Comment by omalleypat** [comment] 2016-03-17 14:09
This will stop if you turn off the News option in the Preferences.

**Comment by vomikan** [comment] 2016-03-17 14:19
It should be nonsense for 1.3.0 because news downloaded only at startup onece.

**Comment by omalleypat** [comment] 2016-03-17 14:20
Correct - this is not an issue in master branch right now.

**Comment by J316** [comment] 2016-10-10 17:29
It occurs even with news disabled. It's kind of random, to me occurs sometimes when I add a transaction, then by hiding and expanding the tree it returns to normal, but when error #773 happens it goes blank and the only way to have it back is to close and reopen the application.

**Comment by slodki** [comment] 2017-05-06 13:40
How to reproduce (always) on latest git master and linux:

1. Opening database
- start mmex
- select **Open Existing Database** from startup pop-up
- select saved file
- main screen is loaded with navigation tree expanded but **only Home Page displayed**. Clicking on empty space below renders selected item or colapse/expand tree fill render all items.
- selecting **Open Last Opened Database** opens main window with navigation tree rendered **properly**
2. Adding account
- expand navigation tree to display subitems
- select accounts->new account rom menu
- complete the wizard
- accept account parameters in Edit account dialog using OK
- after clicking OK all subitems below Home Page are not visible

**Comment by danielrempel** [comment] 2018-08-17 13:51
Hey, I've got it fixed, but can't test on neither Windows nor Mac

**Comment by danielrempel** [comment] 2018-08-18 06:50
- [x] budget entries disappeared on choosing on of them - fixed in f57eed2 (all the previous ones are renames pushed with -f flag)
- [x] all navigation items disappeared upon adding/removing budget entry - fixed in b56dc24

**Closed** 2018-08-19 12:28 UTC
Labels: bug, help wanted, linux, mac
