### ISSUE TITLE
Spurious column sort-order indicator shown when double clicking on Stock Portfolio

### ISSUE THREAD

**Issue by tactilis** [moneymanagerex/moneymanagerex#4978] opened 2022-08-26 14:34 UTC
MMEX version:

 - [x] 1.5.20 Beta

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

Double clicking on a stock portfolio in the navigation tree causes a spurious sort-order indicator to be added to the gain/loss icon column.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

Double click on a stock portfolio in the navigation tree.

Expected result:

Nothing should happen.

Actual result:

A spurious sort-order indicator is added to the gain/loss icon column.

Note that:
Clicking on the column heading does not affect it.
Double clicking on stock portfolio in the navigation tree again does not affect it.
Refreshing the list by clicking on the Home Page and then returning to the stock portfolio clears the unwanted sort-order indicator.

In the video, each time I move the mouse pointer to the stock portfolio, I am double clicking.

https://user-images.githubusercontent.com/4060092/186925333-d953dc21-d297-4e47-b58d-44c9ca9d0691.mp4

Although this bug appears to have no detrimental effects, it points to some erroneous code that should be fixed; firstly by finding out **_why_** a double click creates a second sort-order indicator and fixing that code path, and then (maybe) preventing a double click event.

# Additional Information

Double clicking on any other account type in the navigation tree does **not** create a spurious sort-order indicator in the corresponding transaction list.

**Comment by whalley** [comment] 2022-08-30 13:26
@tactilis Can you confirm that the issue is fixed and if so feel free close the issue.

**Comment by tactilis** [comment] 2022-08-30 13:59
Confirmed fixed.  Thanks

**Closed** 2022-08-30 13:59 UTC
Labels: bug, fixed, stocks-shares
