### ISSUE TITLE
Dispatching to Wayland

### ISSUE THREAD

**Issue by marco90a** [moneymanagerex/moneymanagerex#6838] opened 2024-08-19 23:31 UTC
MMEX version:
 - [ ] 1.7.0
 - [X] 1.8.0
 - [ ] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Operating System:
 - [ ] Windows
 - [ ] Mac OSX
 - [x] Linux (fedora 40)

# Description of the bug
I use the version installed via flatpak.
After entering the login password it goes into exception and exits the program
```Gdk-Message: 01:22:41.705: Error 71 (Errore di protocollo) dispatching to Wayland display.```

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

**Comment by PMaff** [comment] 2024-10-10 18:46
I am not sure what you mean by "entering the login password"?
Do you mean database encryption password?

**Comment by marco90a** [comment] 2024-10-10 20:56
Yes I am referring to the database encryption password

**Comment by marco90a** [comment] 2024-10-11 09:33
I built and installed version 1.8.1 but it doesn't recognize the password to decrypt the database

**Comment by vktr2b** [comment] 2024-10-22 10:47
I have an unencrypted database and I have the same issue(it's not related to DB being encrypted or not )
The issue is affecting only Nvidia GPU users as I have noticed (_what a surprise_) a temporary workaround is to start mmex with this command:
`WEBKIT_DISABLE_DMABUF_RENDERER=1 mmex`

`GTK4 4.16.2` should have fixed it but on `GTK4 4.16.3` and it's still experiencing it, until it's fixed by upstream try to use the workaround

**Comment by marco90a** [comment] 2024-10-22 11:06
Thanks I did as you indicated it works correctly.

**Closed** 2024-10-24 12:13 UTC
Labels: bug, linux, solution found
