### ISSUE TITLE
Budget plan with multiple currencies

### ISSUE THREAD

**Issue by MarekLe** [moneymanagerex/moneymanagerex#1285] opened 2017-08-11 10:12 UTC
I found a BUG in budgeting window. I have some accounts in PLN (main currency) and some in CHF. 'Budget setup' window summarizing values in PLN and CHF without any convertion.
![obraz](https://user-images.githubusercontent.com/30925920/29209282-f94210b4-7e8d-11e7-9b3a-3d3e42e89072.png)

In this situation budgeting in MMEX is dificult to use... It's wrong... and confusing.

Your OS:
- [x] Windows
- [ ] Mac OSX
- [ ] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

MMEX version:
- [ ] 1.4.x
- [x] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by vomikan** [comment] 2018-03-20 15:03
I think all values are in base currency. Just update currency rates in a Currency Manager.

**Comment by slodki** [comment] 2018-03-21 23:07
Duplicate of #1183 

This is not working as you can see below. Default 1:1 ratio is used even if history is updated.

![mmex1183bud](https://user-images.githubusercontent.com/3155552/37742124-8567dc92-2d64-11e8-9547-913fb7b69d42.png)

**Closed** 2018-05-10 16:25 UTC
Labels: bug
