### ISSUE TITLE
Quick category entry using ":" to autocomplete

### ISSUE THREAD

**Issue by n-stein** [moneymanagerex/moneymanagerex#5234] opened 2022-10-27 23:45 UTC
# Description of the feature

Suggested by @ovari.

Allow users to quickly enter categories by utilizing ":" to jump to the end of the autocomplete string. This allows them to type in the minimum number of characters to select the category & subcategory.

# Use cases

Particularly useful in conjunction with #1477.
For example, suppose I have the category Income:Investment Income:Dividends:Qualified.
This could be entered by typing "i:i:d:q" (minimally, if they are all the first alphabetically).

**Comment by n-stein** [comment] 2022-10-28 00:02
PR #5235 entered. Works well on Windows, needs to be tested on MacOS.

**Comment by ovari** [comment] 2022-10-28 01:01
Is there a link to a deb file which works with Linux Mint 21? Thank you

**Comment by ovari** [comment] 2022-10-28 02:10
> Allow users to quickly enter categories by utilizing ":" to jump to the end of the autocomplete string. This allows them to type in the minimum number of characters to select the category & subcategory.

Sorry for not explaining clearly. The ":" jumps to the end of the autocomplete string _and_ automatically highlights the first listed subcategory.

"Enter" automatically competes the string.

As characters are typed, the category that contains that string is highlighted.

Below is a screencast of Quicken 2004 autocomplete:
1. "inv:div" then "Enter" to produce **Investment:Dividends**
2. "inv:div:" then "Enter" to produce **Investment:Dividends:Franked** (notice that "f" was not needed as **Franked** was the first string in the list
3. "inv:d:p" then "Tab" to select to produce **Investment:Distributions:PP** and move to the next field (Memo)

https://user-images.githubusercontent.com/17465872/198452864-17f28d89-d4bb-4802-85f7-4df208cb7017.mp4

Thank you once again.

**Comment by n-stein** [comment] 2022-10-28 02:40
With this change all of what you describe now happens automatically due to the way autocomplete works, at least on Windows.

**Comment by n-stein** [comment] 2022-10-28 04:01
For Linux Mint 21 you want the Ubuntu 22.04 package 
https://output.circle-artifacts.com/output/job/d53ff13c-c0ff-446d-b3f7-51cc43573bc9/artifacts/0/tmp/artifacts/mmex_1.6.1-Beta.1-Ubuntu.22.04.jammy_amd64.deb

Make sure you copy your database before using as it will auto upgrade it to v16.

**Comment by tactilis** [comment] 2022-10-28 07:34
@n-stein 
> With this change all of what you describe now happens automatically due to the way autocomplete works

The changes you have made (multi-level categories and quicker auto-complete) are a great improvement but it appears that @ovari is now clarifying that their request is also for direct inline editing of transactions in the Transaction List:

> The "Enter button" (in Quicken GUI shown on the right) **enters the current transaction and moves to the next transaction**.

Your changes, of course, do not address this.are not intended to address this.

IMO, consideration of inline editing should wait until @whalley has implemented #4106, an extension to which could perhaps allow the OK-ing of the current transaction in the 'edit panel' and automatically stepping on to the next.

**Comment by whalley** [comment] 2022-10-28 07:35
This will not work on MacOS, and not sure we want it as the autocomplete does a 'wildcard' match and would be quite confusing if both features were available.

**Comment by ovari** [comment] 2022-10-28 07:57
> This will not work on MacOS, and not sure we want it as the autocomplete does a 'wildcard' match and would be quite confusing if both features were available.

Should there be a preferences so users can decide which features (autocomplete, wildcard, both) they want?

**Comment by tactilis** [comment] 2022-10-28 08:04
> This will not work on MacOS, and not sure we want it as the autocomplete does a 'wildcard' match and would be quite confusing if both features were available.

Is it **impossible** to have a wildcard match on Windows & Linux? I think this is what has been said before but it's worth asking the question again in case there are ways around it.

**Comment by ovari** [comment] 2022-10-28 08:14
> Give it a test on Linux

Downloaded https://output.circle-artifacts.com/output/job/154427a5-2616-4c82-a3fe-e3c634e6e764/artifacts/0/tmp/artifacts/mmex_1.6.1-Beta.1-Ubuntu.22.04.jammy_amd64.deb from https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/132/workflows/c92e2fbe-9ed2-4ee6-8e6c-cd47cbd3ee64/jobs/132/artifacts and neither autocomplete nor wildcard works.

Perhaps your commit has not landed in that artifact.

Thank you

**Comment by n-stein** [comment] 2022-10-28 13:26
The commit is included in that artifact according to the job details.

**Comment by n-stein** [comment] 2022-10-28 13:32
> the autocomplete does a 'wildcard' match and would be quite confusing if both features were available.

I think both could work in tandem. Autocomplete fills in based on the beginning of the string and the combobox results are filtered with a wildcard match. So if you really are looking for one that starts with the text you can just hit enter to complete, otherwise click one of the filtered options.

**Comment by n-stein** [comment] 2022-10-28 13:42
> Is it impossible to have a wildcard match on Windows & Linux?

I think it's likely doable if we drop the default autocomplete and roll our own. I'll experiment once I get some of these other features finished.

**Comment by whalley** [comment] 2022-10-28 13:53
> > the autocomplete does a 'wildcard' match and would be quite confusing if both features were available.
> 
> I think both could work in tandem. Autocomplete fills in based on the beginning of the string and the combobox results are filtered with a wildcard match. So if you really are looking for one that starts with the text you can just hit enter to complete, otherwise click one of the filtered options.

It doesn't (at present) work like that on MacOS... it presents matches in the order of matching against the complete sorted category list

<img width="365" alt="CleanShot 2022-10-28 at 14 51 48@2x" src="https://user-images.githubusercontent.com/487345/198624519-5c17bf17-0328-4f63-bdfa-8abbc4c4bfe6.png">

**Comment by n-stein** [comment] 2022-10-28 14:40
I think that is a good order to show in the dropdown.

Suppose you type "s" instead of "el". I'm thinking the autocomplete could fill "Sub" in the textctrl (with the "ub" selected) and the dropdown would show everything other than "Car & Fuel". If you type "sa" the autocomplete wouldn't fill anything and the dropdown would only show "Sub : TV & Satellite Week".

**Comment by n-stein** [comment] 2022-10-28 22:23
I'm trying to restrict this to only apply to category comboboxes, not to any others. My question is do we really need to redefine some constants in multiple classes, specifically things like combobox IDs?

For example, mmID_CATEGORY is defined in constants.h (value 6007), but also defined in billsdepositsdialog.h (value 6200), transdialog.h (value 6915), and payee.h (value 7499). 

Is it a problem if we only use the mmID_CATEGORY enum from constants.h?

**Comment by n-stein** [comment] 2022-10-31 13:30
Two small tweaks:

1. Only applies to category comboboxes. In any other combobox typing ':' is just normal text entry.
2. Replaces the ':' with whatever delimiter the user set in the options dialog. For example the single ':' will be replaced with ' : ' or ': ' if one of those category delimiter options has been set.

**Comment by whalley** [comment] 2022-10-31 19:09
@n-stein Just spotted that if I create an empty DB and then type a category like "Bi:" it fills in "Bills,". Seems to think the default separator is "," if nothing is currently set.

**Comment by n-stein** [comment] 2022-10-31 19:38
Thanks, had the wrong default delimiter set. Fixed in latest PR.

**Comment by ovari** [comment] 2022-11-01 22:56
Pressing `:` crashes:
https://output.circle-artifacts.com/output/job/6a6fa65d-61da-4d85-94bb-b45247f426fd/artifacts/0/tmp/artifacts/mmex_1.6.1-Beta.1-Ubuntu.22.04.jammy_amd64.deb

from:
https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/156/workflows/bfc66ed6-2b1b-4c3a-a06f-e8bfd51cba2d/jobs/156/artifacts

with:
Linux Mint 21 Cinnamon

**Comment by n-stein** [comment] 2022-11-02 00:03
@ovari 
What dialog were you in when this crashed? Can you give steps to reproduce?

**Comment by whalley** [comment] 2022-11-02 00:36
Have reproduced crash on Ubuntu... Happens as : is typed in the category field.
![CleanShot 2022-11-02 at 00 31 08](https://user-images.githubusercontent.com/487345/199367249-81fb1df8-01ed-473d-b4e0-1d796220635b.png)

**Comment by n-stein** [comment] 2022-11-03 01:37
@whalley Do you have a Linux build environment you can debug? If not I'll spin up a minimal Debian vm and have a go.

**Comment by whalley** [comment] 2022-11-03 01:42
Unfortunately not at present. I've got an Ubuntu VM on my Macbook which is an AMR64 build which is a bit of mess.

**Comment by n-stein** [comment] 2022-11-04 06:38
Ok, I was able to debug using CodeBlocks in a BunsenLabs VM and fixed the crash on Linux in PR #5309. Turns out that on Linux using wxString::Append to add a ":" was triggering its own EVT_CHAR events which caused a loop until the program seg faulted.

This is my first time running MMEX in Linux, so I'm not sure how autocomplete normally functions here. Looks like it filters the dropdown but doesn't autocomplete the string in the TextCtrl. Is this the expected behavior? This doesn't match the Windows behavior and will cause this quick entry to not work.

For example, on Windows if I type "I" the combobox is automatically filled with "Income" with the insertion point after "I" and remaining substring "ncome" selected. The dropdown is filled only with items that match up to the insertion point.

![image](https://user-images.githubusercontent.com/16599929/199906529-454aa135-232a-4a98-889d-000657262145.png)


On Linux the dropdown filters the same way, but the combobox text control is not autofilled with the first match:

![image](https://user-images.githubusercontent.com/16599929/199906930-e11256a2-0c2c-452c-a9de-54efcb0bd1fc.png)

Will need to play around and see if I can find a way to emulate the Windows behavior.

**Comment by whalley** [comment] 2022-11-04 07:28
> Will need to play around and see if I can find a way to emulate the Windows behavior.

I wouldn't get too hung up on this. The behaviour on MacOS is similar to Linux but with the added benefit of doing a wildcard match for the dropdown. The platforms are slightly different, primarily due to the fact that wxWidgets attempts to use native controls where possible.

**Comment by ovari** [comment] 2022-11-04 07:32
> Will need to play around and see if I can find a way to emulate the Windows behavior.

For GNU/Linux, the Windows behavior seems better than the macOS behavior.

**Comment by whalley** [comment] 2022-11-04 07:41
> For GNU/Linux, the Windows behavior seems better than the macOS behavior.

Others would disagree :-)
Really depends on your usage and needs.
https://github.com/moneymanagerex/moneymanagerex/issues/4247
https://github.com/moneymanagerex/moneymanagerex/issues/4892#issuecomment-1201765270

**Closed** 2022-11-07 19:15 UTC
Labels: enhancement, fixed

**Comment by ovari** [comment] 2022-11-09 19:58
https://output.circle-artifacts.com/output/job/fc5ee455-63ce-46f9-a398-d6dd8d7e5245/artifacts/0/tmp/artifacts/mmex_1.6.1-Beta.1-Ubuntu.22.04.jammy_amd64.deb

from:
https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/176/workflows/7416db87-0c4e-4869-8186-110a409b39f3/jobs/176/artifacts

no longer crashes:
Linux Mint 21 Cinnamon

however, autocomplete does **not** work.

Is this a planned that `:` will work with GNU/Linux operating systems or is this a Windows-only feature?

Thank you

**Comment by ovari** [comment] 2022-11-09 20:02
GNU/Linux version of MMEX does not seem to have the Google autocomplete (macOS) implementation nor the `:` autocomplete (Windows) implementation.

**Comment by whalley** [comment] 2022-11-09 20:27
Situation is that the native combo box on Windows, MacOS, and Linux all have slight differences. 

At present the (:) feature only exists on Windows due to the way the box is populated by OS. It would likely need us to create a new shared combobox implementation to make it work on other platforms and would not be compatible with the MacOS wildcarding

For Linux just basic entry is supported similar to Windows without the (:) feature.

**Comment by ovari** [comment] 2022-11-09 21:54
> At present the (:) feature only exists on Windows due to the way the box is populated by OS. It would likely need us to create a new shared combobox implementation to make it work on other platforms and would not be compatible with the MacOS wildcarding
>
> For Linux just basic entry is supported similar to Windows without the (:) feature.

Should a new issue specific for GNU/Linux be created with a title like `GNU/Linux Quick category entry using ":" to autocomplete` as this issue is marked as Closed?

Thank you

**Comment by n-stein** [comment] 2022-11-09 22:56
> Is it **impossible** to have a wildcard match on Windows & Linux? I think this is what has been said before but it's worth asking the question again in case there are ways around it.

I got wildcard match to work on Windows. It requires two things: 

1. A custom wxTextCompleter that does the pattern matching. Here's the one I built:

In mmSimpleDialogs.h I added a new mmTextCompleter class

![image](https://user-images.githubusercontent.com/16599929/200959450-261aafb4-bb5c-49dc-86cd-b075b7c69809.png)

In mmSimpleDialogs.cpp I added code for pattern matching and used the new TextCompleter for the mmComboBox AutoComplete

![image](https://user-images.githubusercontent.com/16599929/200959521-8a194114-966c-4295-94e3-ff2f4c2e1c35.png)
![image](https://user-images.githubusercontent.com/16599929/200959666-9755e57a-edbb-408a-a7ac-11853adcea30.png)


2. Modify the wxWidgets source file src/msw/textentry.cpp to use the ACO_NOPREFIXFILTERING option for IAutoComplete2 and rebuild wxWidgets from scratch.

![image](https://user-images.githubusercontent.com/16599929/200957395-018fd1f3-dbe7-4f9e-8bb8-9d5d5eafbd01.png)

Doing this makes the Windows autocomplete function the same as the MacOS autocomplete. 

![image](https://user-images.githubusercontent.com/16599929/200958761-76767636-a24c-459a-9daf-bc97b7d5eab8.png)

Incidentally that means it doesn't work with this ":" fast entry option, but maybe that's OK if its outweighed by the net benefit of wildcard matching.

**Comment by whalley** [comment] 2022-11-09 23:24
> I got wildcard match to work on Windows. It requires two things:

Neat.

> 2\. Modify the wxWidgets source file src/msw/textentry.cpp to use the ACO_NOPREFIXFILTERING option for IAutoComplete2 and rebuild wxWidgets from scratch.

Suggest bumping this with the suggestion. https://github.com/wxWidgets/wxWidgets/issues/11465

Don't think we should be changing wxWidgets codebase, best to perhaps raise a PR with option to enhance via an option.

> I should mention that the ACO_NOPREFIXFILTERING option in shldisp of the win32 API is only available in Windows Vista and later. Not sure if that matters.

Agreed.

**Comment by ovari** [comment] 2022-11-10 00:14
> Incidentally that means it doesn't work with this ":" fast entry option, but maybe that's OK if its outweighed by the net benefit of wildcard matching.

Can there please be a setting so that ":" fast entry option is enabled and wildcard matching option disabled?

Perhaps the could be an option called `Category autocomplete`, which has a drop-down with the values:
* `None`
* `":" quick entry` or `":" Quicken entry` or `":" Intuit entry`
* `Wildcard matching`

The ":" Quick(en) entry option may be preferable for users migrating from Intuit/Quicken/QuickBooks to MMEX, including us.

What do you think?

Thank you

**Comment by whalley** [comment] 2022-11-10 00:31
> > Incidentally that means it doesn't work with this ":" fast entry option, but maybe that's OK if its outweighed by the net benefit of wildcard matching.
> 
> Can there please be a setting so that ":" fast entry option is enabled and wildcard matching option disabled?

It then gets more complicated as we would have to limit the setting options based on platform and what if people use multiple platforms (Win home, Mac work?). What should be very simple, namely category entry, gets complex.

My view.... If people move to MMEX then they need to follow the rules of MMEX we should not be in the business of trying to mimic, via configuration options, other platforms. We have our way of doing it, which may differ depending upon platform :-)

We can expend a lot of effort on minor things like this rather that concentrating on bigger changes.

Of course that's just my view.  Others, of course, can have different views and submit code changes if they have strong preferences.

**Comment by n-stein** [comment] 2022-11-10 01:29
Interestingly I found that just implementing the wxTextCompleter change still gives me the normal Windows autocomplete with the existing wxWidgets build, and then by simply swapping the wxmsw32u_core_vc_mmex.dll with the one compiled with the ACO_NOPREFIXFILTERING option I get the wildcard autocomplete. So I can choose fast entry vs pattern match depending on which flavor of the DLL I use.

**Comment by tactilis** [comment] 2022-11-10 08:28
@whalley 
>  If people move to MMEX then they need to follow the rules of MMEX we should not be in the business of trying to mimic, via configuration options, other platforms.

I agree wholeheartedly with this. It is often the case (and I have at times been guilty of it too) of wanting things to be just like they were in application XXX that someone is migrating away from when they start using new application YYY.

However, give it time, put the effort in to getting used to YYY's ways of working - and _only then_ if YYY's approach is still considered sub-optimal, make proposals for changes giving reasons why the suggested new behaviour in YYY is going to be better than the way it works currently.

The reasons should not be "because XXX did it this way" - rather they should be based on a clear use case demonstrating why the changed behaviour in would benefit a significant number of YYY's users.

Adding options to "Make it behave like XXX/Quicken/Intuit" etc is not the answer.
