### ISSUE TITLE
about default column seq.

### ISSUE THREAD

**Issue by DevAnyKR** [moneymanagerex/moneymanagerex#6847] opened 2024-08-29 09:22 UTC
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [x] 1.8.1 bata
 - [ ] 1.8.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [x] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug
The positions of the columns are not saved and their order changes depending on the language.

1. by Language
a. Korean v1.8.1 beta(appveyor)  a month ago.
![image](https://github.com/user-attachments/assets/849ed9be-41a6-40bf-9675-967849b1a0e3)
column: ID, DATE, number, payee, status, category, tag, withdrawal, deposit, note, UCF1, UCF2, lastdate, **balance**, 
balance column is fixed at the end.

a. Korean v1.8.1 beta(appveyor)  today.
![image](https://github.com/user-attachments/assets/e6980042-2ec0-4269-a03b-ab880459e98c)
column: ID, DATE, number, payee, status, category, tag, withdrawal, deposit, balance, note, **UCF1, UCF2**, lastdate

b. English
![image](https://github.com/user-attachments/assets/d50f5ac4-b134-41a8-904d-9452cd441fe9)
column: ID, **UCF1, UCF2** , DATE, number, payee, status, category, tag, withdrawal, deposit, balance, note, lastdate

![image](https://github.com/user-attachments/assets/a2dd520b-194e-4181-9084-31448f034c7b)
All transactions page
account column is fixed at the end.

2. settings
![image](https://github.com/user-attachments/assets/e2752319-f68e-4dd7-9469-2b62067145c9)
Look at the order of the UCF columns. They don't appear at the beginning.
The order of columns is different in Korean and English.

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

open column order manager

Expected result:

Actual result:

# Additional Requests

Column Order manager
- allow resizing
- Column names are duplicated by language.
-- UCF columns does not appear in the English list.

**Comment by jensb** [comment] 2024-08-29 20:17
Thanks for reporting this. This feature is my addition to MMEX, it's not finished yet (beta :-) ).
I'm working on making the order of columns not depend on the language, this turned out to be more difficult than I expected.

**Comment by jensb** [comment] 2024-09-01 21:12
Progress see https://github.com/moneymanagerex/moneymanagerex/issues/4160

**Comment by jensb** [comment] 2024-09-06 18:14
FYI: I refactored this process. Now the dialog is gone and the ordering of columns is done via right-clicking on the columns headers, and chose "Move right" or "Move left". Column order is stored in the user settings database as a list of numbers, not list of column header names, so it survives a change of language. Also, it's MUCH less code. :-)

Please test again as soon as my PR has been accepted. Thanks!

**Comment by DevAnyKR** [comment] 2024-09-19 00:24
1. I just applied the update and balance is messed up. Same problem for all accounts.
2. When move a column, it becomes 0 width along with the column next to it.

![image](https://github.com/user-attachments/assets/6dfd64de-299a-4c43-9112-86243a6cf218)
column order: W, D, B

**Comment by whalley** [comment] 2024-09-19 15:54
> 1. I just applied the update and balance is messed up. Same problem for all accounts.
> 
>     2. When move a column, it becomes 0 width along with the column next to it.

I can't reproduce this on MacOS. All seems good.

**Comment by DevAnyKR** [comment] 2024-09-20 11:31
> I can't reproduce this on MacOS. All seems good.

Then test it on Windows 11. I rolled back to 1.8.1 beta. 😢

**Comment by DevAnyKR** [comment] 2024-09-26 00:49
@whalley RC1 report
2024-09-26
> 1. ~~

fixed

> 2. When move a column, it becomes 0 width along with the column next to it. And both columns are hidden.

There is still a problem..

![image](https://github.com/user-attachments/assets/b86029bb-a685-4fcc-9035-b54b8a0be0e7)
![image](https://github.com/user-attachments/assets/57438867-e37c-4c55-9959-f55d8fe738e7)
![image](https://github.com/user-attachments/assets/4bb3bdee-8d50-4daf-9f9a-e7f2b8cc9dad)


Windows 11 x64

**Comment by jensb** [comment] 2024-09-26 18:09
I am not (on Linux).
I have downloaded a Windows 11 VM image to test this but my computer is too weak for Windows 11 in a VM. So I went with Windows 10, and with the current build I can reproduce this error. Moving columns makes them invisible (width=0) until you change the width.

I cannot reproduce this on Linux with the current 1.8.1 Flatpak build. Otherwise I'd already have tried to fix it :-)

**Comment by whalley** [comment] 2024-09-26 20:09
OK, this needs fixing prior to the v1.8.1 release. @jensb Are you able to investigate further?

**Comment by jensb** [comment] 2024-09-26 21:10
Unfortunately I do not have a Windows build environment available at the moment, I would have to set up a more powerful Windows VM to do that.
I will try to get some debug output on Linux if the column widths are transferred correctly though.

**Comment by jensb** [comment] 2024-09-28 15:38
I found that  m_columns[m_ColumnHeaderNbr].WIDTH sometimes is  -1.
Linux doesn't seem to care about this or uses a default from somewhere, since the column width is simply kept.
Maybe that is why Windows hides the columns because it tries to set a negative width?
How can I access the "true" width of a column?

**Comment by whalley** [comment] 2024-09-29 19:53
> I am already using `static_cast<wxListColumnFormat>(m_columns[m_ColumnHeaderNbr].FORMAT`, I could do something similar for the `SetColumnWidth()` enum if this fixes it.

I've no idea with this one... Maybe worth a try.

**Comment by jensb** [comment] 2024-09-30 08:03
This would require changing the wxWidgets include files. I'm not sure if I can do this without breaking more stuff.
I now have a Windows 11 build environment (VM) including VS2022, but I cannot get the Windows BUILD.md instructions to work. Links seem to be outdated and not working. MMEX seems to build fine but then cannot find DLLs when started. I am trying to script the setup process to make it more generic and automated but I may need some assistance.
Who else is working on a Windows build system and can help?

**Comment by n-stein** [comment] 2024-09-30 13:44
You can copy the wxWidgets .pdb files there as well if you want debug symbols for wxWidgets. That lets you step into the wxWidgets code itself when you are debugging, which is sometimes helpful.

**Comment by n-stein** [comment] 2024-09-30 22:11
That fixes the width issue by using SetColumnWidth on the ListCtrl instead of SetWidth on a ListItem. It also removes the unnecessary double painting that was occurring which made the panel update choppy.

**Comment by n-stein** [comment] 2024-10-01 13:14
"Reset Columns" unhides hidden columns. Perhaps it should also reset the column order to default?

**Comment by DevAnyKR** [comment] 2024-10-01 14:56
> "Reset Columns" unhides hidden columns. Perhaps it should also reset the column order to default?

It seems like a good idea to separate the Reset Columns and AutoWidth functions. The Reset Columns words seem closer to resetting the order than the width, because the default column widths when start a new MMEX seem to be quite narrow.

**Comment by whalley** [comment] 2024-10-02 21:30
@DevAnyKR Does the latest version fix your initial issue? We can perhaps look at tidying the 'Reset column order/sizes' functionality in next release as I'm keen to get the next release out.

**Comment by jensb** [comment] 2024-10-03 21:31
Thank you for jumping in. I have managed to setup a Win11 build environment but there are still some issues. Will try out the patch after this weekend and report back.
Now that we have a place to store the column order, I was going to try to catch drag-n-drop actions on Windows as well so Windows users can use the WxWidgets column drag&drop feature to reorder their columns.

**Comment by whalley** [comment] 2024-10-10 12:39
> Thank you for jumping in. I have managed to setup a Win11 build environment but there are still some issues. Will try out the patch after this weekend and report back. Now that we have a place to store the column order, I was going to try to catch drag-n-drop actions on Windows as well so Windows users can use the WxWidgets column drag&drop feature to reorder their columns.

@DevAnyKR  @jensb Any update on this? Any issues on Windows now?

**Comment by jensb** [comment] 2024-10-10 14:52
Sorry - I still have issues getting a build on Windows to run properly, there are assertion errors related to date/time formatting and if I close those, the app freezes. So I cannot test atm. No such issue on Linux.

**Comment by n-stein** [comment] 2024-10-21 14:35
Ok, I've got it. The issue is wxWidgets uses std::mktime to set the wxDateTime object. However, _mktime64 returns -1 if it references a date after 23:59:59, December 31, 3000, UTC (according to [Microsoft](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mktime-mktime32-mktime64?view=msvc-170)). We are setting our DATE_MAX date in mmDateRange to Dec 31 9999 which returns -1 and causes the assertion failure on the mktime call in wxWidgets debug builds.

Changing the value to Dec 31 2999 (epoch 32503679999) resolves the issue. I think 2999 is sufficiently far in the future, we don't need to go to 9999.

**Comment by n-stein** [comment] 2024-10-21 14:37
@jensb This should resolve the issues with your Windows build.

**Comment by renato-mmex** [comment] 2024-10-22 20:45
I tested it briefly, but I'm not thrilled.
‘All bookings’ is not treated in the same way as an account.
If I drag the column, the position is not saved.

**Comment by jensb** [comment] 2024-10-29 15:57
Each table type has its own sort order. "All bookings" is a different type, so it gets its own order. Some tables' columns also cannot be sorted at all, because they lack internal structures I used to do this (`real_column` variable).
Dragging columns is a Windows only feature and I use (and develop) MMEX on Linux so this feature is not relevant to me.
However (!) I still tried to get a Windows build environment up and running which took a while and then there was a runtime bug (see above). I will have another look at this this week.

**Comment by whalley** [comment] 2024-10-30 23:18
I'm not sure that WxListCtrl has any events associated with column moves that can be intercepted for this on Windows. wxGrid supports these and we may need to wait for the work to move to this to complete... https://github.com/moneymanagerex/moneymanagerex/issues/6826#issuecomment-2318906129

**Comment by n-stein** [comment] 2024-10-31 13:35
You could save the current column order in the mmListCtrl destructor, that way any drag reordering is saved when the user leaves the panel or closes the application.

**Comment by jensb** [comment] 2024-10-31 20:00
Good idea, I'll try to do this (on Linux first, easier for me). If it works I'll commit so you can test on Windows.

**Comment by whalley** [comment] 2024-11-13 06:36
Any update on this? Would be good to get v1.8.1 out. What are the current known issues?

**Comment by jensb** [comment] 2024-11-14 22:04
I'm sorry to have let you wait, but right now I'm simply not able to work on MMEX.
(Family) life is what happens when you have made other plans. :-(

Status:
The column shifting code works for all grids that have a "m_real_column" property. The column order is saved by table in the global configuration SQLite database.
What is still missing is catching the Win32 column header drag & drop events and saving the changed order (in addition to the context menus), see comments above.

**Comment by whalley** [comment] 2024-11-17 18:16
> I'm sorry to have let you wait, but right now I'm simply not able to work on MMEX. (Family) life is what happens when you have made other plans. :-(
> 
> Status: The column shifting code works for all grids that have a "m_real_column" property. The column order is saved by table in the global configuration SQLite database. What is still missing is catching the Win32 column header drag & drop events and saving the changed order (in addition to the context menus), see comments above. And possibly supporting custom column order for tables that do not implement "m_real_column".

OK, this needs a Windows developer to help as the drag/drop column re-ordering only works on Win32. Note also that the column ordering methods are not implemented on all platforms so existing functionality will likely need to remain augmented by saving the order in the destructor for Windows.  https://docs.wxwidgets.org/3.2/classwx_list_ctrl.html#a79411a2c63b0bc9bd6d9d48838aa86c1

**Comment by whalley** [comment] 2024-11-21 21:35
@n-stein Great work, I've not noticed any issues on Mac from casual testing. Let's see if we can get a 1.8.1 release out by the end of the month.

**Closed** 2024-11-28 20:45 UTC
Labels: enhancement, fixed
