### ISSUE TITLE
Bug: Wrong balance in filtered mode

### ISSUE THREAD

**Issue by aquirin** [moneymanagerex/moneymanagerex#619] opened 2015-12-31 16:16 UTC
When filtering the account view, the balance show the original balance, not the balance recomputed using the filtered view.

**Comment by vomikan** [comment] 2016-01-01 10:21
That is a feature, not a bug.

**Comment by stef145g** [comment] 2016-01-01 11:33
When filtering is active you should be able to see the **Displayed Bal:** on the top right which is the what you are looking for I think. No Bug. If you agree, please close this issue.

**Comment by aquirin** [comment] 2016-01-01 12:30
Ok but it would be nice to see the total sum of the filtered view, for
instance the total money spent in food for a given range of dates.

Can we let it open as a feature?

**Comment by stef145g** [comment] 2016-01-01 16:02
@aquirin, I can do this now by setting the filter on my date range, and select category as Food:Groceries  The displayed balance displays the total sum for this specific range.

If you are talking about the actual balances in the balance column, then this would reflect the bank statement balances on that date provided the date sequence matches the bank statement. If they don't, it means that there are some entries that should not be there, and can be temporarily negated by setting the transaction to void, and reinstated later. Otherwise, the balance column should be ignored as this is not a running balance for this view.

Not sure what the problem is if there is one, or what you are proposing.

**Comment by aquirin** [comment] 2016-01-01 16:33
Ok you are right, balance is already shown in the top right. And the
balance column should be viewed as you said, as a copy of the original
balance column when data is not filtered. It was just a bit surprising for
me as I would first expect a cummulated sum of the current data here, but
if other users are OK with that I'm fine with it too, I will get used to.

Thanks,


2016-01-01 17:02 GMT+01:00 Stefano <notifications@github.com>:

**Closed** 2016-01-01 17:01 UTC
