### ISSUE TITLE
Make Dialogs resizable

### ISSUE THREAD

**Issue by sarjanwebdev** [moneymanagerex/moneymanagerex#5668] opened 2023-02-13 23:20 UTC
Love it how we can now have a N-depth hierarchy of categories.

# Use cases
With long category names and concatenated full category names, the names don't fit the view, 
If the dialog can be expanded the way I want, it should help.
The import file dialog does it already.

This should apply to all dialogs, incl reorganise payee/category etc.
1. Have default size
2. Let resize, and remember resized dimensions
3. Load with last resized dimensions
4. (Low value) Allow in settings to reset all dialog dimensions/size to default

![image](https://user-images.githubusercontent.com/10950385/218596052-871e557a-d1b6-483f-ae75-8ec6c3200aaa.png)

**Comment by rmelillo76** [comment] 2023-02-14 01:40
This behavior does already exist for some of the dialogs - Organize Payees, Organize Categories, Split Transactions and Currency Manager are a few that come to mind.

TIP: On the New Transaction screen, you can press [Enter] into the Payee and Category fields to bring up the corresponding 'Organize' dialog for each one in the meantime.

**Comment by vomikan** [comment] 2023-02-14 08:56
Always start typing the name when selecting a category. In this case, the dialog becomes convenient. Or use the advice described above.
![image](https://user-images.githubusercontent.com/6836805/218686731-d7eafd37-af0c-4f4e-a7f3-e19ca13093a3.png)

**Comment by sarjanwebdev** [comment] 2023-02-14 11:39
> 

@vomikan the search is not a true partial match, it's LIKE 'keyword%', should be LIKE '%keyword%'

**Comment by sarjanwebdev** [comment] 2023-02-14 11:40
> > 
> 
> @vomikan the search is not a true partial match, it's LIKE 'keyword%', should be LIKE '%keyword%'

Because my categories are named long, to get to a particular subcategory, I have to type a lot, that kills the purpose of search in my case.

**Comment by vomikan** [comment] 2023-02-14 11:49
> the search is not a true partial match, it's LIKE 'keyword%', should be LIKE '%keyword%'

We cannot implement such a search due to technical reasons. However, it works in a similar way on MAC.

**Comment by tactilis** [comment] 2023-02-14 21:03
@sarjanwebdev
> Because my categories are named long, to get to a particular subcategory, I have to type a lot, that kills the purpose of search in my case.

Would you be happy to provide an export of your categories please? There may be a way to reduce the typing required but I'd need to see them first to advise if it would work for you.

Just go to `File | Export as | JSON File...`, select Categories, deselect Accounts as shown:

![mmex_4cIkp5nsIE](https://user-images.githubusercontent.com/4060092/218862118-d4faeda5-4a43-4e05-b42a-5828aab813d5.png)

Email to martin _at_ tactilis _dot_ co _dot_ uk

I'll delete the file once I have looked at it.

**Comment by n-stein** [comment] 2023-02-14 21:48
Since you use Windows you can take advantage of the ':' quick entry method.

Type only the minimal characters until your desired level 1 category is autocompleted, then type ':'. The insertion point will automatically jump to the end of the category and add your selected category delimiter. Now type the next few characters of the level 2 category until your desired category is autocompleted, then type ':' to again advance the insertion point. Now type the next few chars of the level 3 category etc...

You can get to deep categories with very few keystrokes such as `inc:in:c:l` to get to `Income : Investment Income : Capital Gains : Long Term`.

**Comment by n-stein** [comment] 2023-02-15 16:33
That code change will get you most of the way there. It makes the dialog resizeable, and it automatically opens with the size adjusted to fit the payee and category strings if they are too long for the default width. However, it doesn't save/restore the adjusted size.

https://user-images.githubusercontent.com/16599929/219091190-8c85e169-5339-4b74-b27f-bc48e3ab6f05.mp4

**Comment by n-stein** [comment] 2023-02-15 17:10
Also made the width of "Relocate Categories" and "Relocate Payees" resizeable (height is static since the elements are all single-line).

**Comment by n-stein** [comment] 2023-02-15 22:42
Recurring Transaction dialog is now resizeable. Also fixed a minor issue with the Transaction dialog minimum width not being set properly if opened on a transaction with custom fields (you could resize the dialog too small in that case).

**Comment by whalley** [comment] 2023-02-16 00:20
Ok MacOS i get issues withe amount fields:

Transaction Dialog
![CleanShot 2023-02-16 at 00 17 24](https://user-images.githubusercontent.com/487345/219225440-63ab8439-ef16-4d4c-b559-8b87751a0dbc.png)

Recurring Transaction Dialog
![CleanShot 2023-02-16 at 00 18 24](https://user-images.githubusercontent.com/487345/219225543-9fc7ce31-0dc7-4f62-97b0-b9a0aaa890a3.png)

**Comment by sarjanwebdev** [comment] 2023-02-16 01:51
> That code change will get you most of the way there. It makes the dialog resizeable, and it automatically opens with the size adjusted to fit the payee and category strings if they are too long for the default width. However, it doesn't save/restore the adjusted size.

This is it.

**Comment by n-stein** [comment] 2023-02-16 02:33
> MacOS i get issues withe amount fields:

Odd, on Windows they render properly as their default size. Does that commit I just pushed help?

**Comment by whalley** [comment] 2023-02-16 08:46
I'm using latest commit. Seems the same as this issue.
https://github.com/moneymanagerex/moneymanagerex/issues/4290#issuecomment-1148012595

**Comment by whalley** [comment] 2023-02-16 09:04
It's the same with that latest commit... Leaving the 
`transPanelSizer->Add(amountSizer, wxSizerFlags(g_flagsExpand).Border(0));`
helps but obviously stretches the amount fields - which is no issue for me - and I think people have asked for large amount fields in the past where currencies force large numbers
![CleanShot 2023-02-16 at 09 02 44](https://user-images.githubusercontent.com/487345/219318022-fd38571c-717d-43b4-84e9-84d327722656.png)

**Comment by n-stein** [comment] 2023-02-16 13:13
Yes, the sizer was originally set to expand, but i thought the amount textctrls looked too big as the dialog size was extended so I made them static. 

If there is a use for wide fields we can just allow them to expand. The other option we could try is to add something like `amountSizer->SetMinSize(amountSizer->Get size());` to prevent them from rendering any smaller.

**Comment by whalley** [comment] 2023-02-16 20:03
@n-stein Personally I think expanding the amount fields feels the right thing to do.

**Comment by whalley** [comment] 2023-02-17 00:16
Just noticed on recurring transactions the windows is not sized to cover all controls....

![CleanShot 2023-02-17 at 00 15 57](https://user-images.githubusercontent.com/487345/219517091-b24e8914-6aaa-4414-9f63-3ce178399da4.png)

**Comment by n-stein** [comment] 2023-02-17 01:56
Interesting, another case where Mac doesn't match Windows. Looks fine to me:
![image](https://user-images.githubusercontent.com/16599929/219529554-278a2704-bf84-4b91-878d-4ee2c98221a3.png)

Will poke around in the code, see if I see anything obvious.

**Comment by whalley** [comment] 2023-02-17 08:12
Will do same.

**Comment by whalley** [comment] 2023-02-17 09:13
Changing the fixed with 460 here:
` SetSize(wxSize(minWidth + 460 + (m_custom_fields->IsCustomPanelShown() ? m_custom_fields->GetMinWidth() + 10 : 0), GetMinHeight()));` 
to 485 fixes it.

Not ideal. Probably need to look at how to programmatically determine the width needed.

**Comment by whalley** [comment] 2023-02-17 15:57
Do we need to calculate the size? Does this work OK? Seems fine for me

```
    Fit();
    SetMinSize(GetSize());
```

**Comment by n-stein** [comment] 2023-02-17 17:57
The min size is already set in CreateControls with SetSizerAndFit. This is attempting to expand the initial size of the dialog to accommodate any long category or payee strings that don't fit in the default width. 

Can you try this:
```
int minWidth = std::max(cbPayee_->GetSize().GetX(),
        cbPayee_->GetSizeFromTextSize(cbPayee_->GetTextExtent(cbPayee_->GetValue()).GetX()).GetX()) - cbPayee_->GetSize().GetWidth();
minWidth = std::max(minWidth,
        cbCategory_->GetSizeFromTextSize(cbCategory_->GetTextExtent(cbCategory_->GetValue()).GetX()).GetX() - cbCategory_->GetSize().GetWidth());
SetSize(wxSize(GetMinWidth() + minWidth + (m_custom_fields->IsCustomPanelShown() ? m_custom_fields->GetMinWidth() : 0), GetMinHeight()));
```

**Comment by whalley** [comment] 2023-02-17 19:56
That now presents OK. 

Though on MacOS the dialogs do not open wide if payee/categories are long, but the dialog does resize horizontally OK. I'm fine with that though.

Transaction
<img width="380" alt="CleanShot 2023-02-17 at 19 55 33@2x" src="https://user-images.githubusercontent.com/487345/219778761-df347f33-82d5-4498-acd1-f90da83cfa85.png">

Recurring
<img width="678" alt="CleanShot 2023-02-17 at 19 54 02@2x" src="https://user-images.githubusercontent.com/487345/219778240-bf04273d-9291-4a4e-b90e-70fc64f4c91f.png">

**Comment by n-stein** [comment] 2023-02-17 20:18
Its possible GetSizeFromTextSize isn't implemented on Mac, in which case it just returns wxDefaultSize. That would cause the dialogs to always open at their default minimal size.

**Comment by whalley** [comment] 2023-02-17 20:50
> Its possible GetSizeFromTextSize isn't implemented on Mac, in which case it just returns wxDefaultSize. That would cause the dialogs to always open at their minimal size.

You are correct.

`Currently this method is only implemented for wxTextCtrl, wxComboBox and wxChoice  in wxMSW and wxGTK.`

**Comment by rmelillo76** [comment] 2023-02-19 13:59
I just encountered a bug that I think is related to this fix:

1. Start to create a new transaction
2. Click into the Category field:
3. Click the Split Transaction button to attempt to open the Split Transaction dialog:
 ![image](https://user-images.githubusercontent.com/95182117/219952837-0b6f15e6-d943-4a03-9408-7d84b3d365fd.png)

Results: Instead of the dialog opening, the Category field resizes itself to the width of the dialog and the button is hidden. The dialog does not open.
![image](https://user-images.githubusercontent.com/95182117/219952877-19bd66f6-4fe7-44ff-b05f-ad047351fde3.png)

Note that resizing the dialog does reveal the button again:
![image](https://user-images.githubusercontent.com/95182117/219952898-0c60e4f5-aa0c-4ac5-bce8-ce5df49d0da2.png)

![image](https://user-images.githubusercontent.com/95182117/219952981-32917ad1-b4ad-4b75-9cb3-a3532846b513.png)

Thanks
Rich

**Comment by n-stein** [comment] 2023-02-19 17:03
I am unable to reproduce this, the split button functions as expected for me.

https://user-images.githubusercontent.com/16599929/219962999-6b55c439-c8d5-4ea5-bc22-24dae7b72dab.mp4

**Comment by rmelillo76** [comment] 2023-02-19 17:07
> I am unable to reproduce this, the split button functions as expected for me.

Thanks @n-stein. Here's the version I tested with incase it helps. It's pretty consistent, I will try to capture a video demonstration as well.
![image](https://user-images.githubusercontent.com/95182117/219963215-e5db001c-c764-44e4-aba2-e37f85422d11.png)

**Comment by whalley** [comment] 2023-02-19 17:30
> I am unable to reproduce this, the split button functions as expected for me.

Can't reproduce on MacOS either.

**Comment by tactilis** [comment] 2023-02-19 19:06
I can reproduce it on Windows 11 using:
• Version: 1.6.4-Beta.1 64-bit
• Built on: Feb 18 2023 14:20:58
• Database version: 17 (aes128cbc)
• Git commit: 28302c8 (2023-02-18)

https://user-images.githubusercontent.com/4060092/219969177-40d26191-56a4-4938-8d1c-651ce6ded3d8.mp4

<br>

Note that if I click on the split button without first clicking in the Category field, then the Split Transaction dialog _is_ displayed as normal.
<br>

If I just tab into the Category field, the erroneous field width change also occurs:

https://user-images.githubusercontent.com/4060092/219969454-5f93ffc1-61a8-495e-8463-aba4d8b92fd4.mp4

<br>
(Excuse the email notification bottom right)

**Comment by vomikan** [comment] 2023-02-19 20:35
I can't reproduce this on Windows 10.
I have made a minor change, which is just a small optimization.

**Comment by whalley** [comment] 2023-02-20 20:41
I can't reproduce in Win11/arm

• Version: 1.6.4-Beta.2 64-bit
• Built on: Feb 19 2023 20:36:18
• Database version: 17 (aes128cbc)
• Git commit: 735b7dd (2023-02-19)

**Comment by n-stein** [comment] 2023-02-21 04:17
Curious, does the Number field/increment button show the same behavior?

**Comment by tactilis** [comment] 2023-02-21 08:34
> does the Number field/increment button show the same behavior

No. That works OK

> does the same issue occur with the recurring transaction dialog?

It's a little different. The Split Transaction dialog _is_ displayed but then, after cancelling that, the fields on the transaction dialog change size.

https://user-images.githubusercontent.com/4060092/220291069-8bc013d4-c847-464a-9729-80203fdb8c30.mp4

**Comment by tactilis** [comment] 2023-02-21 08:57
I've just tested the latest build:
• Version: 1.6.4-Beta.2 64-bit
• Built on: Feb 21 2023 08:36:05
• Database version: 17 (aes128cbc)
• Git commit: a4442e7 (2023-02-21)

The behaviour is still as described above.

**Comment by tactilis** [comment] 2023-02-21 09:05
Note that if I resize the transaction dialog _first_, then when I click in the Category field, then click the Split button, the Split Transaction dialog _is_ displayed (unlike what is seen in the first video here https://github.com/moneymanagerex/moneymanagerex/issues/5668#issuecomment-1436067428)

https://user-images.githubusercontent.com/4060092/220298721-5852383a-4ad4-4aff-9f0b-ac5db17937a1.mp4

**Comment by n-stein** [comment] 2023-02-21 17:37
On Linux it opens without the buttons showing at all

![image](https://user-images.githubusercontent.com/16599929/220418889-1d13ae5e-47fe-4c53-b1cf-b30342cdd6ca.png)

**Comment by n-stein** [comment] 2023-02-21 21:25
That resolves the issue on Linux, hopefully the same works for Windows.

**Comment by n-stein** [comment] 2023-02-21 21:40
@whalley do you see this odd behavior on Mac when resizing the dialog after expanding/collapsing the custom fields panel? Windows looks fine, but Linux is not moving the buttons along with the comboboxes. 

https://user-images.githubusercontent.com/16599929/220464247-0550158b-928c-4113-a0e9-60e539839076.mp4

**Comment by whalley** [comment] 2023-02-21 23:39
@n-stein  Works fine on MacOS

**Comment by tactilis** [comment] 2023-02-22 08:31
Not fully fixed on Windows.

Tested:
• Version: 1.6.4-Beta.2 64-bit
• Built on: Feb 21 2023 23:41:59
• Database version: 17 (aes128cbc)
• Git commit: bc6adb4 (2023-02-21)

**Transaction dialog behaviour:**

See https://github.com/moneymanagerex/moneymanagerex/issues/5668#issuecomment-1436067428

1. FIXED: Clicking in the Category field and then on the Split button now works OK. i.e. the erroneous behaviour shown in the 1st video in the above comment has gone.

2. NOT FIXED: Tabbing into the Category field still exhibits the erroneous behaviour shown in the 2nd video in the above comment.

**Recurring Transaction dialog behaviour:**

See https://github.com/moneymanagerex/moneymanagerex/issues/5668#issuecomment-1438046168

1. FIXED: Clicking in the Category field, then on the Split button, then cancelling the Split Transaction dialog now works OK. i.e the erroneous behaviour shown in the 1st video in the above comment has gone.

2. NOT FIXED: Tabbing into the Category field, then clicking on the Split button, then cancelling the Split Transaction dialog still exhibits erroneous behaviour as shown below:

https://user-images.githubusercontent.com/4060092/220564829-bd102500-2a7f-457e-bab4-f3767e790f39.mp4

**Comment by n-stein** [comment] 2023-02-22 19:00
Tough to troubleshoot now since I can't reproduce the behavior on either my native Windows 10 or Linux VM. Maybe that will help?

**Comment by tactilis** [comment] 2023-02-22 20:57
Congratulations @n-stein. You have fixed all the erroneous behaviour.

**Comment by n-stein** [comment] 2023-03-07 23:22
> * Let resize, and remember resized dimensions
> 
> * Load with last resized dimensions

Done

**Comment by n-stein** [comment] 2023-03-07 23:50
Missed the recurring transaction dialog save/restore on the first PR, added it now.

**Closed** 2023-03-27 18:53 UTC
Labels: enhancement
