### ISSUE TITLE
Separate categories for withdrawal and deposit

### ISSUE THREAD

**Issue by michalchecinski** [moneymanagerex/moneymanagerex#879] opened 2016-09-04 10:36 UTC
Could you split categories between withdrawal and deposit categories. So when adding transaction when user specify Type, after choosing category button only the withdrawal categories or deposit categories will show up, depending on the Type of transaction.

make sure these boxed are checked before submitting your issue - thank you!
- Check OS
  - [x] Windows
  - [x] Mac OSX
  - [x] Linux 
-  Check MMEX version
  - [x] 1.3.x
  - [ ] 1.2.x
  - [ ] 1.1 or older

**Comment by guanlisheng** [comment] 2016-09-06 06:42
i think the same category would apply against both withdrawal and deposit by design.

**Comment by vomikan** [comment] 2016-09-06 10:58
there is the function
bool Model_Category::has_income(int id, int sub_id)
Using it and 'Show All' checkbox all categories of the other types may be hiden.
But it can have a negative impact on performance.

**Comment by vomikan** [comment] 2016-09-07 15:38
I've discovered the issue. To separate categories it need additional fiels in DB.
It's not good idea to use 'has_income' function becouse it not working for empty DB.

**Comment by guanlisheng** [comment] 2016-09-11 08:25
@vomikan , i think you totally misunderstood what @michalchecinski wanted here.

**Comment by vomikan** [comment] 2016-09-11 12:55
I beleave that I understand the issue.

**Comment by guanlisheng** [comment] 2016-09-12 15:16
If you understood, there should no pull request for such request. 
Again, one single category would be applied against on both withdrawal and deposit transactions. This is the reality.
Closing this issue and feel free to open it with more support.

**Closed by guanlisheng** 2016-09-12 15:16 UTC
Labels: enhancement
