### ISSUE TITLE
Hotkey for setting Status to "None" differs depending on context

### ISSUE THREAD

**Issue by GKN472** [moneymanagerex/moneymanagerex#4065] opened 2021-12-12 21:02 UTC
When a transaction is in detail view, pressing N sets the transaction's status to None.
When a transaction is selected in ledger view, pressing N does not set the transaction's status to None, but pressing U does.

<hr>Version: 1.5.11 64-bit<br>
 • Build: Dec  7 2021 12:41:07<br>
 • db 7 •  (aes128cbc)<br>
 • git 40b3964 (2021-12-06)<br>
<br>
Libs:<br>
 • wxWidgets 3.1.5 (wxMSW 10.0)<br>
 • wxSQLite3 4.6.0 (SQLite 3.31.1)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • lunasvg v2.0.1<br>
 • libcurl/7.61.0-DEV WinSSL<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Build using:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19042), 64-bit edition<br>
 •  English (U.S.) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by whalley** [comment] 2022-01-27 23:41
Will add 'N' as an alternative to 'U' for Unreconcilled transactions

**Comment by 2BeeOrNot** [comment] 2022-01-28 01:25
The choices in detail view are None, Reconciled, Void, Follow up and Duplicate. So N seems appropriate here.
The choices in ledger view are Reconciled, Unreconciled, Void, Followup and Duplicate. So U seems appropriate here.

Since there are more status choices than just reconciled and unreconciled so should the text in both drop down menus be None and the hotkey be N in both views?
And should 'Follow up' and 'Followup' be the same?
![Status Detail](https://user-images.githubusercontent.com/63317977/151469135-0964b4f0-3856-46c7-8abc-2a8ef557dc0e.jpg)

![Status Grid](https://user-images.githubusercontent.com/63317977/151469148-ab5df4a1-c84f-4270-a740-ac3bc50422bf.jpg)

**Comment by whalley** [comment] 2022-01-28 11:06
Good point. Consistency is important.

So we used None (N)  / Reconciled (R) / Void (V) / Duplicate (D) / Followup (F)   in all cases.

Will make this change.

**Comment by tactilis** [comment] 2022-01-28 11:44
As this is a change of terminology and keyboard shortcuts, I feel it is important that the online documentation at http://github.moneymanagerex.org/moneymanagerex/docs/en/index.html and the application's built-in Help text are updated appropriately.

Searching for \*reconcil\*, I find:

============

*6.1 New/Edit Transaction Dialog*

This dialog box will appear for new transactions. Use this dialog to enter the following details:

Date
    This is generally the date of the transaction. Defaults to current day and can be changed.

**Status
    The default is None, but can be changed to Reconciled by the options settings.**

Type
    Transaction Types:

[...]
	
Transaction Status
**Unreconciled
   When you enter a transaction, it initially is in the state of Unreconciled. Which means the transaction has not been reconciled with your bank/credit card company's balance.**

Reconciled
   Once the transaction is checked and verified with a credit card company's balance information, it can be marked as reconciled.

============

*6.4 Reconciling and Balancing Transactions*

Unreconciled Transactions
    This means that they have not been verified with the statement from the financial institution.

Reconciled Transactions
    A transaction can be considered reconciled when the details of the transaction match that from the financial institution.

In MMEX, reconciled and unreconciled transactions are shown by different icons. When bank details are not checked against a bank statement, the user can select to set the default as Reconciled when creating transactions in the Options settings. 

**Tip**
To mark a transaction as reconciled, just select the transaction and hit the R key. **To mark a transaction as unreconciled, just select the transaction and hit the U key.** 

============


Also in https://github.com/moneymanagerex/moneymanagerex/blob/master/src/mmTips.h

Line 26: wxTRANSLATE("Tip: To mark a transaction as reconciled, just select the transaction and hit the 'r' or 'R' key. **To mark a transaction as unreconciled, just select the transaction and hit the 'u' or 'U' key."),**

**Comment by whalley** [comment] 2022-01-28 17:07
Actually having thought about and performed a small poll around the office today :-)  I think 'Unreconciled' is better than 'None' as it more correctly conveys the meaning.

So what about Unreconciled (U) / Reconciled (R) / Void (V) / Duplicate (D) / Followup (F) in all cases.

**Comment by tactilis** [comment] 2022-01-28 17:52
+1

I was getting concerned about the use of None.

The Help will still need to be updated in section 6.1:

"Status
The default is **None**, but can be changed to Reconciled by the options settings."

**Comment by whalley** [comment] 2022-01-28 19:26
Anybody know why we have None and Un-reconciled in the transaction filter? I see why we have both?
![image](https://user-images.githubusercontent.com/487345/151607386-25b09d06-5b64-4098-bdaf-2f2af6ce36a2.png)

**Comment by vomikan** [comment] 2022-01-28 19:52
I don't think it makes sense to investigate this. Obviously, one of the points is superfluous.

**Comment by 2BeeOrNot** [comment] 2022-01-28 20:06
Maybe because none and unreconciled were use as a status choice. Both choices seem to return the same results so none is not necessary if you are going to go with unreconciled. I have no strong feeling as to none or unreconciled. I just wanted to point out inconsistency.

Is it Un-Reconciled or Unreconciled? It's used both ways and should be consistent.

**Comment by whalley** [comment] 2022-01-28 20:17
> Is it Un-Reconciled or Unreconciled? It's used both ways and should be consistent.

https://www.merriam-webster.com/dictionary/unreconciled  

...so I'm going with that.

**Comment by whalley** [comment] 2022-01-28 20:55
Think I caught all the code points to change this... Please test. Docs not yet updated.

**Comment by tactilis** [comment] 2022-01-28 21:12
It's only in a comment, but there's a misspelling of Unreconciled in mmchecking_list.cpp

    else if (key == wxKeyCode('U')) {
        // Unreconcilled

The misspelling makes it harder to search and find all places that deal with unreconciled status

**Comment by tactilis** [comment] 2022-01-28 22:49
> Think I caught all the code points to change this... Please test.

All seems good @whalley

**Comment by tactilis** [comment] 2022-01-28 23:16
A few remaining tidy-ups though...

Note the order of the Status values in these two dialogs:

![image](https://user-images.githubusercontent.com/4060092/151632421-045f6df2-6f1e-44a2-afed-87e5d74b95c9.png)

![image](https://user-images.githubusercontent.com/4060092/151632438-b9ddd7ef-4c72-4901-a5c5-b4acfb297582.png)

For consistency (which enhances speed of comprehension) the Mark context menu should have the values in the same order, i.e. move Unreconciled to the top:

![image](https://user-images.githubusercontent.com/4060092/151632914-e61d848b-22c9-4eb3-8ea2-57676677d9da.png)

Also, IMO, the above Mark menu should say:

```
Mark all selected as  >  Unreconciled
                         Reconciled
                         Void
                         Follow Up
                         Duplicate
```
It doesn't make sense to say 'Mark all **being** selected' because they already **are** selected, and it is redundant to repeat the 'as' on each line of the cascade menu.

**Comment by whalley** [comment] 2022-01-28 23:20
@tactilis Martin do you suffer from OCD? :-)

Yes we can fix that.

**Comment by tactilis** [comment] 2022-01-28 23:36
> Martin do you suffer from OCD? :-)

Just a keen eye for detail and UI optimisation :nerd_face:

...and lots of years in safety involved / safety critical software where such things matter

**Comment by vomikan** [comment] 2022-01-29 10:50
I suggest to redesign the following menu
![image](https://user-images.githubusercontent.com/6836805/151658201-f6491dd7-ac09-4067-9e0b-1389284dd490.png)

**Comment by tactilis** [comment] 2022-01-29 11:12
@vomikan The problem is with the word "being" as used in the menu.

It's not correct usage  in English.

"all being selected" is a process that the user us currently undertaking.

"all selected" is a state.

This is why I proposed: "Mark all selected as", or perhaps better "Mark selected as".

It could even be reduced to "Mark as" because the action _always_ applies to the selected transactions.

I understand what you are saying about difficulty of translation but "Set the status for the selected:" sounds very clumsy in English. (I do appreciate that English is not your native language)

Presumably, a simple "Mark as" would be OK for translation.

**Comment by vomikan** [comment] 2022-01-29 11:14
@tactilis "Set the status for the selected:" or something similar <- !!!

**Comment by tactilis** [comment] 2022-01-29 12:21
Perfect   **<- !!!**   :grinning: 

(but could we please have Unreconciled at the top of the list for the reason I mentioned earlier)

**Comment by 2BeeOrNot** [comment] 2022-01-29 22:17
I like the changes! Consistent order of status choices. Consistent use of followup vs follow up and unreconciled vs un-reconciled. And none & unreconciled is now just unreconciled.

'Mark as' instead of 'Mark all being selected as' is much better.
So suffering from ODC isn't all bad :-)

**Comment by tactilis** [comment] 2022-01-29 22:31
I haven't finished yet!  :grinning:

**Comment by tactilis** [comment] 2022-01-29 22:32
...provided that Mark is happy to keep make the changes.

They will improve MMEX

**Closed** 2022-01-30 14:03 UTC
Labels: bug, fixed
