### ISSUE TITLE
Transaction Report - filter window has an overlapping between 'Specify' and 'Presentation Options' on MacOS

### ISSUE THREAD

**Issue by TulioLazarini** [moneymanagerex/moneymanagerex#6393] opened 2023-12-27 20:00 UTC
MMEX version:
 - [ ] 1.6.4
 - [x] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [X] Mac OSX
 - [ ] Linux 

# Description of the bug

Due to the addition of tag filtering ability in the transaction report, there is an overlapping issue in the 'Transaction Filter' dialog. If one scrolls the upper section ('Specify'), one can see the filtering fields overlapping the presentation options. 

<img width="538" alt="Screenshot 2023-12-27 at 16 49 58" src="https://github.com/moneymanagerex/moneymanagerex/assets/12682580/de87cac7-f15b-4426-a82d-37bbe9a9f8b3">

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Click on 'Transaction Report
2. Scroll through filter options

Expected result:
The filter option fields on the bottom of the Specify box should be hidden / not visible

Actual result:
There is an overlapping between filter fields and presentation options fields.

# Additional information
Bug observed using dmg image installed on a M1 Mac running Sonoma 14.2.1.

If you have a backtrace for a crash or a warning, paste it here.

**Comment by whalley** [comment] 2023-12-27 20:41
I can reproduce. You can resize the panel but it does not save the sizing.

**Comment by n-stein** [comment] 2024-01-25 01:29
May just be an issue with newer versions of macOS? It looks fine on 12.6.5 and size save/restore seems to work as well. 

![image](https://github.com/moneymanagerex/moneymanagerex/assets/16599929/de6d0df4-6bea-463a-93ef-fbaf86eafe15)

**Comment by whalley** [comment] 2024-01-25 20:16
> May just be an issue with newer versions of macOS? It looks fine on 12.6.5 and size save/restore seems to work as well.

It is indeed. Just tried on my old Intel Mac Mini box running 10.15.7 and it works fine.....

**Comment by whalley** [comment] 2024-01-25 20:21
Likely this issue with wxWidgets: https://github.com/wxWidgets/wxWidgets/issues/24067

**Comment by luisdev** [comment] 2024-01-26 08:23
Seems to be ok on my Windows 10 Pro 22H2 Desktop PC with Money Manager Ex:
• Version: 1.7.1-Beta.1 64-bit
• Built on: Jan 24 2024 23:32:17
• Database version: 19 (aes128cbc)
• Git commit: 714352a (2024-01-24)

So, perhaps this is just an issue on Macs?

**Comment by whalley** [comment] 2024-01-26 10:02
Yes it is a Mac issue.

**Comment by whalley** [comment] 2024-06-17 20:09
Resolved in wxWidgets 3.2.5 https://github.com/moneymanagerex/moneymanagerex/issues/6799

**Closed** 2024-06-17 20:09 UTC
Labels: bug, fixed, mac
