### ISSUE TITLE
Dropdown menus issue (duplicated list)

### ISSUE THREAD

**Issue by micoci2** [moneymanagerex/moneymanagerex#6140] opened 2023-07-25 14:29 UTC
MMEX version:
 - [x] 1.6.4
 - [ ] 1.7.0
 - [ ] 1.7.1
 - [ ] 1.7.2
 - [ ] Other (please specify)

Note: bug reporters are expected to have verified the bug still exists
either in the last stable version of MMEX or on updated development code
(master branch).

Operating System:
 - [ ] Windows
 - [x] Mac OSX
 - [ ] Linux 

# Description of the bug

When I open a drop-down list (accounts, payees, categories), for example when I create a new transaction, the drop-down menu shows the list twice (one after the other).
I tried the same database with the latest Windows version, and the list appears only once when I open a drop-down menu. It seems the problem is with the MAC OS version (M2 processor)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps: Create a new transaction, open a dropdown menu (account, payee or category)

Expected result: The list is displayed only once in the dropdown menu

Actual result: The list is displayed twice in the dropdown menu (one after the other)

# Additional information

I tried to do a "Optimize database", but it has no effect.
This problem was not visible with the previous versions of MMEX.
This problem does not appear with the same file used with the Windows version.

**Comment by whalley** [comment] 2023-07-26 18:47
I can't reproduce this.

**Comment by micoci2** [comment] 2023-07-27 14:44
> I can't reproduce this. Is it possible to share some screenshots and a sample database?

Sure ! I cleaned the database to send it to you and I still see the issue.

I send you the database and 2 pictures of the issue.

For information, I can reproduce the problem on Intel Apple and on M2 Apple (with the latest version of MMEX).

To reproduce the issue:
- Open MMEX
- Select the "TestDB2.mmb" database to open it
- Click on the "TestAccount" account
- Click on "Nouveau" / "New" to add a transaction
- Click on the Payee or Category drop-down menu to see the issue

Do not hesitate if you have any other question :)

Regards,

Mike

<img width="516" alt="Duplicate Categories" src="https://github.com/moneymanagerex/moneymanagerex/assets/31414397/72e83de0-629a-42c2-b20d-34e3dc970007">
<img width="438" alt="Duplicate Tiers" src="https://github.com/moneymanagerex/moneymanagerex/assets/31414397/46b93690-1398-4768-a75a-c1c892fd483c">
[TestDB2.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/12184694/TestDB2.mmb.zip)

**Comment by tactilis** [comment] 2023-07-27 15:18
The zip file is didn't attach.

Please simply drag the file here into the 'Write' box.

**Comment by micoci2** [comment] 2023-07-27 15:21
[TestDB2.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/12185098/TestDB2.mmb.zip)

**Comment by micoci2** [comment] 2023-07-27 15:22
It's strange, because I succeeded in downloading it for Github using the following url:

https://github.com/moneymanagerex/moneymanagerex/files/12184694/TestDB2.mmb.zip

**Comment by tactilis** [comment] 2023-07-27 15:38
> It's strange, because I succeeded in downloading it for Github using the following url

Hmmm. I tried twice but the link did not work.
I tried again now and it does. 🙄

**Comment by vomikan** [comment] 2023-07-27 17:32
The zip is OK for me
[TestDB2.mmb.zip](https://github.com/moneymanagerex/moneymanagerex/files/12186219/TestDB2.mmb.zip)

**Comment by micoci2** [comment] 2023-07-27 17:43
Can you reproduce the issue on your computer ?

**Comment by whalley** [comment] 2023-07-27 18:36
I can reproduce. It only seems to duplicate if you already have a Payee or Category defined and then open the dropdown.

![CleanShot 2023-07-27 at 19 33 25](https://github.com/moneymanagerex/moneymanagerex/assets/487345/cbed5504-8c8c-4ed8-9a86-39b8992ca91c)

If I clear the field then it only displays the list once

![CleanShot 2023-07-27 at 19 34 09](https://github.com/moneymanagerex/moneymanagerex/assets/487345/4abb7119-4dac-4c25-aa91-d4c2665fa366)

and after selecting an entry it works correctly only display the list once
![CleanShot 2023-07-27 at 19 35 45](https://github.com/moneymanagerex/moneymanagerex/assets/487345/6ea380bf-faa8-4e19-bf78-66527beaff83)

**Comment by tactilis** [comment] 2023-07-27 18:52
> I can reproduce. It only seems to duplicate if you already have a Payee or Category defined and then open the dropdown.

Interestingly, @micoci2's screenshot here https://github.com/moneymanagerex/moneymanagerex/issues/6140#issuecomment-1653767083 shows the duplicate list can appear when the combobox is empty, which tallies with his reproduction steps:

> - Click on "Nouveau" / "New" to add a transaction
> - Click on the Payee or Category drop-down menu to see the issue

**Comment by micoci2** [comment] 2023-07-27 21:20
Perhaps something changed because this was not happening with MMEX’s previous versions :)

**Comment by whalley** [comment] 2023-07-27 22:18
> Interestingly, @micoci2's screenshot here https://github.com/moneymanagerex/moneymanagerex/issues/6140#issuecomment-1653767083 shows the duplicate list can appear when the combobox is empty, which tallies with his reproduction

Yes happens when dialog is first opened.

**Comment by n-stein** [comment] 2023-07-28 04:14
This is probably due to the fix for #5809.

**Comment by whalley** [comment] 2023-07-28 11:48
This seems to fix it.

**Comment by micoci2** [comment] 2023-07-28 12:45
I installed your 1.7.0-Beta.1 version.

When opening my file, I had this error message:
<img width="333" alt="1 Issue" src="https://github.com/moneymanagerex/moneymanagerex/assets/31414397/212c6005-4c91-43d3-b112-f6a94d370e63">

Is it normal ?

It created a new file...
<img width="511" alt="2 New file" src="https://github.com/moneymanagerex/moneymanagerex/assets/31414397/d9faa662-170b-413f-9b95-bd6518560efd">

Opening this new file, I had this message:
<img width="331" alt="3 Opening new file" src="https://github.com/moneymanagerex/moneymanagerex/assets/31414397/9564909a-1dcb-4420-948b-e55ffc38cb62">

It seems that it had to convert my database. Is it an expected behavior ?

After that, the duplication problem in drop-down menus no longer exists :)

Thank you very much !

Regards,

Mike

**Comment by tactilis** [comment] 2023-07-28 13:06
> When opening my file, I had this error message: Is it normal ?

No, it isn't normal. For some reason your .mmb file was marked as readonly when MMEX tried to write to it.

<br>

Then you tried again and it worked:

> It seems that it had to convert my database. Is it an expected behavior ?

Yes. MMEX 1.7 upgrades the database schema from v18 to v19 to support new features in the app (notably Tags).

Be aware that you will not be able to open the v19 database using MMEX 1.6.4, so if you want to return to that version, you will need to use your upgrade_v18 backup. i.e rename the .bak file to .mmb

**Comment by micoci2** [comment] 2023-07-28 13:08
It makes sense. Thank you very much for your help and your great job !

**Comment by micoci2** [comment] 2023-07-28 13:25
Yes I confirm. You're totally right :) 

Thanks

**Closed** 2023-08-01 21:41 UTC
Labels: bug, fixed, mac
