### ISSUE TITLE
Account View: Columns showing incorrect data in v1.8.1

### ISSUE THREAD

**Issue by TheTeal** [moneymanagerex/moneymanagerex#6975] opened 2024-11-30 21:36 UTC
MMEX version:
 - [ ] 1.7.0
 - [ ] 1.8.0
 - [X] 1.8.1
 - [ ] 1.8.2
 - [ ] Other (please specify)

Operating System:
 - [X] Windows
 - [ ] Mac OSX
 - [ ] Linux 

# Description of the bug

In v1.8.1 the columns are showing incorrect data. Credit account displays fine, but every other account has the balance duplicated in the 'Notes' column, and the notes are being displayed in the 'Last Updated' column. The credit account has a different column layout and assume this could be why it is not affected but don't know for sure.

Correct columns display in v1.8.0:
![v1 8 0 column display](https://github.com/user-attachments/assets/140401c6-6757-4ea6-ad7b-0a3f47508543)

Incorrect columns display in v1.8.1:
![v1 8 1 column display](https://github.com/user-attachments/assets/b97696e7-c696-4360-870f-81f2a76cec8b)

# Reproduction

Is the bug reproducible? 
 - [x] Always 
 - [ ] Randomly 
 - [ ] Happened only once

Reproduction steps:

1. Install v1.8.1
2. Open any account view that is not credit card.

Expected result:

Columns display correct data.

Actual result:

Columns display incorrect data

# Additional information

- A copy of my mmb file for troubleshooting has been sent to mmexregister@gmail.com as requested by Renato on the [related forum thread](https://forum.moneymanagerex.org/viewtopic.php?p=25588#p25588).
- The data seems fine in the database as opening one of these lines shows the data in all the correct fields - appears to be a display issue in the account view only.
- Moving/changing/adding/removing/resetting columns does not resolve.
- Deleting .db3 file from AppData folder does not resolve.
- Uninstalling and reinstalling v1.8.1 does not resolve.
- Rolling back to v1.8.0 the issue no longer exists.

**Comment by TheTeal** [comment] 2024-11-30 22:01
Not sure if it is related in any way or a separate bug entirely, but 'Deleted Transactions' is crashing in v1.8.1 when I click on it and I have to roll back to v1.8.0 to view and remove deleted transactions.

**Comment by renato-mmex** [comment] 2024-11-30 22:26
Many thanks for the .mmb
I can confirm the crash when deleting with version 1.8.1, we will have to make further clarifications.

The following is displayed for me, see:

<img width="544" alt="image" src="https://github.com/user-attachments/assets/5af71931-7c61-44bc-a93b-7877d2ac2751">

we will have to make further clarifications there too.

**Comment by TheTeal** [comment] 2024-11-30 23:04
Thanks for confirming you see both the deleted transactions crash and the bad column data, Renato!

Interesting that the notes are correct for you and the balance is in the last updated column, when it's the other way around for me.

**Comment by renato-mmex** [comment] 2024-12-01 09:27
@jensb @n-stein @whalley 
**From my point of view, this is a language problem.**
My computer has DE-CH and here it works without problems, if I change to EN-US, the columns are displayed incorrectly.
By the way, the data of the .mmb is ok from my point of view.
Since I have only done a few tests on EN-US on a portable version 1.8.1, I have not noticed this.
**May I ask you to look into the problem as soon as possible.**

**Comment by n-stein** [comment] 2024-12-01 13:53
Looks to be related to the column order change we made. 

Do you have any hidden columns? Can you send us your .db3 file?

**Comment by n-stein** [comment] 2024-12-02 00:36
I've identified the cause of both issues and will work on the fixes.

For "incorrect column display" issue, as a temporary workaround open your credit card account and move the column "Credit" all the way to the end (to the right after "Last Updated"). That should make the data display correctly in all account types.

**Comment by TheTeal** [comment] 2024-12-02 00:43
Hi, great to hear you found the root cause, that was quick! Not that it matters any more but no, I didn't have any hidden columns.

I'll use the temporary workaround for now, and look forward to a v1.8.2 maybe in the near future!

Much appreciated.

**Comment by renato-mmex** [comment] 2024-12-02 07:44
Download: https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51089797/job/hyjef8ydur594ais/artifacts

**Comment by renato-mmex** [comment] 2024-12-03 08:50
I would very much welcome an automatic reset of the columns when changing the language, because now the user is confused by an impossible column display.

**Comment by n-stein** [comment] 2024-12-03 23:51
Can you screenshot a bit lower on your About dialog to show the git commit hash? I'm suspecting you might have downloaded a beta that didn't have the pull request merged.

**Comment by TheTeal** [comment] 2024-12-04 01:39
That's probably the issue - Renato sent me a link via email from the forums to the 1.9.0 beta and I didn't realise at the time but can see now that it's different to the link you pasted above. I tried to download the file from your link above instead but Windows flags it as a trojan and removes it for some reason. This isn't affecting me greatly so I might just wait until the next official release!

Below is the screenshot you requested anyway just in case you want to confirm that the link I was given was incorrect: 

![image](https://github.com/user-attachments/assets/accc7aaf-786f-4ba2-aadd-4309872566e8)

**Comment by n-stein** [comment] 2024-12-04 02:54
Yup, you're running a build from the fix for 6971, so the changes for this issue aren't included. You can either download the latest beta from the master branch https://ci.appveyor.com/project/whalley/moneymanagerex/builds/51097058 or wait for the next release. 

Looks like we may be releasing a 1.8.2 shortly to address some of these early issues with 1.8.1, so the wait shouldn't be too long.

**Closed** 2024-12-10 08:39 UTC
Labels: fixed
