### ISSUE TITLE
unsolved: Saved presets in Transaction Filter and saved column formats #4796

### ISSUE THREAD

**Issue by JuanJabo1GH** [moneymanagerex/moneymanagerex#4945] opened 2022-08-18 11:48 UTC
unsolved: Saved presets in Transaction Filter and saved column formats #4796

Hello, please do not consider this problem closed because even in the latest version: mmex-1.5.18 this problem continues, please indicate a solution, they reported that in version: mmex-1.5.17 it had been resolved and that is not real or it was not solved, thanks.

**Comment by tactilis** [comment] 2022-08-18 12:00
@JuanJabo1GH 

Please look again at your issue #4796.

You will see that it has been marked as a Duplicate of #4623, which is confirmed as a Bug and is still Open.

All that has been closed is the duplicate report; this is normal.  See below:
 
![image](https://user-images.githubusercontent.com/4060092/185389227-6666d3b5-4e3c-437c-9107-d9f69590c476.png)

 
  
Now, please could you close _this_ issue (#4945) because you have created yet another duplicate!

**Closed** 2022-08-18 12:21 UTC
