### ISSUE TITLE
Difference Column in Budgets

### ISSUE THREAD

**Issue by SheilKumar** [moneymanagerex/moneymanagerex#5982] opened 2023-06-04 17:41 UTC
# Description of the feature

Please add a column which shows the difference (estimated - actual) in the budget view.

# Use cases

With this column, we can instantly see how much we are in the proverbial green or red. Ideally these columns (or any column in the app) could be color coded either via gradient or specific color such that we can format our views to be more visible by us.

**Comment by tactilis** [comment] 2023-06-04 18:47
Duplicate of https://github.com/moneymanagerex/moneymanagerex/issues/2695

**Closed** 2023-06-06 08:48 UTC
Labels: duplicate
