### ISSUE TITLE
[Arch/Manjaro] MMEX AUR version not starting and Community package has been removed

### ISSUE THREAD

**Issue by Kalucher** [moneymanagerex/moneymanagerex#4220] opened 2022-02-18 17:25 UTC
I have been working with mmex (money manager ex) from few months ago. Now it’s not anymore in the community repo as this indicates: https://archlinux.org/packages/community/x86_64/moneymanagerex/

I have tried to install it by AUR but application doesn’t start getting the error message:

std::bad alloc

If I tried to launch it by terminal by “sudo mmex” it was working instead just “mmex” command, but now even with sudo says that.

I am thinking about installing it as a .deb but I do not have the knowledge...

I really need it for working (I use it on Android as well with no issues)

Thank you

**Comment by vomikan** [comment] 2022-02-20 12:35
10 years ago, this was done by such a person (e-mail in the script).

https://archlinux.org.ru/forum/topic/2787/?page=1#post-28968

**Comment by Arson31** [comment] 2022-02-23 20:12
I'm having the same issue, I can't build it manually either. My only solution is to run it in wine but mmex freezes after password prompt when attempting to open *.emb files.

**Comment by vomikan** [comment] 2022-02-23 21:25
https://aur.archlinux.org/packages/moneymanagerex-git
Maintainer:  @MartinX3

**Comment by MartinX3** [comment] 2022-02-23 21:32
It uses the mmex tags and the current version works for me.
Also I got no error report in the AUR.

Without logs I know nothing. :D

**Comment by Arson31** [comment] 2022-03-05 20:57
I've attached the build error when I try to build using yay
It's complaining about error: ‘class wxDisplay’ has no member named ‘GetPPI’.
Has no one experienced this?
[error.txt](https://github.com/moneymanagerex/moneymanagerex/files/8191464/error.txt)

**Comment by MartinX3** [comment] 2022-03-05 21:10
I read `error: â€˜class wxDisplayâ€™ has no member named â€˜GetPPIâ€™`
Probably you use a localisation, which interferes with the compilation?

**Comment by Arson31** [comment] 2022-03-06 19:48
@MartinX3
It must be an encoding issue with the text file I uploaded.
There's a similar issue but for an Ubuntu distro [#3911](https://github.com/moneymanagerex/moneymanagerex/issues/3911). The issue is still open and I'm not sure if it's been resolved.

**Comment by MartinX3** [comment] 2022-03-06 19:59
Oh.
Does it work with paru?
Paru is the yay successor written in RUST.

**Comment by Arson31** [comment] 2022-03-07 22:50
@MartinX3
I get the same error when trying to install using Paru.

**Comment by MartinX3** [comment] 2022-03-07 23:11
@Arson31 
Is your part different?
```-- MMEX configuration summary
-- ==========================
-- Version        : 1.5.13
-- Commit         : d019150be (2022-02-06)
-- Host system    : Linux x86_64
-- Target system  : Linux x86_64
-- Build types    : Release
-- Generator      : Unix Makefiles
-- Install prefix : /usr/local
-- DB encryption  : ON
-- 
-- Versions
-- --========--
-- Linux 5.15.26-1-lts
-- EndeavourOS rolling 'rolling'
-- CMake 3.22.3
-- GNU Make 4.3
-- ccache 4.5.1
-- GNU 11.2.0
-- wxWidgets 3.1.5
-- wxSQLite3 4.6.0
-- RapidJSON 1.1.0
-- Lua 5.4.4
-- curl 7.82.0
-- gettext 0.21
```

**Comment by Arson31** [comment] 2022-03-08 19:45
@MartinX3 
Doesn't look different, this is what I see from yay or paru:
 yay -Si moneymanagerex-git 
:: Querying AUR...
Repository      : aur
Name            : moneymanagerex-git
Keywords        : mmex  moneymanagerex
Version         : 1.5.13-1
Description     : MoneyManagerEx is an easy-to-use personal finance suite. This package will always point to the newest tagged version.
URL             : http://www.moneymanagerex.org/
AUR URL         : https://aur.archlinux.org/packages/moneymanagerex-git
Groups          : None
Licenses        : GPL
Provides        : moneymanagerex
Depends On      : wxgtk3-dev  webkit2gtk
Make Deps       : curl  cmake  fakeroot  file  gawk  gcc  gettext  git  jq  lsb-release  make  pkg-config
rapidjson
Check Deps      : None
Optional Deps   : cups
Conflicts With  : moneymanagerex
Maintainer      : MartinX3
Votes           : 7
Popularity      : 0.247056
First Submitted : Sun 12 Feb 2017 01:38:26 PM CST
Last Modified   : Sun 06 Feb 2022 10:37:28 AM CST
Out-of-date     : No

**Comment by MartinX3** [comment] 2022-03-08 20:15
And the package versions?

**Comment by Arson31** [comment] 2022-03-09 14:46
I've got mmex installed 1.5.13 installed by reinstalling wxgtk3-dev and webkit2gtk:
yay -Syu wxgtk3-dev webkit2gtk

The only problem is the interface is broken, I'm stuck on the homepage and the bar chart on the right is not showing.

**Comment by MartinX3** [comment] 2022-03-09 14:50
@Arson31 if you need to reinstall these packages I assume that your arch installation is broken.
As example the package `wxgtk3-dev` had no update since 2021-04-16

**Comment by Arson31** [comment] 2022-03-11 04:02
@MartinX3 I've got this working normally, Onedriver was not retrieving the current version of the database and was acting strange. running the command above got past the build and install.

**Comment by MartinX3** [comment] 2022-03-11 07:32
Perfect.
@vomikan please close this issue.

**Closed** 2022-03-11 12:45 UTC
Labels: linux
