### ISSUE TITLE
General report manager can't create custom reports

### ISSUE THREAD

**Issue by malapradej** [moneymanagerex/moneymanagerex#1746] opened 2018-07-23 22:43 UTC
**Your OS:**
- [ ] Windows
- [ ] Mac OSX
- [x] Linux 
- [ ] Android -> please report bugs to moneymanagerex/android-money-manager-ex repo!

**MMEX version:**
- [x] 1.4.x
- [ ] 1.3.x
- [ ] 1.2.x
- [ ] 1.1 or older
- [ ] development version (git master branch)

**Comment by malapradej** [comment] 2018-07-23 22:45
The **general report manager** comes up with an error page, below:

![image](https://user-images.githubusercontent.com/5550345/43106863-75475e62-8ed2-11e8-9922-e5cbe1a2ef0e.png)

**Comment by malapradej** [comment] 2018-07-23 22:50
Solved. One has to right click on **Reports** and then choose new report from the menu list. But it still show the **Unable to load page** above, with `file:///usr/share/doc/mmex/help/general_report_manager.html` missing.

**Comment by malapradej** [comment] 2018-07-23 22:55
Solved. One has to right click on **Reports** and then choose new report from the menu list. But it still show the **Unable to load page** above, with `file:///usr/share/doc/mmex/help/general_report_manager.html` missing.

**Comment by vomikan** [comment] 2018-07-25 05:58
https://github.com/moneymanagerex/moneymanagerex/blob/master/docs/grm.html

**Comment by vomikan** [comment] 2018-07-25 06:00
Could you please put this page manually?
Seems another bug here.

**Comment by malapradej** [comment] 2018-07-25 12:10
Yes, what I did was rename `/usr/share/doc/mmex/help/grm.html` to `/usr/share/doc/mmex/help/general_report_manager.html` and it worked.

**Comment by slodki** [comment] 2018-07-29 21:20
Duplicate of #1177 - fixed in 1.4.0-alpha.2

**Closed by slodki** 2018-07-29 21:20 UTC
Labels: duplicate
