### ISSUE TITLE
Ability to change account balance without transaction

### ISSUE THREAD

**Issue by regs01** [moneymanagerex/moneymanagerex#1678] opened 2018-05-18 01:00 UTC
Sometimes there are so many little spending, so it's annoying remembering them all and make a change for every cent or boiling the brain with total spendings, cashbacks etc.

So would be good to have ability just to set current account balance as a recorded change.

**Comment by vomikan** [comment] 2018-05-18 06:48
An account balance is sum of unitial balance + sum of all transactions in the account. In case if some transaction missing or value is incorrect the balance will be wrong. 
By design to have proper valances all transactions should be entered and reconcilled.
Seems your proposal goal is make reconcillation process more ligth (for lazy or busy accountant). But I can't understand what exactly you looking for.

**Comment by StefanRickli** [comment] 2018-05-18 08:06
Agree that we always need a transaction.

What @regs01 suggests might be achieved by having a dialog along the line "Enter current balance". The difference to the last recorded balance would then be automatically added as a transaction with a configurable category, e.g. "minor spendings".

**Comment by slodki** [comment] 2018-05-18 11:56
Account balance adjustment must be entered as a transaction.
MMEX displays account balance after each transaction - if you need different then calculated you can add fake transaction before or after with the same date, category "other income/expences" (or your own category for this case only) and note describing reason you manually adjust the balance.
I can see problem with payee field (it cannot be null now) - you can create "unknown" one for this propose.

**Comment by gabriele-v** [comment] 2018-05-18 12:15
Yes, I use the same way, just enter a new transaction with Payee "unknown" and category "reconciliation errors" so you know how much you have adjusted simply filtering by category

**Comment by slodki** [comment] 2018-05-18 12:46
I've created #1679 for payee field simplification

**Comment by StefanRickli** [comment] 2018-05-19 16:17
I don't know how @regs01 came up with the idea, but in my case I used GnuCash a while ago, where the [reconciliation](https://www.open-of-course.org/courses/file.php/13/GnuCash%20Tutorial%20and%20Concepts%20Guide/txns_reconcile.html) dialog would allow me to do (among other things) what I described earlier.

So when I first used MMEX of course I looked for something similar and couldn't find it.
I then later found out that one can use simple formulas in the amount field which allows for easy difference calculations. If this feature were more obvious (discoverable), then maybe this issue won't arise anymore.

Is wxW able to have a greyed out text inside a text box as long as the user hasn't entered something or the cursor is inside?
We could then use this grey-text to display something like "1+2, or 4-1, or 3" as long as the amount field is empty.

![image](https://user-images.githubusercontent.com/19881323/40270607-a252da14-5b90-11e8-83a6-ee0beb00565b.png)

**Comment by vomikan** [comment] 2018-05-19 17:30
This feature is exist. I don't rember it name.

**Comment by gabriele-v** [comment] 2018-05-19 17:31
Should be SetHint() or something Iike that

**Comment by StefanRickli** [comment] 2018-05-19 17:36
[Found it](http://docs.wxwidgets.org/3.0/classwx_text_entry.html#a4e9dfe958dbd1918c54b45be83f1bed4).

If you think that it's desirable to have such a hint, I'd add a new issue for that as it's not exactly what OP asked for.

**Comment by vomikan** [comment] 2018-05-19 17:49
Yes. SetHint. But it has stupid bug. The hint text may be not removed when you start typing.

**Comment by regs01** [comment] 2018-05-19 17:51
> What @regs01 suggests might be achieved by having a dialog along the line "Enter current balance". The difference to the last recorded balance would then be automatically added as a transaction with a configurable category, e.g. "minor spendings".

Or could be simpler. There are 3 types - withdrawal, deposit and transfer. There could be 4th - balance change, where number field below would mean desired final figure. Transaction still could be there, just an app will calculate and display the difference itself, rather than using calculator app.

**Comment by gabriele-v** [comment] 2018-05-19 17:56
Coding-side it will be easier the new dialog, for sure.
UX side I think it will be more clear too, because with your suggestion, amount field will be used for two different amounts: transaction amount in "standard" case and account balance in your case. We should try to avoid misunderstandings and keep MMEX as simple as possible.

**Comment by gabriele-v** [comment] 2018-05-19 17:58
It could be placed in the menu that opens when you right click the account in the tree, so it will require just the amount and doesn't need an additional dialog to be created.

**Comment by vomikan** [comment] 2018-05-19 18:00
KISS ))

**Comment by slodki** [comment] 2018-05-19 18:14
I think new Reconciliation wizard can handle both cases:
a) when account balance matches statement - user can use button like `Mark transactions as reconciled` 
b) when there is a gap between MMEX account and bank statement - user can use button `Add adjustment transaction`

User input:
- account selected
- start date
- end date
- account balance at the beginning of the period
- account balance at the end of the period
MMEX calculated output:
- initial db balance
- summary of income transactions (number, amount)
- summary of outcome transactions (number, amount)
- number of transactions marked/not marked as reconciled in period given
- final db balance
- initial balance gap
- final balance gap
Possible user actions:
- change status for all transactions
- add adjustment transaction at the beginning/end of the period

**Comment by gabriele-v** [comment] 2018-05-19 18:17
That's a long term view but yes, it will be the definitive solution! :)

**Comment by StefanRickli** [comment] 2018-05-19 20:05
@vomikan 

> Yes. SetHint. But it has stupid bug. The hint text may be not removed when you start typing.

Was that a known issue in wxW (possibly tracked in their issuetracker and solved in the meantime) or was it an MMEX specific issue such that it SetHint wasn't used?
Can it be reproduced easily? If so, I could have a look into it.

@gabriele-v 

> We should try to avoid misunderstandings and keep MMEX as simple as possible.

Totally. Mixing absolute and relative amounts in the same field certainly is going to cause some confusion.

@slodki 

> I think new Reconciliation wizard can handle both cases:

Sounds like a very good solution.

**Comment by StefanRickli** [comment] 2018-05-19 20:18
Meanwhile regarding the hint:
If we can't use SetHint, can we change the tooltip for the amount field that explains that we can not only enter numbers but formulas?

In `transdialog.cpp:1185-1202`: from
"Specify the amount for this transaction"

to
"Specify the amount for this transaction. You can also enter simple formulas like ""3.25-1.5""."

**Comment by vomikan** [comment] 2018-05-19 20:28
Hints and tooltips needed only for new users. 
Then it became annoing. 
One more option is using wxRichToolTip several times for new app installation or untill user switch off this feature.

**Comment by vomikan** [comment] 2021-07-31 19:08
> Account balance adjustment must be entered as a transaction.
> MMEX displays account balance after each transaction - if you need different then calculated you can add fake transaction before or after with the same date, category "other income/expences" (or your own category for this case only) and note describing reason you manually adjust the balance.
> I can see problem with payee field (it cannot be null now) - you can create "unknown" one for this propose.

I think so too.

**Closed by vomikan** 2021-07-31 19:08 UTC
Labels: feature
