### ISSUE TITLE
Can't Update Portfolio with the latest Price for shares in Money Manager EX

### ISSUE THREAD

**Issue by MyronAG** [moneymanagerex/moneymanagerex#5932] opened 2023-05-22 17:53 UTC
> When trying to update the share price in Portfolio for Money Manager EX error encountered Invalid Cookie
> Please do not remove information attached below this text.

<hr> • Version: 1.6.3 64-bit<br>
 • Built: Jan 31 2023 12:09:35<br>
 • db 17 (aes128cbc)<br>
 • git 48d8562 (2023-01-31)<br>
<br>
Libs:<br>
 • wxWidgets 3.2.1 (wxMSW 10.0)<br>
 • wxSQLite3 4.9.1 (SQLite 3.40.0)<br>
 • RapidJSON 1.1.0<br>
 • Lua 5.3.5<br>
 • libcurl/7.82.0-DEV Schannel<br>
 • gettext 0.19.8.1<br>
 • apexcharts.js<br>
<br>
Built with:<br>
 • CMake 3.16.2<br>
 • MSBuild 15.9.21.664<br>
 • MSVS15.0<br>
 • MSVSC  19.16.27035.0<br>
 • Windows SDK 10.0.14393.0<br>
<br>
OS:<br>
 • Windows 10 (build 19045), 64-bit edition<br>
 •  English (India) (windows-1252)<br>
 • 1920x1080 32bit 96x96ppi

**Comment by MyronAG** [comment] 2023-05-22 18:01
![image](https://github.com/moneymanagerex/moneymanagerex/assets/134319513/09a43e7d-adb0-46cd-8183-cd2e2ca6bc44)

**Comment by tactilis** [comment] 2023-05-22 20:24
Known problem in 1.6.3.

Duplicate of #5890.

See also #5894

**Comment by MyronAG** [comment] 2023-05-23 15:41
Noted on this. I hope they are working on a fix.

**Comment by tactilis** [comment] 2023-05-23 17:07
@MyronAG 
> I hope they are working on a fix.

It is fixed. It will be part of the 1.6.4 release soon.

**Comment by reddyshyam** [comment] 2023-05-24 19:22
Now I am getting this with latest 1.6.4 beta

![image](https://github.com/moneymanagerex/moneymanagerex/assets/12392746/372cdcf6-5549-4708-afd5-05b265addac6)

**Comment by n-stein** [comment] 2023-05-25 02:39
Seems the v6 API is not functioning. Not sure if it's temporary or permanent.

**Comment by reddyshyam** [comment] 2023-05-25 04:32
> Seems the v6 API is not functioning. Not sure if it's temporary or permanent.

Hi @n-stein, thanks for getting back. Let's see if this is temporary or permanant. Just brought to your notice, that is all. Edit stock and update history still works, so not an issue.

**Comment by vomikan** [comment] 2023-06-09 14:41
> Any idea when the next release of Money Manager will be out with the problem fixed?

ASAP

See the progress: https://github.com/moneymanagerex/moneymanagerex/milestone/41

**Comment by MyronAG** [comment] 2023-06-24 12:21
Thank you all for the new version. Stock update feature is back working. 

Much appreciated.

**Comment by GCLynda** [comment] 2023-08-15 06:20
Is anyone able to confirm what the Yahoo url should be please as when I select the automatic update icon, I receive an error message as under:- 
![image](https://github.com/moneymanagerex/moneymanagerex/assets/46233864/6f0c169e-11c3-43d6-9f9d-d1ac8194a8be)

My database has url as:  
![image](https://github.com/moneymanagerex/moneymanagerex/assets/46233864/20a34865-c924-4495-b95a-395d21c6d262)

Using
![image](https://github.com/moneymanagerex/moneymanagerex/assets/46233864/4a8f06bb-0f84-49c6-8433-0cd4bd4709a6)

**Comment by n-stein** [comment] 2023-08-16 01:08
> Is anyone able to confirm what the Yahoo url should be

This is a common misconception. The URL in the options dialog has nothing to do with share price downloads, it is simply the page navigated to when you right click on a stock and select "Stock Web Page". The URL for share prices is hard coded into the app and can't be modified by end users.

Stock refresh errors were corrected in 1.6.4 for non-GDPR countries. It has subsequently been corrected for GDPR countries, but you need to use the 1.7.0 beta. Take a backup of your database (beta builds may be unstable, although it's in a decent state currently) and try the beta here: https://ci.appveyor.com/project/whalley/moneymanagerex. Note that the beta will update your database version, so you must use the backup if you need to go back to 1.6.4 for some reason.

**Comment by GCLynda** [comment] 2023-08-16 04:20
thanks for that n-stein - I'll give the 1.7.0 beta a trial :-)..  Cheers!!

**Closed** 2023-08-17 08:01 UTC
Labels: duplicate

**Comment by franci207** [comment] 2023-09-07 05:29
i use version 1.7.0 beta for windows64 but the quotes update problem continues. when I try to update the quotes I get the error URL USING BAD/.......
